GTNewHorizons/GT-New-Horizons-Modpack

- scripts/Minecraft.zs
Somehow Minecraft's Dark Oak doesn't count towards minecraft:log:*
Funny.
> Made Crafting table recipe use oreDictionary

- .gitignore
- config/SpiceOfLife.cfg
- config/harvestcraft.cfg
One will need a lunchbox or two lunchbags (6 types of different food
type) to enjoy the food with 100% of its value eating 4 of the same type
food from a stack at a time.
Also, disables HarvestCraft bees.
Closes #449
> Tweak HungerOverhaul/SpiceOfLife food properties

- scripts/Chisel.zs
Squashed commits
5bf056e83c53f7f981499ff85e76ca302d1b200f
ec80d80bf43a5a0a360cd114451609556a8e1381
c53a74676cd9f34e8cacfb94d69d5b22bcc1ba84
51df01db65a911c635a2c5a8520d968d8b2436f6
6857234e12b51349e50bba4be171761d449833c8
from Patches-Arnab into one, coherent branch.
Original commit below
=====================
Add chisel recipes
Clear glass and quite clear glass should be now chiseled into glass and
it types. (Since Clear glass can be made by the player relatively easily
and can also be broken by hand, these recipe wont do harm)
Add Quarried stone to be chiseled into marble (hopefully)
Add future support for stained glass being chiseled into their
equivalent colour blocks from witchery,ztones and tconstruct
> Add chisel recipes for glass and marble

- config/gendustry/bees.cfg
`[Client thread/WARN]: Adding mutation failed: Block not found minecraft:gregtech:gt.blockgem3 (RsMutation(gendustry.bee.Emerald,gendustry.bee.RedGarnet,gendustry.bee.YellowGarnet,3.0,false,List(MReqBlock(StackBlock(minecraft,gregtech:gt.blockgem3,2)))))`
> Fixed gendustry.bee.YellowGarnet

- config/ForbiddenMagic.cfg
```
[18:44:53] [Client thread/FATAL]: Focus Upgrade id 42 already occupied. Ignoring.
[18:44:53] [Client thread/FATAL]: Focus Upgrade id 43 already occupied. Ignoring.
```
I have no idea how to see/dump focus upgrade IDs, but changing it to 142-143 seems works. No more log warn and Forbidden Magic focus upgrades available ingame.
> Focus Upgrade id conflict

- scripts/CoreMod.zs
Charcoal, redstone and glass overwrote the other three recipes without row specification.
> Fix XP bucket recipes

- scripts/Adv-Solar-Panel.zs
- scripts/Emt.zs
- scripts/Galaxy-Space.zs
- scripts/GraviSuite.zs
- scripts/IC2.zs
https://github.com/GTNewHorizons/NewHorizons/issues/1084
Seems IC2 doesn't like "*" as reference to itemArmor damage. Changing it to 1 works fine, no more console spam. You may also want to add recipes with damage 26 (discharged).
> Prevent IC2+NEI console spam

- config/adventurebackpack.cfg
Config cleanup
Enable OpenBlocks Grave compatibility (fix https://github.com/GTNewHorizons/NewHorizons/issues/1113)
Tanks overlay moved to corner
> AdventureBackpack config

- config/adventurebackpack.cfg
- scripts/Advanced-Backpacks.zs
> Fixed NBT for Copter/Jetpack

- scripts/Extra-Trees.zs
- scripts/IC2.zs
These code changes are all necessitated by the recent changes to extra trees to remove the booze making functionality with it.  All the commented out items were removed, and as such, the itemid for the glass fittings was changed.
As a side note, glass fittings are not used in any recipes that I can find, might be something to consider in updating future recipes.
> Extratrees fixes

- scripts/Natura.zs
Adds the rest of the Natura fruits (nether berries and saguaro fruit) to the oredict so that they can be used interchangeably with other Harvestcraft fruits in recipes.
> Add remainder of Natura fruits to oredict

- config/OpenBlocks.cfg
- scripts/Open-Blocks.zs
Hello, @Dream-Master 
Default setting of this device make it useless at all. I bumped all parameters. Now this sprinkler can be compared with basic watering can from ExtraUtilities, but automated.
Because of that, recipe changed (now this gadget available on mid/end MV age).
With these changes I recommend you to add quest for this (now *useful*) device. It (*in my horrible opinion*) fits into Forestry branch after quest "Your first multiblock farm".
//If you want, I'll try to add this quest myself.
> Sprinkler from OpenBlocks made more usable.

- config/HungerOverhaul/HungerOverhaul.cfg
- config/OpenBlocks.cfg
These changes are related to my previous PR. Ones don't change so much balance in early-game, but give players some technical "buffs" (like useful sprinkler) in mid-game.
Change in HungerOverhaul doesn't break early-game balance, because main configuration for growth acceleration is ```B:modifyBonemealGrowth=true```. (I tested this)
> Tweaked growth speed configuration.

- scripts/Extra-Utilities.zs
@Dream-Master 
Be aware, when you remove recipes with
```
recipes.remove(<...>);
```
This command removes **_all_** crafting recipes. Better to use one of these:
```
recipes.removeShaped(<...>);
recipes.removeShapeless(<...>);
```
(In most cases - when recipe was registered with default crafting handler - these ones works fine).
This pull request restores recipes for Inverted and Fuzzy Item filters, removed *in similar way*.
> Added back removed recipes for inverted item filters.

- scripts/Binnies-Core.zs
Recipes for Compartments (from Binnie Core) was **_too_** hard.
For example: Diamond Compartment required Tungstensteel Frame Box (maybe, block id/meta changed after time; if so - **_please, use OreDictionary_**). 
Also these recipes used strange syntax (maybe outdated); this PR fixes it.
Where possible recipes use OreDictionary.
P. S. @Dream-Master 
When you add missing in GT components, please, check OreDictionary tags of existing components.
For example: *Diamond Frame Box* should be registered as ```frameGtDiamond```.
> Changed recipes for Compartments

- scripts/Extra-Trees3.zs
Recipes for ET vanilla-type fences had wrong outputs. Maybe ET version moved up since these scripts were written?
> Fix #2259 - Crafting fences makes "_Wood Slab"

- config/harvestcraft.cfg
- scripts/Harvestcraft.zs
Prevents obtaining infinite sodium and chlorine using the Harvestcraft salt recipe. (Infinite Na is still available from centrifuged ashes, and infinite Cl from centrifuged stone dust.)
This patch requires the corresponding patch in the GTNH coremod: https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/25
Credit to @JasonMcRay for the artwork and original implementation.
> Replace Pam's salt with Edible Salt

- scripts/IC2.zs
Quick fix for the Thick Neutron Collector for GTTweaker 1.7.0 
Since the Neutron Reflector item doesn't stack
> Fixing the Thick Neutron Collector (GTTweaker 1.7.0)

- config/GTNewHorizons/angermod.cfg
- config/betterquesting/DefaultQuests.json
https://github.com/GTNewHorizons/NewHorizons/issues/2202 This change will add the knife and butchery knife to the blacklist for kamikaze explosions. Explosion percentage has also been increased from 5 to 10 percent to compensate and encourage use of these tools for farming.
> Make knives and butchery knives prevent mob explosions

- config/GraviSuite.cfg
Moves the GraviSuite HUD from the overloaded upper left corner to the bottom left corner (below the chat).
> GraviSuite HUD

- config/gendustry/bees.cfg
fixes for:
```
[Client thread/WARN]: Adding mutation failed: Block not found Taintedmagic:BlockShadowmetal (RsMutation(magicbees.speciesTCChaos,magicbees.speciesTCVoid,gendustry.bee.Shadowmetal,6.0,false,List(MReqBlock(StackBlock(Taintedmagic,BlockShadowmetal,32767)))))
[Client thread/WARN]: Adding mutation failed: Species 'gendustry.bee.Tungsten ' not found (RsMutation(gendustry.bee.Jupiter,gendustry.bee.Tungsten ,gendustry.bee.Mercury,12.5,false,List(MReqBlock(StackBlock(GalaxySpace,venusblocks,32767)))))
```
> Gendustry log warns

- config/gendustry/bees.cfg
Made Redstone Comb not a Special Product for Redstone Bees. 
Made Aluminium Comb not a Special Product for Aluminium Bees.
Changed output of Firestone Comb to 15%.
Increased Shard Comb output to 20%.
Added Basalt, Marble, Redrock, Red Granite, Black Granite to Stone Comb output (50%).
Changed output of Certus Comb to Certus Dust (80%).
Changed the output of Fluix Comb to Fluix Dust (25%).
Changed output of Redstone Comb to Redstone Dust (100%).
Changed output of Lapis Comb to Lapis Dust (100%), Lazurite Dust (80%) and Sodalite Dust (60%).
Changed output of Tiny Pile of Graphite Dust to 75% from Diamond Comb.
Changed output of Red/Yellow Garnet Comb, Pyrope Comb and Grossular Comb to 100% for main outputs.
> Bee adjustments and OCD cleanup

- scripts/Gregtech.zs
- scripts/Tinkers-Construct.zs
I ended up fixing all of the ardite recipes. All of the recipes worked with the Tinkers Construct version of the Ardite Ingot but not the GregTech Ardite Ingot. I simply swapped this in the Tinkers-Construct.zs script. If you'd prefer these commented out and added to the GregTech.zs Extruder section let me know and I can do that instead. If you have any questions please let me know either on Issue 2967 or in Discord.
> Fix for Issue 2967

- config/betterquesting/Readme.md
Major update with new IC2 quests and PTFE quests.  Re-ararnged some quests to make better sense. Fixed minor typos. Added super tank 2 and 3 quests. Addeed some more info for newbies to understand pipes and water generation. Added printer quest for Seismic Prospector. Added info on steam outputs cannot be blocked. Removed outdated oil cracker info. Added info on more ways to get gallium and arsenic.
Added readme.md file to BQ config directory with instructions on how to use it.  Plz keep up to date.
> Moron quest update q42018

- config/betterquesting/Readme.md
moved redstone quest to after upgrade 2.0 so players find out about cauldron cleaning sooner and can clean redstone for their ore wand
underground fluids quest after moon.
updated ic2 crops starting quest
Tips for monsters
Railcraft boiler tips
Backpacks config option to wear backpack
Bees breeding - Need purebreed bees
tier 0 quests for tips on dealing with infernals and other monsters
spectre glass for nether portals, spectre key, spectral armor
stairs quest
Openblocks fan quest
EBF tips
A bunch of new pam's foods quests
enderio magnet
Added some base tier coins quests for animal products like leather/wool/eggs
Added flood gate quest
> Big quest update -

- scripts/Chisel.zs
https://github.com/GTNewHorizons/NewHorizons/issues/4188
Left Abyssal Stone in the Black Granite group instead of moving it to the Basalt Group by popular demand.
Sorry about the two pull requests, apparently I'm bad at github?
> Gregtech Stone Chisel Compatibility

- scripts/Minecraft.zs
I just found an issue when tried to convert TiC glass to vanilla glass.
The old recipe consumed the GT chip, and I fixed that.
> Fix Blast Furnace Glass Recipe

- scripts/Thaumcraft-04-Artifice.zs
- scripts/Tinkers-Construct.zs
Because Mirrored Glass cann't be made with Resonant Ender Bucket of GT ++
> Made Mirrored Glass recipes compatible with Ordict

- scripts/CoreMod.zs
Change recipe from shape:
B = XP Bucket
```none
╔═══╤═══╤═══╗
║ B │   │ B ║
╟───┼───┼───╢
║ B │ B │ B ║
╟───┼───┼───╢
║ B │ B │ B ║
╚═══╧═══╧═══╝
```
To this new recipe:
```none
╔═══╤═══╤═══╗
║ B │ B │   ║
╟───┼───┼───╢
║ B │ B │ B ║
╟───┼───┼───╢
║ B │ B │ B ║
╚═══╧═══╧═══╝
```
> fix #5517 Conflicting recipes for leather and gold dust

- scripts/Blood-Magic-Thaumcraft.zs
- scripts/Forbidden-Magic-01-Wands.zs
- scripts/Tainted-Magic-1.zs
- scripts/Thaumic-Bases-01-Main.zs
- scripts/Thaumic-Exploration-01.zs
- scripts/ThaumicTinkerer-01.zs
- scripts/ThaumicTinkerer-02-Kami.zs
- scripts/Warp-Theory.zs
* Returned back old research keys for rods and wands to fix the issue that NEI can't show some wand recipes.
* Removed en-localizations that duplicates standard ones (Didn't remove changed texts, only duplicated)
> Thaumic improvements

- scripts/CoreMod.zs
- scripts/Thaumcraft-01-Basic.zs
#5643 
Some players don't progress through the quests and don't know the effect of warp,
So move it to an easy-to-understand position to indicate that Warp is dangerous,
> Moving WarpWarinig's research to Vanilla TC Basic Information tab

- config/AppleCore.cfg
If true, shows the hunger and saturation values of food in its tooltip automatically (without needing to hold SHIFT)
B:show.food.values.in.tooltip.always=true
How do you think @Dream-Master
> apple core show tooltip always

- scripts/Ztones.zs
Add any mushroom block as ingredient rather than specific meta 0 brown mushroom block.
Address issue [Mushroom Block With Chisel Support](https://github.com/GTNewHorizons/NewHorizons/issues/5701).
> fix(ztones): myst block recipe

- README.md
- quest 1780: find => found
- quest 1834: rwg => RWG | it's an acronym (tho "rwg" might have been intended)
- Readme: Corrected some typos, also checked with Grammarly for the commas
> Fixed quest typo and readme typos

- scripts/Natura.zs
As of https://github.com/GTNewHorizons/Natura/commit/34cfe9c82acae7995de2a70aae308f2310610a2c  Natura registers its fruits with the same tags that the Natura.zs script does.
> Don't register Natura fruit to the ore dictionary, Natura now does that itself

- config/AWWayofTime.cfg
AE2MatrixFrame is a non-destructible transparent block of storage cell Dim.
> Add AE2MatrixFrame to teleposer blacklist

- scripts/Minecraft.zs
Oredict the crafting table recipe to support modded logs in the assembler. Something to be aware of: this replacement adds several (62) more recipe pages in NEI.
> oredict the assembler crafting table recipe

- scripts/Biome-o-Plenty.zs
If you include a Bucket of Water and it also looks like Clay Bucket of Water you automatically get the bucket back without needing to script it in. This why it was duplicating.
This not the case with all mods but it's the case here. You can also add a .noReturn() for those times you want it to be consumed.
This fixes:
#6424
#6354
#6256
#6230
#5727
#5591
#6089
#6514
> Fixed Water Bucket Dupe with Mud Balls

- scripts/Blood-Magic-Thaumcraft.zs
Removes infinity requirement because the device is no longer broken as shown in #5675.
>  Life-Imbuer-Revert

- scripts/Emt.zs
#2607, #3609 Should be already fixed? But also made it so quantum traveller boots recipe is wildcarded (#6300)
> Traveller boots fix

- scripts/AE2.zs
Fix missing brown smart cable recipe in AE2. Issue #2439 
Using dyeBrown ore dictionary.
> Fix issue 2439, no recipe for brown smart cable in AE2.

- scripts/Gregtech.zs
- scripts/Minecraft.zs
Fix issue #3556 remove Pam's Beet to sugar in mortar. Add Sugar Beet (Crops++) to mortar but only 4 sugar. Get 8 in extractor still. Tried to add to Crops++ source but I couldn't even get Crops++ to build from fresh clone so bart will need to add it there if you want in code.
> Issue3556 Sugar from Beet removed.

- .github/workflows/stale.yml
This essentially creates a stale bot that mark stale issues and close them if no activity happens after marking.
An issue is considered stale when
1. It is a balancing related change and it has not been updated in 90 days.
2. It is related to an official server and it has not been updated in 90 days.
3. It cannot be reproduced and it has not been updated in 180 days.
The bot will run 12 times per day, as we have quite a few issues to handle.
> Add Mark stale issues github action

- scripts/Emt.zs
new recipe for diamond chainsaw - see #6562
new recipe for iron omnitool (previous recipe did not consume GT tools) - see #4008 and #2694
changed recipe for diamond omnitool (previous recipe did not consume GT tool; GT tool is now center item and will be consumed) - see #2694
verified crafting of Nanosuit Boots of the Traveller - see #3609 and #2607
adressed revert of PR#6474
added oredict for arcane crafting (not possible to set oredict for infusion crafting, however it works ingame) - see #6474
fixed various spelling/grammar mistakes
all tested and working with 2.0.9.0QF4
> Updated Electro-Magic Tools Script file

- config/Betterloadingscreen/tips/en_US.txt
> [BetterLoadingScreen] "It's NEI, not JEI"-tip fix

- scripts/Galacticraft.zs
- scripts/Gregtech.zs
fix molten void autoclave recipe of TC crystal powders only giving air shards instead of their respective shards
Change Arc Lamp and Frequency Module recipes to use GT battery instead of GalactiCraft battery to allow proper autocrafting
> fix autoclave of TC dusts / allow autocrafting of Galacticraft items

- scripts/Tainted-Magic-1.zs
Fixes uncraftable items due to requiring unobtainable tainted magic items (block of shadowmetal and shadowmetal ingot)
-Shadowmetal hoe
-Shadowmetal pickaxe
-Shadowmetal axe
-Shadowmetal shovel
-Shadowmetal sword
-Wand focus: mage's mace
-Shadow fortress helm
-Shadow fortress cuirass
-Shadow fortress thigh guards
> fixed various recipes that use shadowmetal

- config/bartworks.cfg
I missed this number before, so it regenerates the list.
> Actaully prevent getting IV loot on ross

- scripts/Draconic-Evolution.zs
Make the first magnet actually craftable at a point earlier than the HV EIO one.
DCT->normal crafting table, otherwise it's HV locked, and you can make them all 3 involved at about the same time.
> Fix magnet derp

- config/TMechworks.cfg
To prevent cheesing solar boilers. Probably prevents crashes with other blocks too, given how buggy I hear DBs are. Why are TEs even allowed to begin with?
> Add GT blocks to the blacklist of the drawbridge

- scripts/AE2.zs
mistake when removing ME pattern recipe (used MultiPart instead of MultiMaterial).  Remove additional recipe for brown smart cable as you can now craft it the intended way
> Fix brown smart cable properly

- scripts/AE2.zs
via shapeless crafting
Clean up script file while I am at it (no other code changes, just remove empty lines)
> Add conversion of colored cables back to fluix

- config/LootGames/lootgames.cfg
according to @TimeConqueror, it's better if it's disabled.
> disabled lootgames donator list to speed up loading time

- scripts/Extra-Cells.zs
This is now obsolete given we have the ore dict card. This item is extremely laggy and unneeded.
> Remove Ore Dict Bus Recipe

- config/bartworks.cfg
Updated bartworks config with lost from dev version option and disabled shared itemstack tooltip
> Disable shared itemstack tooltip

- scripts/Advanced-Backpacks.zs
Since this is supposedly fixed by #7137 and #7299.
Should fix #8189.
> Removed Tooltips on Adv Backpacks

- .github/workflows/stale.yml
* Prevent crash reports from being closed
* Automatically close FixedInDev in case someone forgot
> Update stale bot configuration

- README.md
PR for #8361.
For every mod, I added the first one of these that I could find:
1. GTNewHorizons GitHub repo 
2. CurseForge page providing that exact version
3. Other official website providing that exact version
There were some mods I couldn't find, even some GTNH ones. Someone more knowledgeable than me can add them in later.
Also, I didn't touch the mod versions because checking that as well would've been too much work. I fixed some typos in mod names though.
I'll share the data and the scripts I used to generate this. I stored the modlists as CSVs where URLs can be easily added.
[gtnh_readme.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6946692/gtnh_readme.zip)
If you don't like the tabular format then I can easily change it back to the old bullet list one.
> Reformat mod list and add links

- .github/ISSUE_TEMPLATE/004-suggest-a-new-mod.yml
PS: I renamed the label itself to be more grammatically correct first too.
Also, there was no triage label, so those weren't being added, so I created that one too.
> Fix adding label

- config/SpecialMobs.cfg
Disables them until they can be reworked. Otherwise, they are complete bullshit that has no legitimate counter-play.
> Disables Witch of the Wind / Set Spawn Chance to 0

- scripts/Project_Red.zs
Should fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8568 and https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8559
Dream, you forgot to add the * 0 part. Also, why didn't you use oredict on the dyes, it's way less work?
> Fix recipes consuming circuits, and use oredict properly

- scripts/Avaritia-Addon.zs
using piece of paper, as the 9x9 Autocrafting table will store its recipe even when picked up.
> Add recipe to clear 9x9 Autocrafting table

- scripts/Thaumcraft-04-Artifice.zs
Changed Enderium to Enderium Base; from EV to late HV tier. Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8326
> Magic Mirror Adjustment

- .github/ISSUE_TEMPLATE/002-suggest-a-change.yml
- .github/ISSUE_TEMPLATE/003-request-new-feature.yml
Someone renamed `Type: suggestion` to `Type: Suggestion` and accidentally broke the issue templates. It does look better though, so let's keep it. This PR will fix the issue template.
> Fix issue template

- config/OpenComputers.cfg
If nobody against #8979 increased range to 6 blocks from 3
> Increased MFU range

- scripts/Railcraft.zs
It was removed from Railcraft and so not needed to be removed here (currently throws that message on 2.1.2.0)
> already removed in code

- config/adventurebackpack.cfg
As required to enable the tooltip fixed in https://github.com/GTNewHorizons/AdventureBackpack2/pull/4.
> Enabled adventure backpack tank tooltip

- config/cofh/core/common.cfg
We can have flat bedrock and it would be a nice QoL.
Retroactive flattening bedrock is not on because of the performance hit; that would better be done on a "once scan" perhaps.
> flat bedrock on new chunks

- scripts/Blood-Magic.zs
Adjusts the following:
Sanctus: Gold > Rose Gold
Incedium: Lava Bucket > Ignis Crystal Dust, Firestone Dust > Small Firestone
Virtus: Plutonium 239 > Fiery Steel Dust
Blank slate: 2000 > 1000
Reinforced slate: 4000 > 2500
Imbued slate: 10000 > 7500
Demonic slate: 20000 (unchanged)
Ethereal Slate: 50000 > 60000
Makes cutting the Slate variants not take a million years for the sake of it taking forever
These changes should drastically make early & mid game BM extremely less tedious
> Sanity Adjusting Some Recipes

- config/AWWayofTime.cfg
Incense sacrificing increased from 50 to 150 (this is a very oddball way of getting LP and is a "charged" means instead of spamming).
LP per sacrifice increased from 400 to 600.
WoS amount on "hit" per mob increased from 10 to 25. This apparently matches the later Minecraft versions of BM.
Self-sacrifice increased from 100 to 125.
Ritual of Feathered Knife increased from 100 to 125; it's basically automated & safe self-sacrificing for LP gain.
I also forgot to name the patch before accidentally hitting enter, whoops!
> (Self-)Sacrificing is less tedious overall

- scripts/Forbidden-Magic-01-Wands.zs
Redoes all the caps and wands derived from Botania:
- Make recipes look more like GT:NH style - to the extent those materials exist
- Put everything back in its appropriate tier
- Remove or replace the previous placeholder recipes that use exclusively non-botania ingredients.
P.S.: Don't merge this before Botania itself is actually added
> Botania + Forbidden Magic exploit fixes

- resources/minecraft/lang/en_US.lang
I couldn't find the MR with the corresponding code change for reference, but according to my in-game measurements and a few discussions on Discord, it seems the 13% output bonus on the multiblock sifter is not there anymore.
Therefore, it makes sense to remove its mention from the questbook.
> Remove mention of the MB sifter 13% output bonus, since it's not there anymore

- config/GTNewHorizons/CustomToolTips.xml
Sleeping height bug is patched by GT ++ in java/gtPlusPlus/plugin/fixes/vanilla/VanillaBedHeightFix.java since https://github.com/GTNewHorizons/GTplusplus/commit/e199da91c8b6614caca1f056fbaab8cae01df32b
> Removed obsolete sleeping bag sleep height warning

- config/MagicBees.cfg
- scripts/Magic-Bees.zs
Magic bees support part 2/2
- Enables magic bees' builtin botania integration
- Removes pristine bee drops from hiveacynth - its on par with the vanilla swarmer and far less expensive than gendustry and those can't do it either.
- Make hiveacynth require HV + soulful bee branch
- Make hibeescus require IV + multiple MB bee branches (this is the flower that turns ignobles into pristines).
Part 1 (required) is at https://github.com/GTNewHorizons/Botanic-horizons/pull/8
> Enable MagicBees + Botania integration

- config/Botania.cfg
Botania potions fix part 3/3 - see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9568
- Move the botania potion IDs to use empty slots.
Note: do not merge or test this without applying part 1 and 2 first, or things will break.
https://github.com/GTNewHorizons/Hodgepodge/pull/56
https://github.com/GTNewHorizons/Botania/pull/7
> De-conflicts the potion ids for botania. Requires mod support to work.

- config/endercore/endercore.cfg
There are two, though I don't know which mod adds the another one.
> Disable registry name tooltip from EnderCore

- scripts/Ender-IO.zs
These are incredibly basic machinery that is made around the same tier as you'd get at around LV-MV, though it so happened to apparently be gated at EV~
> Enderium > Dark Steel for Basic EiO Stuff

- config/enderio/EnderIO.cfg
The 128 limitation actually presents issues with larger bases
> Increase max distance between traversable anchors

- scripts/Logistics-Pipes.zs
- Changed LP recipes to not need HV machines or components, except for specific upgraded items such as high-tier Logistics Chassis, which still need HV and sometimes above.
Logistics Pipes is an automation mod that was added to GTNH some months ago, but it has seen very little use, especially as a main automation mod. This is because it requires HV to set up proper automation with it, and in the next tier, EV, the player gets access to the faster, less laggy and vastly superior AE2. As such, there's very little room to use this setup before it gets replaced by another.
To combat this, I've changed a lot of recipes, so that full automation can be set up in MV, in a similar fashion to ProjectRed, a very similar mod to Logistics Pipes. Some upgrades to important pipes are still locked to …
> Tiering Logistics Pipes to MV

- config/InGameInfo.xml
- Make formatting codes more verbose (e.g. `$0` -> `{black}`)
- Remove inconsistencies (remove double whitespaces, capitalize some letters)
> Make InGameInfo.xml more readable

- config/OpenComputers.cfg
finally adress https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8048: lua will by default be 5.2 but users will still be able to use 5.3 and newly crafted cpus will need to be changed to 5.3 manually, the same way it needs to be changed to 5.2 currently.
> make 5.2 the default lua version

- scripts/RemoteIO.zs
context: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10348
This is a feature that is already available in the RIO
https://github.com/GTNewHorizons/RemoteIO/blob/7d9df57c47f8832302ebeda9f9cd6630fd7f4e6f/src/main/java/remoteio/common/RemoteIO.java#L62-L63
```java
// Used for clearing location chips
GameRegistry.addShapelessRecipe(new ItemStack(ModItems.locationChip), new ItemStack(ModItems.locationChip));
```
> Add a shapeless recipe to clear RIO location chip

- scripts/ThaumicTinkerer-02-Kami.zs
Addresses https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10380. 
Locks Ichorium behind only Ichor, which I believe is the correct way it's supposed to be gated.
> Fix Ichorium research pre-reqs

- config/opencomputers/gtnh.recipes
[Server thread/WARN] [OpenComputers/OpenComputers]: No recipe for 'configuratorUpgrade', you will not be able to craft this item. To suppress this warning, disable the recipe (assign `false` to it).
[Server thread/WARN] [OpenComputers/OpenComputers]: No recipe for 'ritegUpgrade', you will not be able to craft this item. To suppress this warning, disable the recipe (assign `false` to it).
It also leads to a message being sent to the player after joining: "There were errors loading one or more recipes. Some items may be uncraftable. Please check your log file for more information."
> Add missing recipes to OC

- config/AdvancedSolarPanel_MTRecipes.cfg
Originally the MT had a 2x speed boost that was unintended. Even with this boost, the multi wasn't considered very good, but it got fixed since it was still unintended. This effectively brings back that speed boost as a buff.
Sunnarium will be changed separately.
> Halve all Molecular Transformer recipe times

- config/Galacticraft/core.conf
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10512.
Tested in a creative world by running /gckeeploaded on a space station that was previously affected by this bug then reloading the world, which kept the space station loaded.
> Enable static loading on new space stations

- scripts/Build-Craft.zs
- scripts/Ender-IO.zs
- scripts/Forestry.zs
- scripts/Project_Red.zs
(I wrote the https://gtnh.miraheze.org/wiki/Project_Red_Transportation_-_MV_Storage_and_Autocrafting article)
Project Red: Transportation is the earliest option for request crafting, but it's barely worth it.
The primary complaints I get from people after setting up PRT are:
1. This costs way too many circuits / is generally cost prohibitive for the value I get
2. Help, I used active chips (which you said not to use) and now I'm confused / it's buggy (this needs logic patches and questline adjustment, which will be done later)
3. Not having auto crafting table options is pain
4. Because of idiosyncracies with how item distribution works, you cannot reuse machines during a multi-step crafting procedure. This leads to additional logistics costs that may not be obvious if you haven't built a …
> Project Red: Transportation Buffs

- scripts/Galacticraft.zs
removed MT script for removing fluid manipulator recipe in order for the new YOTTANK recipes to work
Yottank PR: https://github.com/GTNewHorizons/GoodGenerator/pull/61
New Recipe:
> Removing MT Script

- scripts/Gendustry.zs
instead of requiring the advanced mutatron in the recipe FOR the advanced mutatron, I switched it to an integrated casing. Oops-
+ mutagen producer:
> Fixed advanced Mutatron recipe

- config/GTNewHorizons/dreamcraft.cfg
- scripts/Gendustry.zs
- scripts/Genetics.zs
- scripts/Gregtech.zs
Blacklisted from World Accelerator
Moved down to LV
New Recipes:
Industrial Apiary:
Automation upgrade:
Integrated Circuit:
Upgrade Frame:
> Modifying Industrial Apiary

- config/GTNewHorizons/dreamcraft.cfg
Blacklist Gendustry Industrial Apiary from acceleration to force people to use the new version
Also why there was **gregtech** apiary ? Removed it.
> Blacklist Gendustry Industrial Apiary from acceleration

- config/GalaxySpace/core.conf
Despite what the config says, reflecting the fireballs back at these bosses does basically no damage. With the current damage limit of 3, these bosses end up being 5+ minutes of left click spam, which is very tedious.
Increasing the damage maximum to 100 makes them less of a useless time sink.
> Greatly reduce damage reduction on GS bosses

- scripts/Galacticraft.zs
The Galacticraft cannister doesn't behave well with ae2, thus I changed it to a normal ic2 empty cell.
> Modify Fluid Manipulator

- scripts/Extra-Utilities.zs
Just added the other EV circuits as options. That is already how it works for the other pipes.
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10844
> add circuit alternatives for hyperrationing pipe

- config/GTNewHorizons/dreamcraft.cfg
Its a power generation option. Those are usually blacklisted.
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10558
> Blacklist GG Essentia Hatch

- scripts/Biome-o-Plenty.zs
Adds an additional recipe for glow coral that uses gt++ algae instead of bop.
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10422.
> Add alternative algae recipe for glow coral

- config/gendustry/overrides/tuning.cfg
Blacklisted infinity, infinity catalyst and cosmic neutronium from mutatron (didn't work prior) also changed it to REQUIREMENTS instead of DISABLED since their combs will be used as a catalyst in DTPF recipes and not for primarly centrifuging recipes anymore.
> Updated Infinity Line

- scripts/CoreMod.zs
Because
https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/393
has been merged, shaped Wooden Form recipe is no longer required
> Remove shaped Wooden Form recipe

- config/GregTech/Client.cfg
turns out input filter default behavior is controlled by a config, so i updated it to reflect the change we wanted to do in code
(see https://github.com/GTNewHorizons/GT5-Unofficial/pull/1167)
> input filter default off

- config/gendustry/overrides/tuning.cfg
Add Americium and Indium bee to blacklist. 
Modified Infinity bees to be disabled from mutatron, which means that they have to be bred by hand now.
> Mutatron update

- scripts/Logistics-Pipes.zs
because apparently people still complain about this being too expensive
also added another tier for the Unrouted Logistics Pipe. Mass boro glass usage just doesn't belong to a tier before LuV. unrouted pipe is even worse than tin item pipe so this seems pretty justified.
> decrease LP item price by 33% to 50%

- scripts/Gregtech.zs
Tiered solars are more reasonable to craft, for example for uv solars requiring 6 uiv circuits as well as 2 of the previous tier is quite excessive so it was changed to be craftable in tier+2. Also the change from iv->luv solars becoming vastly more expensive with them requiring more circuits, the circuits being tier+3 rather than tier+2, and requiring 2 of the previous tier over 1. While these solars still won't compete with fusion spam (as it should be) they aren't completely irrelevant either and actually have a niche.
> Cheaper tiered solars

- scripts/Draconic-Evolution.zs
Retiered the staff of power and the advanced dislocator back to uhv, as they were affected by the chaotic core nerf and got moved to umv
> Fix chaotic nerf

- config/defaultserverlist.json
- servers.json
Remember:
- Entries in a list must be separated by commas
- `servers.json` is the master list, not `config/defaultserverlist.json`
(@superhealing @Dream-Master )
> Fix #11851

- scripts/Project_Red.zs
Fix oversight in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/10802:
- Fix circuit tier
- Diamond plate -> aluminium plate for stock keeper
- Diamond plate -> aluminium rod for routed junction pipe
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11769
> Fix recipe inconsistency with ProjectRed

- config/GTNewHorizons/dreamcraft.cfg
Let's remove normal apiary from WA blacklist. If early game the player wants to pay EUs in exchange of extra speed, that is fine, especially for breeding purposes (rip the player if he does it on a radioactive bee). If player wants to abuse it for production, there are way better solutions than this, so if he wants to shoot a bullet in the foot, that's up to them.
> remove normal apiary from WA blacklist

- scripts/Forestry.zs
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12032
> Fix amount of redstone to craft Thermionic Fabricator not divisible by 144mB

- scripts/Warp-Theory.zs
Changed **<IC2:itemFluidCell>.withTag({Fluid: {FluidName: "lifeessence", Amount: 1000}})** to **<gregtech:gt.metaitem.01:30694>**; using the GT cell version of life essence instead of IC2. fixes the issue some people were having with the infusion not starting. Because you can only fill GT cells up to 1000mB this should be the same portions in the recipe as before
-unsure problems: unsure if initial method returned empty IC2 cell or not; including this here to make it known and to point it out if it did or not
> Update Warp-Theory.zs impure tear infusion not starting

- scripts/Blood-Magic-Thaumcraft.zs
these are ignored because of line breaks
> complement i18n

- scripts/Logistics-Pipes.zs
Should only be accepted when [this](https://github.com/GTNewHorizons/LogisticsPipes/pull/14) pull request is merged.
Adds the craft for GT Type Filter ItemSink module.
Crafting way:
The same for tin & soldering alloy.
> Add GT Type Filter ItemSink module craft

- config/EnhancedLootBags/LootBags.xml
Silver chest is not a thing, so loot is broken for lv and mv bags. This causes it to drop 1 item instead of 2 sometimes and render glitches for creative loot preview
> fix lv and mv lootbags ironchests table (silver -> steel)

- config/NEI/client.cfg
the players don't need to see non-sense numbers appened at the end of item tooltips
> change item IDs from shown to hidden

- scripts/AE2.zs
- scripts/Adv-Solar-Panel.zs
- scripts/Automagy.zs
- scripts/Blood-Magic-Thaumcraft.zs
- scripts/CoreMod.zs
- scripts/Emt.zs
- scripts/Ender-IO.zs
- scripts/Extra-Bees.zs
- scripts/Extra-Utilities.zs
- scripts/Forbidden-Magic-01-Wands.zs
- scripts/Forestry-Frames.zs
- scripts/Forestry.zs
- scripts/GraviSuite.zs
- scripts/Gregtech.zs
- scripts/Magic-Bees.zs
- scripts/Minecraft.zs
- scripts/Open-Blocks.zs
- scripts/Railcraft.zs
- scripts/Renaming.zs
- scripts/Tainted-Magic-1.zs
- scripts/Thaumcraft-01-Basic.zs
- scripts/Thaumcraft-03-Alchemy.zs
- scripts/Thaumic-Bases-01-Main.zs
- scripts/Thaumic-Exploration-01.zs
- scripts/ThaumicTinkerer-01.zs
- scripts/ThaumicTinkerer-02-Kami.zs
- scripts/Tinkers-Construct.zs
- scripts/Warp-Theory.zs
- scripts/Witchery.zs
- scripts/ZZ-Client-Only.zs
defined a variable `_I18N_Lang` with a value of `"en_US"` to facilitate the replacement of its value with other values such as `"zh_CN"` during the automation process
only extracted the variable, without increasing the complexity of scripts.
> Update zen scripts for improved automation of I18N

- config/Thaumcraft.cfg
Solves #12390
Normal GUI Size:
Extra Large GUI Size:
Works for me at least.
> Move Wand display to bottom left instead

- scripts/Extra-Utilities.zs
For Builders Wands.
Otherwise only the Random Things Obsidian Rod work in this recipe.
This should reduce the amount of Unstable explosions happening.
> Oredict Obsidian Stick

- config/InGameInfo.xml
Space after the word was also underlined.
> Fix ore chunk text formatting

- scripts/Tinkers-Construct.zs
Fixes #9484.
Removes this recipe:
I can't figure out how to build the modpack to test yet, but it should work fine.
> Remove Tinkers channel->nether brick faucet recipe

- config/TooMuchLoot/loot/chest1.xml
- config/TooMuchLoot/loot/chest2.xml
- config/TooMuchLoot/loot/chest3.xml
- config/TooMuchLoot/loot/chest4.xml
As discussed here and in the following pages on discord: https://discord.com/channels/181078474394566657/939305179524792340/1090192484115681320
This a rebalance of the loot obtained in game of light. (chest1/chest2/chest3/chest4) There was general consensus in the meta-dev channel that this is needed. (see more about the reasoning there)
General goals of the rebalance:
- reduce the overall power of lootgames in early game somewhat while still keeping things rewarding.
- reduce the tierskipping potential from rewards.
- broaden the rewards to non-tech parts of the early game
- clean up the files a bit . (duplicates and things that get autoconverted.)
How to achieve these goals:
- no more rewards that require HV+ technology.
- only limitted amounts that would need MV technology.
- addition …
> Lootgames rebalance

- scripts/Draconic-Evolution.zs
zs not applicable /* */ comment，After using the overload instruction, two additional // will be automatically added, and restarting will also.
> zs not applicable /* */ comment

- servers.json
I believe it should be `mineyourmind`, but it is `mineyourmine`.
> Typo Fix (mineyourmine > mineyourmind)

- config/GregTech/WorldGeneration.cfg
Depends on https://github.com/GTNewHorizons/GT5-Unofficial/pull/1906 and https://github.com/GTNewHorizons/amunra/pull/4
Based on a modified version of the oregen spreadsheet: [GTNewHorizons.ods](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11304816/GTNewHorizons.ods)
*Note: Not all T9 dimensions have a "full" (~12 veins) set of oreveins yet, partly because of a lack of creativity on my end, partly because I don't know enough about the late game to know what would be beneficial. Any Feedback is appreciatet.*
> Enable T9 Oregen

- .github/workflows/stale.yml
`close-issue-reason` is not included in v3. https://github.com/actions/stale/commit/06d2a3904b77e3b34b74319855eebe4627488d19
Also it's set to `not_planned` by default. https://github.com/actions/stale/commit/02e44c81cc3144e8817a5686f3d7c24658f6f1e6
> Update actions/stale to v8

- config/betterquesting/DefaultQuests/Quests/Tier05Steam-AAAAAAAAAAAAAAAAAAAAAg==/UpgradeABetterCo-AAAAAAAAAAAAAAAAAAAANw==.json
- config/betterquesting/DefaultQuests/Quests/Tier05Steam-AAAAAAAAAAAAAAAAAAAAAg==/UpgradeBetterFur-AAAAAAAAAAAAAAAAAAAAQA==.json
- config/betterquesting/DefaultQuests/Quests/Tier05Steam-AAAAAAAAAAAAAAAAAAAAAg==/UpgradeBetterMac-AAAAAAAAAAAAAAAAAAAAOg==.json
- config/betterquesting/DefaultQuests/Quests/Tier05Steam-AAAAAAAAAAAAAAAAAAAAAg==/UpgradeExtractor-AAAAAAAAAAAAAAAAAAAAOQ==.json
- config/betterquesting/DefaultQuests/Quests/Tier05Steam-AAAAAAAAAAAAAAAAAAAAAg==/UpgradeForgeHamm-AAAAAAAAAAAAAAAAAAAAOA==.json
- config/betterquesting/DefaultQuests/Quests/Tier05Steam-AAAAAAAAAAAAAAAAAAAAAg==/UpgradeHighSpeed-AAAAAAAAAAAAAAAAAAAALw==.json
Clarify that high pressure variants spend the same total amount of steam when doing the job twice as fast. 
The test to verify that was done on GTNH 2.3.0 with High Pressure Compressor.
> Update quests about High Pressure steam machines

- config/betterquesting/DefaultQuests/Quests/Tier05Steam-AAAAAAAAAAAAAAAAAAAAAg==/RubberSheets-AAAAAAAAAAAAAAAAAAACGA==.json
Rephrase the Rubber Sheets quest to mention Piston Boots.
Also clarify the main usage of Rubber Sheets at this stage.
Remove the mention of other things that are crafted not as often.
> docs(quest): Rubber Sheets: mention Piston Boots

- config/betterquesting/DefaultQuests/Quests/Tier05Steam-AAAAAAAAAAAAAAAAAAAAAg==/RubberSheets-AAAAAAAAAAAAAAAAAAACGA==.json
* Update the reference to the Getting Around questline because it was split in two.
* Simplify wording.
> docs(quest): RubberSheets: update and reword

- config/betterquesting/DefaultQuests/Quests/Tier05Steam-AAAAAAAAAAAAAAAAAAAAAg==/CuttingaTreelogb-AAAAAAAAAAAAAAAAAAAC5w==.json
* Decolor orange because it's not a good match with the default background color.
* Decolor dark_aqua because it's just another tip.
* Explain how to make netherrack parts because they are not shown in NEI.
* Move the parts about upgraded materials and quest detection closer together to the end.
> docs(quest): CuttingaTreelogb: improve wording and formatting

- config/betterquesting/Readme.md
Explaining lines 90-91:
Swap and reword the items 6 and 7 to change the intention from 
"a quest can be in multiple tabs but only if necessary" 
to
"a quest really should be in one tab, but can be in many if really necessary"
The rest is minor rewording and typo fixes.
> docs(quests): BetterQuesting Readme: fix typos and improve wording

- config/betterquesting/DefaultQuests/Quests/FishingFarmingCo-AAAAAAAAAAAAAAAAAAAACg==/JustLikeMomUsedt-AAAAAAAAAAAAAAAAAAAHPg==.json
Mentioning only Forestry Worktable as a way to store food recipes is questionable because the kitchen multiblock is overwhelmingly better for food in this regard.
> Quest: JustLikeMomUsedt: mention kitchen multiblock

- config/betterquesting/DefaultQuests/Quests/Tier1LV-AAAAAAAAAAAAAAAAAAAAAw==/Glue-AAAAAAAAAAAAAAAAAAAC6Q==.json
The quest mentions refined glue as an option to make Good Circuits. The usual glue can also be used to make Good Circuits.
What is more, manually farming glue from Slimy Trees is faster and easier than manually farming Sticky Resin from Rubber Trees.
If I understood the quest intention correctly, it is made to prepare a player for the creation of Good Circuits. If this is so, overlooking glue farming from Slimy Trees is an unaffordable luxury.
Therefore, I added glue as an option:
* Make Requirements disjunctive (OR) and add Fluid Extractor as a requirement that is visible on hover.
* Add Congealed Green Slime as an Optional Retrieval. The number to retrieve is 11 to give 6kL Glue, which is equivalent to 3kL Refined Glue if using Distillery.
11 Congealed > (Extractor) 44 Smlimeballs > …
> Quest: Glue: add glue option

- config/GalaxySpace/core.conf
Based on these calculations:
Distances are taken from [here](https://github.com/GTNewHorizons/amunra/blob/master/src/main/java/de/katzenpapst/amunra/AmunRa.java#L513-L618) (second to last parameter of `createPlanet` is distance in AU, moons use ther parent planet's distance to the sun).
> Configure T9 Power Factors for Dyson Swarm

- config/betterquesting.cfg
Not sure when or why this happened, but the current default (as of [this nightly](https://discord.com/channels/181078474394566657/522098956491030558/1106543995896737823)) appears to be an invalid value, resulting in BQ using some weird messed up default theme.
In particular, this was reported to be causing scrollbars to render oddly, becoming very difficult to see when hovered over.
> Fix BQ default theme

- config/betterquesting/DefaultQuests/Quests/SpaceRace-AAAAAAAAAAAAAAAAAAAAIg==/FastFancyStripes-zLE6OyCFT8ih5eSJVainBQ==.json
The Ion Thruster actually has less capacity than the Rocket Engine (see [`TileEntityMothershipEngineIon#getTankCapacity`](https://github.com/GTNewHorizons/amunra/blob/master/src/main/java/de/katzenpapst/amunra/tile/TileEntityMothershipEngineIon.java#L137)).
> Update "Fast Fancy Stripes" Quest

- config/betterquesting/DefaultQuests/Quests/MultiblockGoals-AAAAAAAAAAAAAAAAAAAADA==/YouAreNotPrepare-AAAAAAAAAAAAAAAAAAALqQ==.json
This replaces “The villager are too dumb that they spent...”, which does not make sense in English, with “The villagers are so dumb that they spent...” in the “You Are Not Prepared... But They Are” quest.
> Fix incorrect wording for smeltery quest

- config/InGameInfo.xml
depends on https://github.com/GTNewHorizons/InGame-Info-XML/pull/18 and thus also https://github.com/GTNewHorizons/GT5-Unofficial/pull/2081.
use the new info about the gt oregen pattern to show correctly when the player is in a ore vein chunk.
> Adjust igi xml to new oregen pattern

- config/Waila.cfg
I think this information is useless in 99.9% of cases but it still takes space and distracts from really important stuff.
<details><summary>Before/After</summary>
</details>
To Enable it back:
[Waila] Config screen (NUMPAD0 by default) -> Modules -> Wawla-General -> Set "Show Block Hardness?" and "Show Blast Resistance?" to Yes.
> Hide Hardness and Blast Resistance values in Waila

- config/betterquesting/DefaultQuests/Quests/PowerfulNuclearP-AAAAAAAAAAAAAAAAAAAAGg==/Plutonium239-AAAAAAAAAAAAAAAAAAAMZA==.json
Follow up to https://github.com/GTNewHorizons/GTplusplus/pull/698 that changes the plutonium quest icon to the gt variant.
> Fix plutonium icon

- config/betterquesting/DefaultQuests/Quests/NoviceThaumaturg-AAAAAAAAAAAAAAAAAAAAFg==/LeadGalenaSilver-AAAAAAAAAAAAAAAAAAACYg==.json
- config/betterquesting/DefaultQuests/Quests/NoviceThaumaturg-AAAAAAAAAAAAAAAAAAAAFg==/SourceofNickel-AAAAAAAAAAAAAAAAAAAGTQ==.json
- config/betterquesting/DefaultQuests/Quests/Tier05Steam-AAAAAAAAAAAAAAAAAAAAAg==/Gypsum-AAAAAAAAAAAAAAAAAAADZA==.json
- config/betterquesting/DefaultQuests/Quests/Tier05Steam-AAAAAAAAAAAAAAAAAAAAAg==/HowtoMakeRubber-AAAAAAAAAAAAAAAAAAAB8A==.json
- config/betterquesting/DefaultQuests/Quests/Tier05Steam-AAAAAAAAAAAAAAAAAAAAAg==/LapisLazuriteSod-AAAAAAAAAAAAAAAAAAADYw==.json
- config/betterquesting/DefaultQuests/Quests/Tier05Steam-AAAAAAAAAAAAAAAAAAAAAg==/OooShinyNotPlati-AAAAAAAAAAAAAAAAAAAB7w==.json
- config/betterquesting/DefaultQuests/Quests/Tier0StoneAge-AAAAAAAAAAAAAAAAAAAAAQ==/CopperOre-AAAAAAAAAAAAAAAAAAADOQ==.json
- config/betterquesting/DefaultQuests/Quests/Tier0StoneAge-AAAAAAAAAAAAAAAAAAAAAQ==/IronOre-AAAAAAAAAAAAAAAAAAADOg==.json
- config/betterquesting/DefaultQuests/Quests/Tier0StoneAge-AAAAAAAAAAAAAAAAAAAAAQ==/Malachite-AAAAAAAAAAAAAAAAAAAB4A==.json
- config/betterquesting/DefaultQuests/Quests/Tier0StoneAge-AAAAAAAAAAAAAAAAAAAAAQ==/Redstone-AAAAAAAAAAAAAAAAAAAB7g==.json
- config/betterquesting/DefaultQuests/Quests/Tier1LV-AAAAAAAAAAAAAAAAAAAAAw==/HowtoGetSodium-AAAAAAAAAAAAAAAAAAACbQ==.json
- config/betterquesting/DefaultQuests/Quests/Tier1LV-AAAAAAAAAAAAAAAAAAAAAw==/MicaOre-AAAAAAAAAAAAAAAAAAALpw==.json
- config/betterquesting/DefaultQuests/Quests/Tier1LV-AAAAAAAAAAAAAAAAAAAAAw==/OilsandorHowYouG-AAAAAAAAAAAAAAAAAAAG_w==.json
- config/betterquesting/DefaultQuests/Quests/Tier1LV-AAAAAAAAAAAAAAAAAAAAAw==/QuartziteVeins-AAAAAAAAAAAAAAAAAAAEjg==.json
- config/betterquesting/DefaultQuests/Quests/Tier1LV-AAAAAAAAAAAAAAAAAAAAAw==/TetrahedriteStib-AAAAAAAAAAAAAAAAAAACVQ==.json
- config/betterquesting/DefaultQuests/Quests/Tier3HV-AAAAAAAAAAAAAAAAAAAABQ==/FindBastnasiteMo-AAAAAAAAAAAAAAAAAAAGTA==.json
- config/betterquesting/DefaultQuests/Quests/Tier3HV-AAAAAAAAAAAAAAAAAAAABQ==/FindBauxite-AAAAAAAAAAAAAAAAAAAD8w==.json
- config/betterquesting/DefaultQuests/Quests/Tier3HV-AAAAAAAAAAAAAAAAAAAABQ==/FindIlmenite-AAAAAAAAAAAAAAAAAAAFkA==.json
- config/betterquesting/DefaultQuests/Quests/Tier4EV-AAAAAAAAAAAAAAAAAAAABg==/PureUraniumOres-AAAAAAAAAAAAAAAAAAAFhw==.json
- config/betterquesting/DefaultQuests/Quests/Tier4EV-AAAAAAAAAAAAAAAAAAAABg==/ReactorFuels-AAAAAAAAAAAAAAAAAAAE2w==.json
Makes all ore quests that I found pretty much the same:
Main x32
Secondary x32
Between x32
Sporadic x16
Pictures:
Quests that are not strictly about one vein remain unchanged, e.g. iron quest:
> Ore quest consistency

- config/hodgepodge.cfg
doesn't change something, but should be turned off for a proper release.
> turn off render debug

- config/EnhancedLootBags/LootBags.xml
was giving the old (and unusable) dreamcraft one instead of thaumcraft.
> Fix wand cap in lootbag

- config/enderio/SAGMillRecipes_User.xml
deletes string as secondary output
> fix wool recipe

- config/betterquesting/DefaultQuests/Quests/Tier5IV-AAAAAAAAAAAAAAAAAAAABw==/PotassiumNitrate-AAAAAAAAAAAAAAAAAAAGpw==.json
Allows player to skip potassium nitrate with saltpeter (which is also accepted in dichromate recipe)
> skip potassium nitrate with saltpeter

- config/GTNewHorizons/CustomToolTips.xml
- config/gendustry/overrides/tuning.cfg
See [here](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14245).  This PR makes the Drake bee mutatron blacklisted, so that players must get the awakened draconium coil to breed it as intended.  Even for no space / skyblock players this is still possible via breeding late planet bees that take way more breeding and have a much slower production of awakened draconium.
Also adds tooltips to ALL speed, territory, lifespan, and effect gene samples from gendustry.  This provides valuable in game information about annoying to remember bee data.
Also adds tooltips to the apiary, magic apiary, alveary, and bee house explaining the bee formula.
> Mutatron blacklist Drake bee, improve gene sample tooltips

- config/GalaxySpace/core.conf
With the Dyson formula fixed, revisiting the consumption is in order, especially as the old balancing was done with an incorrect script (It had module count and consumption swapped).
"Current" values with existing coefficients and a fixed consumption function, although the consumption has always been at a static 1 module per hour due to a bug in the formula.
Increasing computation is fairly inconsequential, and the module consumption still makes the Dyson spammable even without computation.
Module consumption with new values:
Adding computation becomes almost mandatory, with each quantum computer (at 25k computation/s) reducing the module consumption by roughly 30% (additive). The computation is capped at 100 000/s to still keep a minimum running cost of 64 modules per hour (One …
> Increase Dyson module consumption, especially without computation

- config/betterquesting/DefaultQuests/Quests/GT-AAAAAAAAAAAAAAAAAAAAEQ==/AMERICA-Qrjs7uh5TcSveEbaFnXFog==.json
- config/betterquesting/DefaultQuests/Quests/GT-AAAAAAAAAAAAAAAAAAAAEQ==/BoronicFusion-Tfb8JzstRNuiSV6CKgTNRQ==.json
- config/betterquesting/DefaultQuests/Quests/GT-AAAAAAAAAAAAAAAAAAAAEQ==/CalciumBottlenec-9j1Iwd3KRG6jqLI9m6YDKQ==.json
- config/betterquesting/DefaultQuests/Quests/GT-AAAAAAAAAAAAAAAAAAAAEQ==/MarieCurium-3r7tJ7_bTuePzsh-B_jyIQ==.json
- config/betterquesting/DefaultQuests/Quests/GT-AAAAAAAAAAAAAAAAAAAAEQ==/Niobiumization-X_rOgp6GRKiyGzwRV_p7GA==.json
- config/betterquesting/DefaultQuests/Quests/GT-AAAAAAAAAAAAAAAAAAAAEQ==/Zzzincing-Ng5Ldnf3TZCefB4Mr3u-rQ==.json
These icons were broken by Colens recent gt++ 'clean-up'. Even worse, BQ didnt handle it gracefully with placeholder items but spammed errors on the questline page and crashed when clicking the quest. This PR cleans that up by replacing those icons.
> Fix QB crashing and spamming errors

- config/RTG/biomes/abyssalcraft.cfg
- config/RTG/biomes/arsmagica.cfg
- config/RTG/biomes/atg.cfg
- config/RTG/biomes/biomesoplenty.cfg
- config/RTG/biomes/buildcraft.cfg
- config/RTG/biomes/chromaticraft.cfg
- config/RTG/biomes/enhancedbiomes.cfg
- config/RTG/biomes/extrabiomes.cfg
- config/RTG/biomes/flowercraft.cfg
- config/RTG/biomes/forgottennature.cfg
- config/RTG/biomes/growthcraft.cfg
- config/RTG/biomes/highlands.cfg
- config/RTG/biomes/icecreammod.cfg
- config/RTG/biomes/industrialtechnologies.cfg
- config/RTG/biomes/ridiculousworld.cfg
- config/RTG/biomes/thaumcraft.cfg
- config/RTG/biomes/tofucraft.cfg
- config/RTG/biomes/vampirism.cfg
- config/RTG/biomes/vanilla.cfg
- config/RTG/rtg.cfg
The Minecraft Fandom wiki has been forked to a new domain: minecraft.wiki. Learn more here: https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom. This PR updates all URLs accordingly.
> Update Minecraft Wiki links to new domain

- config/craftpresence.json
Unbind the craft presence config keybind by default.
Actually a pretty important fix so that new players can access the quest book without issues.
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14006
> Unbind craft presence key by default

- config/GregTech/GregTech.cfg
To make spotting recipe error easier. I can load the pack without issue.
> Enable crashOnNullRecipeInput

- config/harvestcraft.cfg
Adds new entries from https://github.com/GTNewHorizons/harvestcraft/pull/48. 
`enablemachinerecipes` is set to false as requested.
New content is disabled for until it is properly integrated.
**Not to be merged until the associated PR is merged.**
> Harvestcraft Config Update - Grinder

- config/forestry/backpacks.cfg
Closes: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7022
Natura:barleyFood:7 is flamestring
RandomThings:ingredient:3 is ectoplasm
witchery:ingredient:24 is wool of bat
others are self-explanatory.
> Add more missing "hunter's drops" to forestry backpack

- config/amazingtrophies/achievements/unbreakable_tconstruct_tool.json
Depends on https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/776.
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/15070.
The condition would only be met, if a TiCon Hammer is picked up.
> Remove Condition from `unbreakable_tconstruct_tool` Achievement

- config/betterquesting/DefaultQuests/Quests/AppliedEnergisti-AAAAAAAAAAAAAAAAAAAAIw==/AppliedGreg-AAAAAAAAAAAAAAAAAAALPQ==.json
Changed the requirement for Advanced Stocking Input Bus (ME) to Stocking Input Bus (ME) in the "Applied Greg?" quest to fix #15154 
Before change
After change
> Changed "Applied Greg?" quest to better match other requirements

- config/betterquesting/DefaultQuests/Quests/KaaamiHaaaamiHA-AAAAAAAAAAAAAAAAAAAAGA==/TheseItemsWillNo-AAAAAAAAAAAAAAAAAAALRw==.json
Updated the "These Items Will Not 'Be Back'" to require 8 Advanced Alchemical Constructs instead of 
4 to fix #15099
Before change
After change
> Change "These Items Will Not 'Be Back'" to better match items needed

- config/IguanaTinkerTweaks/BlockOverride.cfg
Found a unused iguana config that can be used to override harvest levels for ARR mods. (from what I can tell the 'blockdefault' config is just a datadump that hasnt been regenerated in years and not a real config, but 'blockoverride' does indeed do what it says.)
Fixes https://github.com/GTNewHorizons/Dupes-Exploits-GTNH/issues/111 (hopefully these were the last ones).
> Override xutils obsidian harvest levels

- config/NEI/client.cfg
Causes a double transfer with mouse tweaks transfer (which is better imo cause inventory position awareness)
> Disable NEI's mouse wheel transfer

- config/GraviSuite.cfg
Adds the 3 new Quantum tier of Thaumic Boots as valid boots for use with GraviSuite's Quantum Shield
> Add  Thaumic Boots to Gravisuite Config

- config/betterquesting/DefaultQuests/Quests/AppliedEnergisti-AAAAAAAAAAAAAAAAAAAAIw==/ToolsoftheTrade-AAAAAAAAAAAAAAAAAAAJ6Q==.json
Fix a second prereq loop caused by https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/15112
First was fixed in [december.](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/15171)
hope thats all now :(
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15494
> Fix second AE2 quest prereq loop

- serverutilities/server/ranks.txt
- serverutilities/serverutilities.cfg
- turn on dump_permission for some documentation
- add a basic ranks file. This makes it easier for people to configure their game! (ranks/chunkloading/claims/homes are still off in the config. but now its easy to change)
- turn on explosions
The goal here is to make it much easier to give instructions on how to use SU for chunkloading in SP or a local server without adding other cheats: 'turn on claims, chunkloading, and ranks in the config'. While at the same time also making it clearer how to enable and configure homes (for the teleport cheaters :P). And all that without changing the current defaults as claims/chunkloading/ranks/home is all off.
> Improve server utils config

- config/betterquesting/DefaultQuests/Quests/Tier3HV-AAAAAAAAAAAAAAAAAAAABQ==/Rutile-AAAAAAAAAAAAAAAAAAAD9A==.json
Removes magnesium chloride requirement to complete the quest so that players who loop it won't have to gather it
> Remove magnesium chloride as a required item

- config/BloodMagic/meteors/RainbowGlassMeteor.json
- config/BloodMagic/meteors/SuperGTStones.json
- config/BloodMagic/meteors/T1RocketStones.json
- config/BloodMagic/meteors/T2RocketStones.json
- config/BloodMagic/meteors/T3RocketStones.json
- config/BloodMagic/meteors/T4RocketStones.json
- config/BloodMagic/meteors/T5RocketStones.json
- config/BloodMagic/meteors/T6RocketStones.json
- config/BloodMagic/meteors/T7RocketStones.json
- config/BloodMagic/meteors/T8RocketStones.json
The main purpose of this PR is to add all the different blocks that generate on the various planets to the respective meteors (Blood Magic Mark of the Falling Tower ritual). This closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15711. See https://github.com/GTNewHorizons/BloodMagic/pull/50 for explanation of the new format; this PR is also necessary for this change to work (older versions of BM *will crash* with this config).
Along the way I implemented two minor fixes:
* The meteor which spawns various granite blocks now always spawns the GT variants, not assorted variants from other random mods based on whichever is first in the oredict. The different variants can still be converted to each other using a chisel if one wants a different type (this is pre-existing). …
> Add various planet blocks to meteors.

- config/WitchingGadgets.cfg
Add missing advanced materials to blacklist. Fixes https://discord.com/channels/181078474394566657/939305179524792340/1223927938320302110
> Fix the advanced metal blacklist for WG

- config/InGameInfoXML/InGameInfo.xml
Noticed that the default config doesn't have a functioning slime chunk HUD even though it is included. So I replaced it with one that worked (tested personally) that fit with the "This is an ore chunk." and "This is the center of the chunk." formats.
> Update InGameInfo.xml - Fix Slime Chunk Designation

- config/betterquesting/DefaultQuests/Quests/GT-AAAAAAAAAAAAAAAAAAAAEQ==/ToomuchIndium-AAAAAAAAAAAAAAAAAAAMSA==.json
- config/betterquesting/DefaultQuests/Quests/GT-AAAAAAAAAAAAAAAAAAAAEQ==/WhatEvenisThis-AAAAAAAAAAAAAAAAAAAKyA==.json
GTNewHorizons/GTPlusPlus#873 downtiered the multiblock dehydrator from ZPM to LuV. This PR updates the questbook to reflect these changes.
- Requirement is changed from ZPM hull quest to LuV hull quest
- Reward for dehydrator quest changed from ZPM loot bag to LuV loot bag
- Text updated to reflect changes.
> Fix quests for multiblock dehydrator downtiering

- config/NEI/heighthackhandlers.cfg
Fixes:
* https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16020
I tested this and it seemed to work fine on 2.5.1
> Add Railcraft NEI handlers to height hack

- config/DraconicEvolution.cfg
Using the new DE config option, disable ore spawning outside of the end - this fixes draconium spawning in personal dimensions.
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12919
> Whitelist non-GT draconium ore dimensions to End only

- config/NEIAddons.cfg
Everything this does is already handled by NEE and currently causes https://github.com/GTNewHorizons/NotEnoughEnergistics/pull/39 not to work in base AE2 terminals.
> Turn off NEIAddons AE2 integration

- config/MouseTweaks.cfg
- config/NEI/client.cfg
readds the mousetweaks config in the new format with the LMBTweakWithItem setting it had in 2.5.0. I am not gonna touch wheeltweaks here after all that is a bigger can of worms including defaultconfig mod considerations.
specifically:
- this disables LMBTweakWithItem again. which is a buggy thing we always had disabled. This fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16126
> Readd mousetweaks config and fix incorrect stack splitting

- config/localconfig.txt
May or may not have been responsible for the autotransition to the new MouseTweaks config format not working in some cases.
`LMBTweakWithItem` is excluded.
> Update MouseTweaks entry to match new config format

- .github/workflows/issue-helper.yml
See more at [GTNewHorizons/GTNHIssueHelper](https://github.com/GTNewHorizons/GTNHIssueHelper)
Examples of the bot response can be found [here](https://github.com/Glease/GT-New-Horizons-Modpack/issues). You are free to post some crash reports there to test the bot. Be sure to use "Report Crash" template though.
> Add an extremely primitive issue bot to help diagnose crash reports

- config/InGameInfoXML/InGameInfo.xml
Improves the weather information to be accurate based on localtemperature (which is how weather *actually* works, that being a .15 temperature threshold which is dynamic based on y level) instead of the previous raining/snowing/thundering variables. Also shares the remaining length of the current storm / time until the next storm.
The big series of biomes are me trying to catch every biome which does not have any precipitation, as uh, there is no easy way to add that without including every case (and there are less no precipitation biomes than there are precipitation biomes).
Examples:
As for moon phases, this is a modification from what was grabbed in this page here: https://gtnh.miraheze.org/wiki/InGame_Info_XML
Instead of color coding based on Day/Night cycle on the moon, it's color …
> Update InGameInfo.xml - Weather & Moon Phases, Improving Slime Chunk Commit

- config/forestry/backpacks.cfg
After having to copy my local Forestry backpack config changes when updating from 2.5.x -> 2.6.0 and once again from 2.6.0 -> 2.6.1 I've decided to open a PR to improve the Hunter's Backpack for everyone.
This PR adds to the config the items I noticed were not picked by the Hunter's Backpack.
I also included some additional boss drops the full Twilight Forest progression I have yet to obtain, so those are untested.
> Update hunter backpack contents

- config/betterquesting/DefaultQuests/Quests/AppliedEnergisti-AAAAAAAAAAAAAAAAAAAAIw==/AppliedGreg-AAAAAAAAAAAAAAAAAAALPQ==.json
- config/betterquesting/DefaultQuests/Quests/AppliedEnergisti-AAAAAAAAAAAAAAAAAAAAIw==/StockingFluids-soyN9ODlQmmjrKEyKBNENA==.json
Fixes the Applied Greg quest requisite from #16177.
Applied Greg should only require Interfacing with Machines and not Stocking Fluids. 
Stocking Fluids should require Applied Greg and not the other way around.
Before:
After:
> Fix Applied Greg quest requisite

- config/hodgepodge.cfg
Fixes several hodgepodge configs not actually working. (e.g., XaeroWorldMapScrolling, coke oven pollution)
This updates the hodgepodge config to a freshly generated one. However keeping all our configs (please check).
This was needed as a number of entry names were broken by https://github.com/GTNewHorizons/Hodgepodge/pull/313.
> Fix some broken hodgepodge config entries

- config/TwilightForest.cfg
- updates the TF config (while keeping our values)
- sets the EnableTiConstructIntegration to false and puts in the right ids. I talked to drparadox and that was the setting for GTNH intended by https://github.com/GTNewHorizons/twilightforest/pull/62
This fixes various issues in dev with duplicate incompatible fluids, duplicate tinker tool parts, ingot<->nugget crafting recipes, etc (again).
> update and fix TF config

- config/betterquesting/DefaultQuests/Quests/Tier2MV-AAAAAAAAAAAAAAAAAAAABA==/AdvancedCompress-AAAAAAAAAAAAAAAAAAAFKA==.json
- config/betterquesting/DefaultQuests/Quests/Tier2MV-AAAAAAAAAAAAAAAAAAAABA==/AdvancedMacerato-AAAAAAAAAAAAAAAAAAAFKQ==.json
- config/betterquesting/DefaultQuests/Quests/Tier2MV-AAAAAAAAAAAAAAAAAAAABA==/CoolingKanthal-AAAAAAAAAAAAAAAAAAAL_w==.json
- config/betterquesting/DefaultQuests/Quests/Tier2MV-AAAAAAAAAAAAAAAAAAAABA==/FluidSolidifier-AAAAAAAAAAAAAAAAAAADtw==.json
- config/betterquesting/DefaultQuests/Quests/Tier2MV-AAAAAAAAAAAAAAAAAAAABA==/PressAlltheThing-AAAAAAAAAAAAAAAAAAAGCw==.json
- config/betterquesting/DefaultQuests/Quests/Tier2MV-AAAAAAAAAAAAAAAAAAAABA==/SiliconWafer-AAAAAAAAAAAAAAAAAAADGA==.json
- config/betterquesting/DefaultQuests/Quests/Tier3HV-AAAAAAAAAAAAAAAAAAAABQ==/HVBender-AAAAAAAAAAAAAAAAAAAFCQ==.json
- config/betterquesting/DefaultQuests/Quests/Tier3HV-AAAAAAAAAAAAAAAAAAAABQ==/PerformingChemic-AAAAAAAAAAAAAAAAAAADrw==.json
- config/betterquesting/DefaultQuests/Quests/Tier3HV-AAAAAAAAAAAAAAAAAAAABQ==/PlayingWithDust-AAAAAAAAAAAAAAAAAAADAQ==.json
- config/betterquesting/DefaultQuests/Quests/Tier3HV-AAAAAAAAAAAAAAAAAAAABQ==/SeparatingGemsFr-AAAAAAAAAAAAAAAAAAAF8Q==.json
- config/betterquesting/DefaultQuests/Quests/Tier3HV-AAAAAAAAAAAAAAAAAAAABQ==/SeparatingMolecu-AAAAAAAAAAAAAAAAAAAHgQ==.json
- config/betterquesting/DefaultQuests/Quests/Tier3HV-AAAAAAAAAAAAAAAAAAAABQ==/UniversalMacerat-AAAAAAAAAAAAAAAAAAAEjA==.json
A set of quests in the hv and mv chapters now unlock prior quests in other chapters allowing players to not have quests of machines that they have not crafted. When they have indeed crafted the other machines.
Set of machines that were changed.
autoclave
macerator
bending machine
sifting machine
chemical reactor
centrifuge
mv forming press
Fluid solidifier
compressor
chemical bath
cutting machine
> Quest completes for lower tier machines from higher tier machines

- config/betterquesting/DefaultQuests/Quests/LooktotheEdges-AAAAAAAAAAAAAAAAAAAAGw==/Arthana-AAAAAAAAAAAAAAAAAAAJJQ==.json
- config/betterquesting/DefaultQuests/Quests/SpaceRace-AAAAAAAAAAAAAAAAAAAAIg==/AreYouPrepared-AAAAAAAAAAAAAAAAAAAELA==.json
Fixes #16453
Fixes both the reported instance and another instance in Are You Prepared
Tested that both books function properly after the change
> Fix enchanted minecraft:book rewards

- config/betterquesting/DefaultQuests/Quests/NoQuestLine/TriggerEpoxidSki-AAAAAAAAAAAAAAAAAAAL2w==.json
add missing prereq to epoxid skip quest to avoid it completing before reaching the tier.
fixes https://discord.com/channels/181078474394566657/949447391587733504/1256145102909472778
Even more important now in dev where the skip quests complete the entire line and not just one quest.
> Add missing prereq to epoxid skip quest

- config/betterquesting/DefaultQuests/Quests/MultipleQuestLine/ChemicalPseudoAl-AAAAAAAAAAAAAAAAAAAM1w==.json
QFT structure change fixed the symmetry by adding 3 Manipulators, but quest was never updated.
> Fixed QFT Quest showing incorrect amount of Manipulatiors

- config/InGameInfoXML/InGameInfo.xml
Fixes the issue of the broken {raintime} tag for users on multiplayer by giving a non-raintime variant on serverport check for -1.
Tested whether it would detect as the serverport -1 or not on a local singleplayer world (inverting behavior to see if the lines functioned correctly), and I had AnrDaemon help on the discord with finding a better tag for detection. I didn't test it on a personal server file host (as I only play through singleplayer). Might need someone to double check in case connecting to a server hosted on the same machine will still list it as -1 or not. This should work fine though for at minimum external server hostings not on the same pc/ip, so for that it'll be a lot better for users.
Compared to 2.6.1's lines (which would stay persistent for singleplayer users), new …
> Update InGameInfo.xml - Fix Server/Local Discrepency

- config/betterquesting/DefaultQuests/Quests/NoQuestLine/TriggerNaqlineSk-AAAAAAAAAAAAAAAAAAAL3A==.json
- config/betterquesting/DefaultQuests/Quests/NoQuestLine/TriggerPTFESkip-AAAAAAAAAAAAAAAAAAAL2Q==.json
- config/betterquesting/DefaultQuests/Quests/NoQuestLine/TriggerPolystyre-AAAAAAAAAAAAAAAAAAAL2g==.json
- config/betterquesting/DefaultQuests/Quests/NoQuestLine/TriggerSiliconeR-AAAAAAAAAAAAAAAAAAAL2A==.json
Epoxid and Styrene-Butadiene work fine, but these 4 quests don't check for Tier Unlock.
- 3 other HV plastics
- Naquadah dust
Naq dust will check for LuV Tier unlock and HV plastics will check for HV chem react (like how Styrene works).
> Trigger Quests inconsistency fix

- config/betterquesting/DefaultQuests/Quests/Tier2MV-AAAAAAAAAAAAAAAAAAAABA==/StainlessSteelEB-AAAAAAAAAAAAAAAAAAAC8Q==.json
- Fixed Stainless steel quest requiring either the dust OR the mv energy hatch instead of both.
Fixes (https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16658#issuecomment-2203965646)
> Fixed Stainless Steel quest requirement

- config/betterquesting/DefaultQuests/Quests/HowtoGeneratePow-AAAAAAAAAAAAAAAAAAAACQ==/AbsorbingMagicEn-AAAAAAAAAAAAAAAAAAALBg==.json
- config/betterquesting/DefaultQuests/Quests/HowtoGeneratePow-AAAAAAAAAAAAAAAAAAAACQ==/AbsorbingMagicEn-AAAAAAAAAAAAAAAAAAALBw==.json
- config/betterquesting/DefaultQuests/Quests/HowtoGeneratePow-AAAAAAAAAAAAAAAAAAAACQ==/AbsorbingMagicEn-AAAAAAAAAAAAAAAAAAALCA==.json
- config/betterquesting/DefaultQuests/Quests/HowtoGeneratePow-AAAAAAAAAAAAAAAAAAAACQ==/AbsorbingMagicEn-AAAAAAAAAAAAAAAAAAALCQ==.json
- Changed the order of the quest prerequisite, now each Absorber only needs prerequisite Convertor
- Removed doubled quest prerequisite
The old quest flow made no sense since the Convertor -> Absorber lines are seperated from each other by default.
Thanks to Mr_Vovikpro on discord for pointing it out.
> Fixed and cleaned Magic Absorber Quests

- config/betterquesting/DefaultQuests/Quests/ForestryandMulti-AAAAAAAAAAAAAAAAAAAAEg==/BioGasEngine-AAAAAAAAAAAAAAAAAAAEvw==.json
Fixes #16360 
Updates formatting and deletes creosote from quest desciption.  Tested it myself ingame and indeed it does not work anymore. Also replaces the creosote reward with fruit juice. Puts lava at the bottom to properly group the rewards.
> Update the Biogas engine quest

- config/betterquesting/DefaultQuests/Quests/BasicAutomation-AAAAAAAAAAAAAAAAAAAADg==/LetsGetSomePipes-AAAAAAAAAAAAAAAAAAAGVw==.json
Fixes #15329 
Adjust the quest to open up as soon as the player get his hand on lv circs since logistic pipes have been recently downtiered to lv instead of mv.
> Adjust logistic pipe questline to recent downtiering

- config/betterquesting/DefaultQuests/Quests/Tier4EV-AAAAAAAAAAAAAAAAAAAABg==/WaterFast-AAAAAAAAAAAAAAAAAAAKog==.json
Liked the proposal of fix #16063 and went ahead and added the hatch as an optional task with added info. 
The condense part is a hint to the matter condenser which is often paired with a reservoir hatch and pump for fast production of singularitys/matter balls for uua-production.
> Add reservoir hatch to the water quest in EV

- config/betterquesting/DefaultQuests/Quests/PayingtheHighest-AAAAAAAAAAAAAAAAAAAAHA==/AdvancedRituals-AAAAAAAAAAAAAAAAAAACyA==.json
- config/betterquesting/DefaultQuests/Quests/PayingtheHighest-AAAAAAAAAAAAAAAAAAAAHA==/ApprenticeOrb-AAAAAAAAAAAAAAAAAAABpw==.json
- config/betterquesting/DefaultQuests/Quests/PayingtheHighest-AAAAAAAAAAAAAAAAAAAAHA==/ArchmageOrbLetTh-AAAAAAAAAAAAAAAAAAACww==.json
- config/betterquesting/DefaultQuests/Quests/PayingtheHighest-AAAAAAAAAAAAAAAAAAAAHA==/Ascended-AAAAAAAAAAAAAAAAAAACvQ==.json
- config/betterquesting/DefaultQuests/Quests/PayingtheHighest-AAAAAAAAAAAAAAAAAAAAHA==/Convocationofthe-AAAAAAAAAAAAAAAAAAACyg==.json
- config/betterquesting/DefaultQuests/Quests/PayingtheHighest-AAAAAAAAAAAAAAAAAAAAHA==/HighendRituals-AAAAAAAAAAAAAAAAAAACyQ==.json
- config/betterquesting/DefaultQuests/Quests/PayingtheHighest-AAAAAAAAAAAAAAAAAAAAHA==/HowDarkCanYouGo-AAAAAAAAAAAAAAAAAAACvA==.json
- config/betterquesting/DefaultQuests/Quests/PayingtheHighest-AAAAAAAAAAAAAAAAAAAAHA==/MagicansOrb-AAAAAAAAAAAAAAAAAAABqA==.json
- config/betterquesting/DefaultQuests/Quests/PayingtheHighest-AAAAAAAAAAAAAAAAAAAAHA==/PortableBattery-AAAAAAAAAAAAAAAAAAAApA==.json
- config/betterquesting/DefaultQuests/Quests/PayingtheHighest-AAAAAAAAAAAAAAAAAAAAHA==/StarterKey-AAAAAAAAAAAAAAAAAAAJmQ==.json
Some items can be bound to the player in Blood Magic (Blood Orbs, Activation Crystals and Ritual Diviners) those don't count for the quest when they are bound. Also clarified that Energy Crystal has to be fully charged (https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15373#issuecomment-1998022306).
> Fixed "Bound by" items not detecting by QB

- config/betterquesting/DefaultQuests/Quests/Tier05Steam-AAAAAAAAAAAAAAAAAAAAAg==/ToolForge-AAAAAAAAAAAAAAAAAAAC5Q==.json
fixes #16754 
by adding a checkbox for people that to not craft the forge with iron blocks and also add the information that other materials can be used.
The checkbox is needed since ignoreNBT does not accept different forge variants. Another option to fix that issue would be adding all 13 variants of the forge which are differentiated by damage NBT to the quest but that would make it very long.
Lastly using the asterix on the forge (see below) sets the damageNBT to 32k and makes them shuffle all variants but looking up the recipe for it crashes the game so thats not a solution aswell.
> Make Tinker forge quest accept different mats & update info accordingly

- serverutilities/serverutilities.cfg
This will enable tracking of time players spend AFK, which shows up in game statistics and chat.
> Enable AFK time tracking by default, including singleplayer

- config/betterquesting/DefaultQuests/Quests/MultiblockGoals-AAAAAAAAAAAAAAAAAAAADA==/DiggingDeepforWa-jreOZVXRQa2sGXViV7-3Gg==.json
This small fix just locks the water pump quest behind the right quest now that everything regarding to the steam multis is merged.
> Fix water pump requirements

- config/INpureProjects/custom_nei_filters/Tcon.js
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9920
longer explanation:
if you search for "iron pickaxe head" (normal and important in early game) the game gives you 9 options (new nei grouping disabled it just makes this worse to see but doesnt really change anything):
however: none of them is the iron pickaxe head!!
the most important tinker tools have not been searchable in nei for many years now and there wasnt even any upside, nei was still full of tinker tools. This PR rectifies that:
you now get 12 options instead of 9, sure. but the first one is the one you want
Maybe even more clearly, with "thaumium binding" the comparison becomes 0 results to 1 result (the right one).
> fix tinker tools in NEI

- config/betterquesting/DefaultQuests/Quests/HowtoGeneratePow-AAAAAAAAAAAAAAAAAAAACQ==/PuttingtheSemiBa-AAAAAAAAAAAAAAAAAAAK5g==.json
fixes (https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16658#issuecomment-2268973383) by simply removing the need for the vac freezer quest.
Chrome does not need to be cooled down after EBFing. So the Vac freezer is not needed. The recipe for reference:
After the fix it has the same reqs as the other HV singleblock gens:
> Quick fix  for HV semifluid gen quest

- config/betterquesting/DefaultQuests/Quests/Tier3HV-AAAAAAAAAAAAAAAAAAAABQ==/FluidHeater-55XTBx8LRN2Ol_42LS6Mwg==.json
- config/betterquesting/DefaultQuests/Quests/Tier3HV-AAAAAAAAAAAAAAAAAAAABQ==/HotSlurry-AAAAAAAAAAAAAAAAAAALoQ==.json
Some recipes got changed to now use the fluid heater instead of the oil cracker (thank god). To keep the quests updated this PR changes some things:
-Updates the description for the bauxite slurry quest to state its made using a fluid heater
-Change the req for the bauxite slurry quest from the oil cracker quest to the fluid heater quest in the HV tab
-Mention that the HV fluid heater can be used to better process bauxite once the player has been to the moon in the fluid heater quest
See pictures below for better reference (the line is set to only show when hovered):
> Update quests related to Fluid Heater changes

- config/betterquesting/DefaultQuests/Quests/EndgameGoals-AAAAAAAAAAAAAAAAAAAAHQ==/Tier13UXV-7wI7VuLKRe6lqAJpuYKKJg==.json
- config/betterquesting/DefaultQuests/Quests/Tier12UMV-l37V2WvbSHGZQ5oMgAfBuw==/FinallyUniversiu-21tDEYptRuOgSJym30Watg==.json
Changes the description of the Universium quest to instead mention that the first few should go towards the Eternity loop.
Due to this, the T9 EOH mention has been moved to the UXV Hull quest.
> Make the Universium quest more clearer

- config/betterquesting/DefaultQuests/Quests/MultipleQuestLine/AllAloneintheNig-AAAAAAAAAAAAAAAAAAAF1w==.json
Updates the quest reload quest to not spread misinformation. This is a follow up to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/16910#issue-2448175764 that does not remove it as requested in discord dms.
> Update reload quest instead of removing it

- config/chisel.cfg
This config option has been unused since Sep 16, 2015 where it was replaced by `concreteVelocityMult`
https://github.com/GTNewHorizons/Chisel/commit/45b1cfdb9eb694c468a0a449ea5f3336bf65b680
It should have been removed on Sep 30, 2016 in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/commit/d131018d95aeabc05e7b8b9d6eb33f88e20c4231
where its comment was removed and the new `concreteVelocityMult` which replaces it was added, but the line wasn't actually removed.
> remove unused concreteVelocity from chisel.cfg

- config/betterquesting/DefaultQuests/Quests/Tier1LV-AAAAAAAAAAAAAAAAAAAAAw==/BlackandDecker-AAAAAAAAAAAAAAAAAAAGAQ==.json
This PR updates the quest explaining the electric version of the GT Wrench and Screwdriver. Additionally to changing the quest description to incentivize the player to have a look for himself regarding the material he wants to use it also detects if you craft GT Tools of a higher tier. The old version only detected LV tools despite the quest explicitly mentioning the MV and HV ones. See below for more details:
> Update the quest for electric GT Tools

- config/betterquesting/DefaultQuests/Quests/GT-AAAAAAAAAAAAAAAAAAAAEQ==/GTMultiblocks-w5O5rPL_Q_GDp8lxWMd0DQ==.json
- config/betterquesting/DefaultQuests/Quests/GT-AAAAAAAAAAAAAAAAAAAAEQ==/STEAMPOWEREDBREA-quLxATDCQFWsrZRuh_gspA==.json
- config/betterquesting/DefaultQuests/Quests/MultipleQuestLine/DarksteelChest-t6xRGFm_S2SG6_-xNh8mwQ==.json
- config/betterquesting/DefaultQuests/Quests/MultipleQuestLine/SteelChest-V4jinTYRSueIrEqn90dRzQ==.json
- config/betterquesting/DefaultQuests/Quests/Tier05Steam-AAAAAAAAAAAAAAAAAAAAAg==/FlamingIdiots-AAAAAAAAAAAAAAAAAAAHNQ==.json
- config/betterquesting/DefaultQuests/Quests/Tier05Steam-AAAAAAAAAAAAAAAAAAAAAg==/NewSourceofGlows-AAAAAAAAAAAAAAAAAAAERA==.json
- config/betterquesting/DefaultQuests/Quests/Tier4EV-AAAAAAAAAAAAAAAAAAAABg==/EXTREMEMIXING-kQL8JceoSMSLDU_2AFjoqw==.json
- config/betterquesting/DefaultQuests/Quests/Tier4EV-AAAAAAAAAAAAAAAAAAAABg==/Fourfluidsintheo-JkWQZxq_TECWjHhjywrZZA==.json
- config/betterquesting/DefaultQuests/Quests/Tier5IV-AAAAAAAAAAAAAAAAAAAABw==/Intradimensional-VCXYSn_PTZ6kY3d6kFTFwg==.json
- config/betterquesting/DefaultQuests/Quests/Tier5IV-AAAAAAAAAAAAAAAAAAAABw==/SupersizedBuses-Mt25IP2aShSSUBhZ1GGItg==.json
- config/betterquesting/DefaultQuests/Quests/Tier5IV-AAAAAAAAAAAAAAAAAAAABw==/Thesaneoption-SIqmtgRmTj-EsZlXpCdyWQ==.json
- config/betterquesting/DefaultQuests/Quests/Tier5IV-AAAAAAAAAAAAAAAAAAAABw==/Thorium232-nNTmwkdsQgyE6QAfmIwcvg==.json
- config/betterquesting/DefaultQuests/Quests/Tier5IV-AAAAAAAAAAAAAAAAAAAABw==/Universalpickaxe-VoQ7oLYhTjuomLCz_ddOhA==.json
- config/betterquesting/DefaultQuests/Quests/Tier5IV-AAAAAAAAAAAAAAAAAAAABw==/Waitareyousure-fvz-5lJaRAqfsM1hcAYOng==.json
This PR contains small fixes for some quests. Most of them fix quest names that were not in line with other quests of its tab. Examples can be seen below:
Additionally this fixes a steam age quest that was giving an LV lootbag and the requirements unlocking the EV multis in the GT++ Tab.
> Some adjustments for quest rewards, quest logic and mostly formatting

- config/betterquesting/DefaultQuests/Quests/AndSoItBegins-AAAAAAAAAAAAAAAAAAAAAA==/Evenmorechalleng-AAAAAAAAAAAAAAAAAAABjQ==.json
- config/betterquesting/DefaultQuests/Quests/AndSoItBegins-AAAAAAAAAAAAAAAAAAAAAA==/Goals-AAAAAAAAAAAAAAAAAAABjA==.json
- config/betterquesting/DefaultQuests/Quests/HowtoGeneratePow-AAAAAAAAAAAAAAAAAAAACQ==/PoweroftheSunatZ-AAAAAAAAAAAAAAAAAAAK2A==.json
- config/betterquesting/DefaultQuests/Quests/Tier2MV-AAAAAAAAAAAAAAAAAAAABA==/MVBending-AAAAAAAAAAAAAAAAAAAEOQ==.json
This PR does the following:
**Fixes (https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16658#issuecomment-2295240196) by changing the req to first UHV circuit quest (wetware mainframe)** 
**Change MV bender to give GT dense steel plates instead of IC2 ones**
**Adjust names of two quests to match the formatting of the whole beginning tab and fix a typo**
> More small quest fixes

- config/GTNewHorizons/CustomToolTips.xml
Identically to Cubic Zirconia, I've added a tooltip to Orundum to make it clear how to obtain it
These tooltips are added for the Orundum Dust, Gem, and Ore
Additionally, I changed the line that addds the Cubic Zirconia Dust tooltip to use Tab instead of four Spaces ;p
> Add tooltip for Orundum to make it clearer how to obtain

- config/InGameInfoXML/InGameInfo.xml
…from https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/16572 if IGI is not installed on the server, not based on a server port check.
This should be paired with https://github.com/GTNewHorizons/InGame-Info-XML/pull/21, and IGI should be included in the server files zip after that PR is merged.  If IGI is not included in the server though, it is still fine, as it will just fall back to the changes @PlayfulPiano made in the previous PR.
> Modified IGI config to fall back to less informative rain changes

- config/betterquesting/DefaultQuests/Quests/Tier05Steam-AAAAAAAAAAAAAAAAAAAAAg==/ToolForge-AAAAAAAAAAAAAAAAAAAC5Q==.json
With the wildcard NEI bug fixed (https://github.com/GTNewHorizons/BetterQuesting/pull/150#issue-2485562371) this quest can be done the proper way. Instead of a shitload of OR quests for every Forge variant we can now just use a wildcard which lets it shuffle between every forge and completes the quest. This allows for the optional task to be added back aswell.
> Add wildcard to Forge quest & add back optional task

- config/StorageDrawers.cfg
This adds configuration that is being added with https://github.com/GTNewHorizons/StorageDrawers/pull/33. This controls which add-on packs are enabled in the pack.
I've disabled the Erebus add-on as that hasn't been shipped with GTNH previously.
> Add storage drawers pack configuration

- config/betterquesting/DefaultQuests/Quests/Tier1LV-AAAAAAAAAAAAAAAAAAAAAw==/Naphtha-AAAAAAAAAAAAAAAAAAACgQ==.json
It was nerfed from 320 to 220. This PR fixes the quest side of it.
> Adjust fuel value of Naphtha in its dedicated quest

- config/NEID.cfg
NotEnoughIDs has an option called `PostNeidWorldsSupport` which enables additionally saving the blocks and metadata which can be, in the vanilla format(blocks which cannot be saved in that manner are simply replaced with air if over the block ID limit, or meta value 0 if over the meta limit). This enables worlds saved with NEID to be able to be opened(albeit likely broken, but in a way that won't crash) without NEID being present.
The important thing to note about this change, is that GTNH worlds will no longer be able to be opened at all without NEID present, as the `Blocks` and `Data` tags in the NBT are no longer present in the save file at all, and are replaced by NEID's `Blocks16` and `Data16`.
This option is on by default in NotEnoughIDs, but that doesn't really make much sense for …
> Disable PostNeidWorldsSupport by default in NotEnoughIDs

- config/gendustry/overrides/tuning.cfg
After https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/967, the indium bee is not as overpowered as it was before, so the mutatron blacklist is not necessary anymore.
> Re-enable mutatron for indium bee

- config/betterquesting/DefaultQuests/Quests/NoQuestLine/TriggerNetherSki-qFco17HGS0SxmpVn-uWJZQ==.json
Note: This was written in 2.6.1's questbook, and I have not written a quest before. I tried to match how other quests were made in the discord, so there might need to be edits to fix this.
This adds a Trigger Quest to skip "THE NETHER" & "How To Make Rubber" by obtaining 128 Rubber Bars in your inventory. Doing so will unlock "Wire-Wrap".
This is so players who decided to progress through the steam age without going to the nether (fear of nether mobs, wanting to build renewable methods early through XP Buckets, etc.) can still progress through the questbook.
> Create Trigger Quest: Nether Skip

- config/railcraft/items.cfg
removes railcraft items for:
- obsidian, sulfur, saltpeter, charcoal dust
- iron, steel, tin, copper, lead plate
- steel, copper, tin, lead ingot
- iron, steel, tin, copper, lead nugget
those all exist in gt.
this also removes a bunch of colliding recipes.
> remove duplicate items from railcraft

- config/BloodMagic/meteors/T9Ores.json
The main purpose of this meteor is providing an expensive no-rocket source of tartarite. Tartarite is required for progressing into UIV, and my PR adding Proto-Halkonite to UIV components accidentally killed off all no space runs, making them end at UIV. Now, I am very well aware no-space and challenge runs are unsupported, however
- My intention with Proto-Halkonite was never to kill no-space.
- Just because it is not officially supported doesn't mean no devs care about adding in some support for the content they provided.
- This meteor is quite expensive, coming in at a full Mk3 Space Mining Module (late UEV, pricy), making it not really worth using for anyone except out of necessity.
- In similar fashion, after a very long debate, a Tengam meteor was added a while ago. If that meteor …
> Add T9 planet meteor

- config/betterquesting/DefaultQuests/Quests/MassProcessing-AAAAAAAAAAAAAAAAAAAAEQ==/Asteampoweredwhi-0rUmaWIPQPaL93q-_pgKXw==.json
- config/betterquesting/DefaultQuests/Quests/MassProcessing-AAAAAAAAAAAAAAAAAAAAEQ==/Moresteammorepre-Plg8vg0gS9Ks2Ddc5sIVOg==.json
- config/betterquesting/DefaultQuests/Quests/MassProcessing-AAAAAAAAAAAAAAAAAAAAEQ==/Pressurewashing-zorY0c3BQuqLJp7ThOLG-g==.json
- config/betterquesting/DefaultQuests/Quests/MassProcessing-AAAAAAAAAAAAAAAAAAAAEQ==/SteamBlender-WEwrzX4ZRkSxJ3M6cBesfA==.json
- config/betterquesting/DefaultQuests/Quests/MassProcessing-AAAAAAAAAAAAAAAAAAAAEQ==/Steamstomping-s6AEHSKiQe2XveT_oDZbZg==.json
- config/betterquesting/DefaultQuests/Quests/MassProcessing-AAAAAAAAAAAAAAAAAAAAEQ==/SteamyMincer-AAAAAAAAAAAAAAAAAAAKzA==.json
8 steel -> 4 steel. Fixes one quest that i set to 1 steel too.
For more details on why: https://discord.com/channels/181078474394566657/949447391587733504/1287721952970276956
> Nerf steam multi quests to prevent skipping proper steel production early

- config/aroma1997/Aroma1997Core.cfg
- serverutilities/serverutilities.cfg
We now want to use server utilities for backups and remove aroma backup+aroma core.
it's requested by boubou and also dream approved: https://discord.com/channels/181078474394566657/603348502637969419/1290679475461423154
_note_ that this includes servers where aroma was never on. But if someone doesnt want it they can turn it off easily enough.
> Use SU for backups

- config/GalacticraftAmunRa.cfg
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17549.
Some numbers for context:
Oxygen Collector produces 0.75 units of oxygen per 10 ticks per leaf block, at a cost of 6 RF/t.
Hydroponics Unit produces 3 units of oxygen per 10 ticks, at a cost of 3 RF/t.
This PR buffs the Hydroponics Unit by a factor of 5, for a total of 15 oxygen units per 10 ticks. Energy cost is unchanged. (It is not configurable, would require a PR to Amun-Ra, and since it is so absurdly trivial I don't see a point.)
Number of oxygen generators needed to keep up with various oxygen consumers:
| Consumer  | Oxygen required per second | Collector (num. of leaves) | Hydroponics (old) | Hydroponics (new) |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| Oxygen …
> Buff Hydroponics Unit.

- config/betterquesting/DefaultQuests/Quests/SFMandComputers-AAAAAAAAAAAAAAAAAAAAHw==/Tier1-AAAAAAAAAAAAAAAAAAAG3w==.json
- config/opencomputers/gtnh.recipes
I am not sure how many players out there want to get any achievement possible but at last I am one of them.
Now I found out that the OC Transistor is fully disabled since we have the GT Transistor which all makes sense.
Sadly the linked OC Achievement wasn't altered or maybe it got forgotten about it so I thought over this and have had the following ideas (every idea foreces to re-enable the OC Transistor which I am not going to mention twice):
1. _Add in `gtnh.recipes` a simple shapeless recipe to transform GT Transistor into OC Transistor:_
**Pro**: Simply implemented
**Contra**: Whever cares about loosing at last one GT Transistor wouldn't be able to do a shapeless backcrafting since this would require a shapless recipie with RA2 in the corresponding mod. So it would be one way ticket. …
> Oc transistor achievement fix

- config/betterquesting/DefaultQuests/Quests/CoinsCoinsCoins-AAAAAAAAAAAAAAAAAAAAEA==/Naga-AAAAAAAAAAAAAAAAAAAEMQ==.json
- config/betterquesting/DefaultQuests/Quests/NoviceThaumaturg-AAAAAAAAAAAAAAAAAAAAFg==/StuckintheTwilig-AAAAAAAAAAAAAAAAAAAFWA==.json
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17440 and https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16380
Didnt find a way to make all variations of nagastones to work so I defaulted to the normal one
> Fixes some twilight quest issues

- serverutilities/serverutilities.cfg
This aims to lessen the amount of things players need to turn on in config if they want to use SU features.
The newly enabled values are
/ranks - Does nothing if ranks are turned off (which they are by default)
/chunks - Does nothing if chunk claiming is turned off (it is by default)
/dump_chunkloaders - Useful for debugging and is an admin command anyways
/killall - Admin command
/leaderboard - Why was this turned off?
/nbtedit - very useful for debugging and is still only usable by OPs
/tpl - admin command
/inv - admin command
and finally it enables chunk loading, this does nothing if claims are turned off as it says in the comment above the setting but leaves one less option that the players need to manually enable.
Most of the useful stuff that people use is still disabled but …
> Enable a few SU options

- config/betterquesting/DefaultQuests/Quests/MassProcessing-AAAAAAAAAAAAAAAAAAAAEQ==/HephaestusEBF-AAAAAAAAAAAAAAAAAAAH9A==.json
Renames the Volcanus quest since its original name ("Forge of the Gods") may not be very applicable anymore
> Rename Volcanus quest

- config/InGameInfoXML/InGameInfo.xml
Noticed that the current .xml file has an unnecessary chunk coordinate check (chunk coordinates, not relative coordinates within a chunk) for the "center of the chunk" line. I removed that part and added in the obsidian tough binding icon to be placed next to this line.
I would've added some sort of red tough binding icon but I could not figure out the proper file path for like an ignis tough binding. So obsidian it is.
Also uhhh ignore that second commit. I tried to fix one of the lines using a different tab size but it literally did nothing and could still be saved as a commit so /shrug
> Update InGameInfo.xml - Adding center chunk icon & removing unecessaey chunk checks

- config/InfernalMobs.cfg
WarpTheory spawns two types of creepers: "passive creepers", and "fake creepers". The former don't do anything, but the latter explode similar to normal creepers, with difference that their explosion doesn't do any world and player damage. Since fake creepers behave like normal creepers for the most part, if they spawn infernal, they can trigger normal infernal behavior and cause unintentional griefing. Passive creepers are already exempt from infernal status and I think the same should apply for fake creepers. See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17873 for some info.
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17873
> Prevent Fake Creepers from becoming Infernal

- README.md
- config/MouseTweaks.cfg
- config/NEI/client.cfg
We have two mods adding the same feature : when you hover on an item and scroll your mouse, it will transfer items to the other inventory
Both NEI and MouseTweaks add it
I made NEI enabled and mouse tweaks disabled
The one from mouse tweaks will send items in the crafting grid of your inventory instead of the hotbar when you use that feature in the player inventory
Also since almost every player opens the NEI settings menu at some point and the setting is there I thought it would be better to use the feature from NEI than mousetwkeas.
> Use mouse scrolling transfer from NEI

- config/WitchingGadgets.cfg
Removal agreed on with @GDCloudstrike and @serenibyss 
Tartarite now has real use in the pack and an intended method to obtain, therefore it shouldn't have a dupe.
> Added Tartarite to TC Dupe Blacklist

- config/CustomMainMenu/mainmenu.json
- config/CustomMainMenu/mainmenu_auto.json
- config/CustomMainMenu/mainmenu_large.json
- config/CustomMainMenu/mainmenu_normal.json
- config/CustomMainMenu/mainmenu_small.json
- config/txloader/load/custommainmenu/lang/en_US.lang
The copyright notice line got a bit too long on auto/large gui scale.
Before:
After:
Closes #16569
> Move Mojang copyright notice to new line in main menu

- config/BloodMagic/meteors/CheatyVeryLowQuantityRawTengam.json
The expected yield for this config and the old one are both 26 tengam ore (with the updated Blood Magic version, the previous version significantly underestimated the ore yield for all meteors so the numbers from beta 4 and before were shown to be a bit lower).
> Fix for tengam meteor to make it match old numbers

- config/BloodMagic/meteors/CheatyVeryLowQuantityRawTengam.json
ping @koolkrafter5 
The previous fix (https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/18064) uses salt ore for both yield and filler parts of the meteor. This confuses the NEI diagram, which shows the same tooltip for both salt blocks:
This PR replaces the filler block with stone salt ore (instead of marble ore), which displays the tooltip correctly without affecting the amount of ore one gets.
Picture of the full meteor (find the tengam!):
Ore yield (whether salt or tengam) is not changed from #18064.
> One more Tengam meteor fix.

- config/betterquesting/DefaultQuests/Quests/MultiblockGoals-AAAAAAAAAAAAAAAAAAAADA==/AwakenedDraconiu-AAAAAAAAAAAAAAAAAAAHKQ==.json
- config/betterquesting/DefaultQuests/Quests/MultiblockGoals-AAAAAAAAAAAAAAAAAAAADA==/ElectrumFluxCoil-AAAAAAAAAAAAAAAAAAAHGQ==.json
- config/betterquesting/DefaultQuests/Quests/MultiblockGoals-AAAAAAAAAAAAAAAAAAAADA==/HSSGCoilUpgrade-AAAAAAAAAAAAAAAAAAAB2w==.json
- config/betterquesting/DefaultQuests/Quests/MultiblockGoals-AAAAAAAAAAAAAAAAAAAADA==/HSSSCoilUpgrade-AAAAAAAAAAAAAAAAAAALTA==.json
- config/betterquesting/DefaultQuests/Quests/MultiblockGoals-AAAAAAAAAAAAAAAAAAAADA==/InfinityCoilUpgr-AAAAAAAAAAAAAAAAAAAMkQ==.json
- config/betterquesting/DefaultQuests/Quests/MultiblockGoals-AAAAAAAAAAAAAAAAAAAADA==/NaquadahCoilUpgr-AAAAAAAAAAAAAAAAAAAB3A==.json
- config/betterquesting/DefaultQuests/Quests/MultiblockGoals-AAAAAAAAAAAAAAAAAAAADA==/NichromeCoilUpgr-AAAAAAAAAAAAAAAAAAAATw==.json
- config/betterquesting/DefaultQuests/Quests/MultiblockGoals-AAAAAAAAAAAAAAAAAAAADA==/TriniumCoilUpgra-AAAAAAAAAAAAAAAAAAALTQ==.json
In EBF Coil quests, the symbol of temperature unit kelvin is not unified (`K`, `k` or no symbol at all).
Every symbol of kelvin will be unified to `K` after this PR.
> EBF Coil quest description: Unify kelvin symbol to K

- config/NEI/hiddenitems.cfg
Binnie mods use NEI lookup for these items to construct recipes.
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18229
> Prevent hiding of serum items

- config/MouseTweaks.cfg
This accidentally got changed after https://github.com/GTNewHorizons/MouseTweaks/pull/5 set the default value to false.
Fixes #16806
> Enable `RMBTweak` in MouseTweaks config

- config/InfernalMobs.cfg
Leftover from #17881. Passive Creepers were, in fact, not exempt from Infernal status.
> Prevent WarpTheory Passive Creeper from getting infernal

- config/defaultserverlist.json
- servers.json
The necessary changes to `defaultserverlist.json` were missed in #16821. This *needs* to go into 2.7.1.
The way we use DefaultServerList, we can only *add* servers by URL in the [`servers.json`](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/519e25268846c294a3b1ae6ab266165d2a4c79bb/servers.json). If we want to remove them, we also have to edit `defaultserverlist.json`.
Closes #18281.
> Drop EULA-breaking servers for good

- config/hodgepodge.cfg
Enabled by https://github.com/GTNewHorizons/Hodgepodge/pull/446
See #18316
> Set Ender Quarry energy storage size in hodgepodge config

- config/GTNewHorizons/CustomToolTips.xml
- config/ThaumicTinkerer.cfg
Allows for botania cake reactors :sunglasses: 
Forgot we never enabled this again after it was fixed in https://github.com/GTNewHorizons/ThaumicTinkerer/pull/31
> Enable thaumic fire spread again as it was fixed and made non world bricking

- config/ProjectRed.cfg
removes a duplicate redstone fluid and a duplicate red alloy fluid and fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18458. We have that all covered in gt.
see https://github.com/GTNewHorizons/ProjectRed/blob/master/src/main/scala/mrtjp/projectred/compatibility/tconstruct/PluginTConstruct.scala for what the config does.
> Red alloy fix/cleanup

- config/betterquesting/DefaultQuests/Quests/Tier5IV-AAAAAAAAAAAAAAAAAAAABw==/QuantumStar-AAAAAAAAAAAAAAAAAAAGAw==.json
Radium obtained from Quantum Star quest has an additional NBT tag that makes it different from radium you would obtain from processing (eg sifting uranium ores), which makes it not stackable in barrel-like containers.
Normally it wouldn't matter, as the player who claimed the reward would get it into their inventory where the item would start ticking and immediately become non-stackable via new NBT data. But I though I was smart and claimed it with full inventory over an item collector, only to realize that it doesn't stack anyways due to reward already having NBT data in it. Repeating this trick with edited quest reward made the reward barrel-stackable.
> Removed unnecessary NBT tag from Quantum Star quest radium reward

- config/HungerOverhaul/HungerOverhaul.cfg
This config removed both Wooden and Stone Hoe recipes. However coremod also removes the Stone Hoe recipe, so this only restores the Wooden one.
> Restore wooden hoe recipe

- config/etfuturum/mixins.cfg
Mitigates the issue with climbing stairs reported in https://github.com/Roadhog360/Et-Futurum-Requiem/issues/210
Based on the conversation in that issue, it seems the problem is still there and turning off the mixin is the most expedient solution.
> Mitigate stair climbing bug

- config/IguanaTinkerTweaks/restrictions.cfg
With the removal of the Gregtech Flint Sword there's a capability gap between the Wooden Sword & the Bronze Broadsword.
There is already a Flint Dagger which can be crafted, but it lacks a block ability (you throw it instead) and has lower damage than the Wooden Sword so I don't think it fits the needs of new players.
As a possible short-term fix, we could re-enable the Flint Sword Blade & Bone Wide Guard to allow crafting a Flint Broadsword. Incidentally this also allows crafting a Flint Rapier.
> Allow crafting a TiCo Flint Sword Blade & Bone Wide Guard

- config/MouseTweaks.cfg
I moved Cleanroom's MouseTweaks into Inventory Bogo Sorter in (https://github.com/GTNewHorizons/InventoryBogoSorter/pull/28), those changes include updating the configs.  
Merge after including Inventory Bogo Sorter in the pack and MouseTweaks and InventoryTweaks is removed from the pack
> Mouse Tweaks Config

- config/etfuturum/blocksitems.cfg
we already have gt dyes for all colors that everything can be crafted into, so we dont need these. And having both just creates conflicts everywhere.
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18690
> remove efr new dyes

- config/betterquesting/DefaultQuests/Quests/SpaceRace-AAAAAAAAAAAAAAAAAAAAIg==/MarsDungeon-AAAAAAAAAAAAAAAAAAAFpg==.json
use gt desh ingot as the reward instead of GCMars desh ingot. The plan is to remove the GCMars one fully.
> small gc quest fix

- config/betterquesting/DefaultQuests/Quests/Tier2MV-AAAAAAAAAAAAAAAAAAAABA==/MVSuperconductor-AAAAAAAAAAAAAAAAAAAFfA==.json
removes the VF prereq for mv SC, due to it not being hot anymore
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18722
together with https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/1155
> remove VF prereq for MV SC

- config/GalaxySpace/core.conf
Set enableOresGeneration to false in the GalaxySpace config so GalaxySpace ores will not generate.
> Disable GalaxySpace ore generation

- config/gendustry/overrides/tuning.cfg
Only merge if https://github.com/GTNewHorizons/GT5-Unofficial/pull/3894 gets merged.
Reverts the change happened in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/16977 due to compact controller removal, as it was enabled intentionally by https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/11921
Allows mutatron to be used for americium and europium bee, while still requiring the breeding blocks.
> Re-enable americium and europium bee mutatron

- config/GTNewHorizons/CustomDrops.xml
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/19001
Mob was dropping the old firefly item.
> Make TF Firefly Mob Drop Correct

- config/bugtorch/mixins.cfg
- config/coretweaks.cfg
- config/eternalsingularity.cfg
- config/hodgepodge.cfg
Some patches are done similarly by multiple mods. This PR disables one mixin for each such pair.
The two deleted lines in `eternalsingularity.cfg` are classes of mods we don't use in the pack.
> Disable duplicate Mixins

- serverutilities/serverutilities.cfg
Not sure where that quote came from, but it needs to be removed. Sorry about that...
> Fix typo in ServerUtilities backup config

- config/endercore/endercore.cfg
Reverts GTNewHorizons/GT-New-Horizons-Modpack#9905
As it turns out, the other mod that added this information was probably Inventory Tweaks which has since been removed from the pack.
> Revert "Disable registry name tooltip from EnderCore"

- .github/workflows/stale_remover.yml
If an issue is closed by the stale label, any comment will automatically reopen the issue. Does not affect closed issues without the stale label present
> Allow comments on closed stale issues to auto-reopen

- config/hodgepodge.cfg
This was disabled in #19216 to prevent hodgepodge-AF conflict. since [AF now disable its removeAll() patches if hodgepodge is present](https://github.com/embeddedt/ArchaicFix/pull/142), hodgepodge's implementation must be re-enabled or else we'd be left with no one to fix the lag
> re-enable optimizeTileentityRemoval

- config/etfuturum/experiments.cfg
https://discord.com/channels/181078474394566657/1321069193646444568/1369402563123871875 for context.
We currently don't need these features enough to justify any additional maintenance burden, so let's not use them until they're deemed final.
The stripped logs for crimson & warped trees will need to be removed from https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/1228
Should be merged along with https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/1257 & https://github.com/GTNewHorizons/GT5-Unofficial/pull/4273
> Don't use experimental EFR features

- config/EnhancedLootBags/LootBags.xml
- config/betterquesting/DefaultQuests/Quests/MultipleQuestLine/GasPlanets-AAAAAAAAAAAAAAAAAAAMiQ==.json
- config/txloader/load/betterquesting/lang/template.lang
Two very small changes.
1. Remove EEPROM (Lua BIOS) from the lootbag pool because it does NOT work and causes a "no bootable medium found" error
2. Adds the tiers of the gas giants to the quest book.
> Small Fixes

- config/DraconicEvolution.cfg
Revert the config change introduced in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/19259
It's a config, people can always disable it, but for pack default, it should be on.
> Restore the original catastrophical explosion

- config/NEI/collapsibleitems.cfg
Fixed off by one ProjectRed Lamp groupings - **Inverted White Lamp** is in normal lamps group.
Previous:
After the fix:
> Fix ProjectRed Lamps grouping for Inverted White Lamp

- config/betterquesting/DefaultQuests/Quests/MassProcessing-AAAAAAAAAAAAAAAAAAAAEQ==/Baskinthecurrent-AAAAAAAAAAAAAAAAAAAH7Q==.json
This line in the quest book is just incorrect. Tested in-game with a single UXV energy hatch trying to run a UXV recipe (it worked).
> Fix Industrial Arc Furnace Quest

- config/betterquesting/DefaultQuests/Quests/Tier2MV-AAAAAAAAAAAAAAAAAAAABA==/Conduits-AAAAAAAAAAAAAAAAAAAAhg==.json
Updated the "conduits" quest to require the MV Assembler as you can't craft the conduits within the quest without it.
Closes: #19863
> Conduits QB Change

- config/EnhancedLootBags/LootBags.xml
Fixes issue [#19966](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/19966) by removing the sense from the IC2 lootbag's loot table in the configs.
> Updated IC2 loot table (#19966)

- config/ArchitectureCraft.cfg
This adds Lapis Caelestis to the ArchitectureCraft block whitelist and makes shapes crafted from those as well as AntiBlocks and Neonite "glow" like their material blocks. This requires ArchitectureCraft [1.10.3](https://github.com/GTNewHorizons/ArchitectureCraft/releases/tag/1.10.3) or later to have any effect.
> Update ArchitectureCraft config to properly support shapes of "neon" blocks

- config/roguelike_dungeons/settings/theme_desert.json
In the code of roguelike dungeons, the 3rd floor desert dungeon should be red, but red sandstone does not exist in 1.7.10 until it was back ported by EFR. This uses the EFR red sandstone to recreate what it might look like.
> backport red sandstone 3rd floor to the desert dungeon

- config/betterquesting/DefaultQuests/Quests/HowtoBee-AAAAAAAAAAAAAAAAAAAAFA==/ApiaristsCloth-AAAAAAAAAAAAAAAAAAAD5A==.json
The Apiarist's Suit requires an MV assembler to craft, but the quest called for the carpenter. This is now changed to reflect that you need the MV assembler to be unlocked so that you can craft the Apiarist Suit.
> Changed the requirements for the Apiarist's Suit

- config/Waila.cfg
Using a size different from 100% makes the font rendering on the HUD look compressed and it looks super ugly, for comparison : 
this is the current of 88% 
this is the new with 100%
I just want the game to look nice
> Change waila HUD size to 100% for nice font rendering

- config/Waila.cfg
I removed the block rendering, there is no reason to have this, why would you need to have a separate HUD that renders a second time the block you are looking at when it's already in the middle of your screen right in front of you ? It takes screenspace for no added value and adds an ugly left padding.
I changed the colors a bit too to reduce the contrast in between the outer line and the background, I'm open to suggestion for the colors.
> Set waila icon render to false and edit default colors

- config/StorageDrawers.cfg
Change default for `breakDrawerDropMode=mixed`
See https://github.com/GTNewHorizons/StorageDrawers/pull/42
> Update StorageDrawers config

- config/betterquesting/DefaultQuests/Quests/Tier8UV-AAAAAAAAAAAAAAAAAAAALQ==/GeneralPurposeFe-AAAAAAAAAAAAAAAAAAAKmw==.json
- Corrects the quest "General Purpose Fermenting Bacteria" to have proper petri dish culture at beginning for breeding bacteria. 
- Fixes the last petri item so it shows in NEI
This will fix and close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/19265.
> General Purpose Fermenting Bacteria Quest Fix

- config/betterquesting/DefaultQuests/Quests/SpaceRace-AAAAAAAAAAAAAAAAAAAAIg==/Grapple-AAAAAAAAAAAAAAAAAAAFwA==.json
- The optional task was changes to a meteoric steel spring rather than the meteoric steel ring that it had. This is now in line with the actual crafting recipe. 
This will fix and close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/19911
> Grapple Recipe Mismatch Fix

- config/betterquesting/DefaultQuests/Quests/Tier05Steam-AAAAAAAAAAAAAAAAAAAAAg==/TheHellisThat-AAAAAAAAAAAAAAAAAAAAMQ==.json
- config/betterquesting/DefaultQuests/Quests/Tier0StoneAge-AAAAAAAAAAAAAAAAAAAAAQ==/HowtoOpenYourWoo-AAAAAAAAAAAAAAAAAAAJHQ==.json
- config/betterquesting/DefaultQuests/Quests/Tier0StoneAge-AAAAAAAAAAAAAAAAAAAAAQ==/TinkerTime-AAAAAAAAAAAAAAAAAAAAIQ==.json
- config/betterquesting/DefaultQuests/Quests/Tier0StoneAge-AAAAAAAAAAAAAAAAAAAAAQ==/WoodenDoor-AAAAAAAAAAAAAAAAAAAG_g==.json
- Replacing "Flint" with "Wooden" in describing pre-tinkers tools. There are no longer flint tools, so yeah.
- Allowing for oreDict on a few different early game wooden quest required objects. (I've also noted some items I'll be adding to the oreDict in game)
This will fix and close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/20265
This should fix and close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/20048
I would include photos but the code makes it very clear what changed.
> Early Game Wood oreDict Questbook Fixes & "Wood" replacing "Flint"

- config/InGameInfoXML/InGameInfo.xml
Something that I didn't realize until just now was that there was a lack of blocklight information shown by InGameInfoXML. Considering how that can be valuable to the user for quick glances (separate from the NEI F7 method), I figured I could write up a quick PR for it. It's a very small QoL change which doesn't affect any gameplay mechanic, so maybe it could be considered for 2.8? If not since feature freeze, that's fine as well.
Thanks,
-Piano
> Update InGameInfo.xml - Detailed Light Levels

- config/bogosorter.cfg
Adds the default config file for bogosorter mod
Disabled the `usageticker` HUD by default, it's the hud that pops up at the bottom left of your hotbat and renders the items you have in hand and also when you equip armor. We do not need more clutter on the HUD.
> Add bogosorter.cfg + disable usage ticker HUD

- config/betterquesting/DefaultQuests/Quests/CoinsCoinsCoins-AAAAAAAAAAAAAAAAAAAAEA==/CoalOreexchange-AAAAAAAAAAAAAAAAAAAJfA==.json
- config/betterquesting/DefaultQuests/Quests/CoinsCoinsCoins-AAAAAAAAAAAAAAAAAAAAEA==/CopperOreexchang-AAAAAAAAAAAAAAAAAAAJgQ==.json
- config/betterquesting/DefaultQuests/Quests/CoinsCoinsCoins-AAAAAAAAAAAAAAAAAAAAEA==/DiamondOreexchan-AAAAAAAAAAAAAAAAAAAJfg==.json
- config/betterquesting/DefaultQuests/Quests/CoinsCoinsCoins-AAAAAAAAAAAAAAAAAAAAEA==/LapisOreexchange-AAAAAAAAAAAAAAAAAAAJfQ==.json
- config/betterquesting/DefaultQuests/Quests/CoinsCoinsCoins-AAAAAAAAAAAAAAAAAAAAEA==/LeadOreexchange-AAAAAAAAAAAAAAAAAAAJhA==.json
- config/betterquesting/DefaultQuests/Quests/CoinsCoinsCoins-AAAAAAAAAAAAAAAAAAAAEA==/NetherquartzOree-AAAAAAAAAAAAAAAAAAAJgA==.json
- config/betterquesting/DefaultQuests/Quests/CoinsCoinsCoins-AAAAAAAAAAAAAAAAAAAAEA==/RedstoneOreexcha-AAAAAAAAAAAAAAAAAAAJfw==.json
- config/betterquesting/DefaultQuests/Quests/CoinsCoinsCoins-AAAAAAAAAAAAAAAAAAAAEA==/TinOreexchange-AAAAAAAAAAAAAAAAAAAJgg==.json
- config/betterquesting/DefaultQuests/Quests/CoinsCoinsCoins-AAAAAAAAAAAAAAAAAAAAEA==/UraniumOreexchan-AAAAAAAAAAAAAAAAAAAJgw==.json
Fixes #20539 
Coal, Copper, Diamond, Lapis, lead, Nether Quartz, Redstone, Tin, and Uranium quest trades now correctly consume raw ore.
> Ore trade quests now consume raw ore

- config/EMT.cfg
Attempt to enable enchanting for the non Thaumic boots mod boots, this might also enable enchantability of other things, if that is an issue it might be best to try and rectify this at the source code which could be done as well, which would simply require removing the config option and changing it on the boots to be always enabled
> Enable the enchantability of EMT tols

- config/betterquesting/DefaultQuests/Quests/KillAlltheThings-AAAAAAAAAAAAAAAAAAAAJQ==/ThePowerofInfini-AAAAAAAAAAAAAAAAAAABlQ==.json
- config/betterquesting/DefaultQuests/Quests/Tier8UV-AAAAAAAAAAAAAAAAAAAALQ==/SpaceElevator-AAAAAAAAAAAAAAAAAAAM0w==.json
- Removes King Slime completion quest dependency for secret witchery infinity egg quest, all of the other boss requirements make sense for this quest but this one is out of left field
- Removes Tier 7 plate quest requirement for Space Elevator quest, this was inhibiting completion of the quest for anyone doing a no rocket run, and you need the T7 plates to make the item anyway so the quest dependency is doing nothing helpful. 
This will close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/20723.
> Egg & SE Dependency Removal

- config/Backpack.cfg
- config/adventurebackpack.cfg
- config/etfuturum/functions.cfg
- Bans backpack from shulker box
- Bans shulker box from adventure backpack
- Bans shulker box from backpack
Shulker was already banned from adventure backpack
This contributes towards https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/20769
> Backpack & Shulker Bans

- config/IC2.ini
Just by changing a config the problems from IC2 in form of dropping teleporter (and other shenanigans) can be almost completely fixed. The only unaffected blocks are Reactor Chambers (drop as Basic Casings) and Charge Pads (they all drop as basic version in form of BatBox), at least from the batches i tested.
Just getting the PR in here to give as an option to fix some IC2 annoyances before proper Mixins are made (if any will be made). If there are some other reasons why it wasn't done before that i don't know of, then it's fine to ignore this.
Confirmed on the latest Beta 2 that the option works and no more teleporters drop when breaking with pickaxe/vajra. Kinda important since there are still 5 machines that can be crafted and used to "make" teleporters.
> Change the IC2 config ignoreWrenchRequirement to true

- config/betterquesting/DefaultQuests/Quests/HowtoBee-AAAAAAAAAAAAAAAAAAAAFA==/ToPlayGod-AAAAAAAAAAAAAAAAAAAB-g==.json
- config/betterquesting/DefaultQuests/Quests/Tier6LuV-AAAAAAAAAAAAAAAAAAAACA==/StartingFusion-AAAAAAAAAAAAAAAAAAAEvA==.json
- To play god required the location quest of travelling to Mars. I've changed it to require a bucket of bacterial sludge since that is the point of the quest and it allows for people who take the harder route by not going to Mars also able to complete the quest. I changed the description to account for this as well.
- The "Starting Fusion" quest now requires the Clarifier quest to unlock, since now it requires Netherite, which is dependent on obtaining Grade 1 water
This will close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/20910
** Note on the issue, I decided not to change the rocket dependency for "Fusion Rocketry" or "Mysterious..." because they are not main quests and do not prohibit you from continuing down the line. I maintain that we will assist but not cater …
> Quest Updates for "To Play God" and "Starting Fusion"

- config/Backpack.cfg
This is a followup for https://github.com/GTNewHorizons/Minecraft-Backpack-Mod/pull/15.
The changes introduced with https://github.com/GTNewHorizons/Minecraft-Backpack-Mod/pull/14 made the Big Backpack inventory fit better with auto gui scale. Previously, or backpack sizes were multiples of 9 in accordance with the standard Minecraft inventory slot layout. However, with the new layout, the Big Backpacks in GTNH are now missing a slot in the last row.
This adds one slot to the Big Backpack to fill out the layout. This is very much just an aesthetic change, but I don't see any downsides with it.
This will not affect existing backpacks.
Before:
After:
> Increase Big Backpack slots by 1

- config/etfuturum/blocksitems.cfg
Enables EFR concrete in the configs to provide more blocks for decoration. Currently there's no way to craft the EFR concrete blocks, and so this PR should be approved along with https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/1359, which gives them chisel crafting recipes.
> Enable Concrete in EFR configs

- config/NEI/collapsibleitems.cfg
Creates groups (or adds to existing groups, when possible) for EFR.
This PR also includes three changes unrelated to EFR:
- `minecraft:arrow` is now part of the (non-tinkers) arrow group
- Grouped Iron Chest upgrades together (to be consistent with the Barrel and Shulker groups)
- Created a group for boats. Which includes, besides MC and EFR, boats from IC2, Adventure Backpack and Thaumic Horizons
EFR items in NEI:
> Add collapsible NEI groups for Et Futurum Requiem

- config/Baubles.cfg
This will prevent slots from changing order when new slots are added, which led to items being in the wrong slot for their type.
This change will also require new slots to be added manually in this config, but that's simple enough.
> Use manualSlotSelection and slotTypeOverrides in Baubles.cfg

- config/betterquesting/DefaultQuests/Quests/AndSoItBegins-AAAAAAAAAAAAAAAAAAAAAA==/PermanentOffhand-U7JoxM0mRaWx0MYriD2LtQ==.json
Offhand working on backpacks is a relatively new feature that isn't in the default Backhand mod, so i thought it'd be good to add more documentation on that feature.
> Add more offhand info

- config/etfuturum/blocksitems.cfg
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/21271
Following the discussion on Discord: https://discord.com/channels/181078474394566657/401118216228831252/1418190294410723389
I think we should disable the new anvils from EFR due to known and potentially more uncovered issues.
It might be a good idea to check other block replacements from EFR too, especially ones that are used in multiblocks for example.
> fix: disable new anvils from EFR

- config/EnhancedLootBags/LootBags.xml
Muffler upgrades have been removed from the pack as machines now have an inbuilt method of sound muffling.
> Remove muffler upgrade from loot bags

- .github/ISSUE_TEMPLATE/000-report-crash.yml
- .github/ISSUE_TEMPLATE/001-report-bug.yml
We are officially enabling java 25 with 2.8, so add that to our issue templates. If not the lastest supported java, people should stay on LTS releases. Keep java 24 around as last non-LTS release as people might not have updated yet.
> Add Java 25 to issue templates and drop non-LTS versions

- config/Backpack.cfg
- config/GTNewHorizons/CustomToolTips.xml
There are some changes ([1](https://github.com/GTNewHorizons/Minecraft-Backpack-Mod/pull/19), [2](https://github.com/GTNewHorizons/Minecraft-Backpack-Mod/pull/17)) in the pipeline to improve the inventory layout with the original 90 slots, so go back to that for now. That means, the last slot in the grid will be empty with the current algorithm, but that's acceptable.
> Change Big Backpacks to 90 slots again

- config/betterquesting/DefaultQuests/Quests/Tier05Steam-AAAAAAAAAAAAAAAAAAAAAg==/BetterMakethatTw-fRHWhPgpRyyvSRZpL1Pkbw==.json
The taks is now crafting so it doesnt auto complete. I also made the dep visible that was hidden for no reason. takes care of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/21341#issuecomment-3344296046
> fix second anvil quest

- config/betterquesting/DefaultQuests/Quests/Tier4EV-AAAAAAAAAAAAAAAAAAAABg==/WhatsintheBox-AAAAAAAAAAAAAAAAAAAHhQ==.json
the questbook tells the reader that they are unable to shift-click into the lead lined box, which I am assuming is from an older version where this wasn't possible
> remove incorrect shift-clicking dissuasion
