GTNewHorizons/GT-New-Horizons-Modpack

scripts/Minecraft.zs
Right now you HAVE to put ingrediences to the left of the crafting grid.
=> Mirrored Torch recipe

scripts/Ender-IO.zs
Commits:
ec80d80bf43a5a0a360cd114451609556a8e1381
51df01db65a911c635a2c5a8520d968d8b2436f6
433a6c7a2917e768e56b7bb8b3fbd22036458af9
=> New recipe for dark clear glass & Bank Upgrade Fix

config/Morpheus.cfg
Should we lower it a bit?
To be discussed.
=> Lower necessary sleep percentage to 33

config/OpenComputers.cfg
Increased clipboard,
increased model count for 3D printers,
higher tier stuff adjustment,
=> Tweaks to improve openCC experience

scripts/Minecraft.zs
Spelling fixes and moving stuff to right place
(Now fixed derp and in the right branch)
=> Script arrangements

scripts/Blood-Magic.zs, scripts/CoreMod.zs, scripts/Extra-Bees.zs, scripts/Forestry.zs, scripts/Magic-Bees.zs, scripts/Open-Blocks.zs, scripts/Thaumcraft-02-Thaumaturgy-1.zs, scripts/Thaumcraft-02-Thaumaturgy-2.zs, scripts/Thaumcraft-03-Alchemy.zs, scripts/Thaumcraft-06-Eldritch.zs, scripts/ThaumicTinkerer-01.zs, scripts/ThaumicTinkerer-02-Kami.zs, scripts/Warp-Theory.zs, scripts/Witchery.zs
Maybe it will be better to avoid using specific language code in localization text. This change will make all the text display normally in different language environment, instead of only showing the keys.
=> Solve localization Issue

scripts/ThaumicTinkerer-03-Wands.zs
Fix the cap of Ichorium Ardorned Ichorclothstapped Silverwooden Scepter
=> Fix the recipe of a TT-kami scepter

config/adventurebackpack.cfg
Config for Adventure Backpack f-beta2, 'fix' https://github.com/GTNewHorizons/NewHorizons/issues/749
=> Disable backpack tools rendering

config/OpenComputers.cfg, scripts/Advanced-Backpacks.zs
for Adventure Backpack v0.9fbeta8
=> Pantaloons -> adventurePants

config/gendustry/bees.cfg
#868 see https://github.com/GTNewHorizons/NewHorizons/issues/868
=> Fix: Tungsten bee mutation

config/StorageDrawers.cfg
default config + 
B:enableItemConversion=false
=> Disable Storage Drawers oredict unification

scripts/Advanced-Backpacks.zs
it does nothing in the current state, only possible bugs
=> Disable motorized boat

config/betterquesting/DefaultQuests.json
Did a complete check on all quests for spelling and grammar.
=> Quest description fixes

config/betterquesting/DefaultQuests.json
I cherry-picked the two commits that were done on the master branch to 1.5.0.0 and fixed yet another typo.
=> Quest description improvements

config/betterquesting/DefaultQuests.json
Just fixed the small error i caused.
=> my small hotfix

scripts/Galacticraft.zs
=> Infite oxygen supply

config/betterquesting/DefaultQuests.json
a few more changes from MTesseractS
=> The final pull request (for now)

config/betterquesting/DefaultQuests.json
Replaced them with
16 Heavy Fuel Cell and
32 Light Fuel Cell since the cracked versions have been removed
you were to fast dream, i missed this fix :)
=> Maybe fix for quest 768

config/betterquesting/DefaultQuests.json
=> A new transportation quest

config/EnderStorage.cfg, config/betterquesting/DefaultQuests.json, resources/enderstorage/lang/en_US.lang, scripts/Renaming.zs
Fix so that it isn't disabled, so that quest Dimensional Chest (603) can be completed. (Still uncraftable)
rename of new quest
=> Bugfix with vanilla ender chest

resources/draconicevolution/lang/en_US.lang, resources/forbidden/lang/en_US.lang, scripts/Avaritia.zs
=> Avaritia Recipes part 1

config/betterquesting/DefaultQuests.json
Change "tree ingots" to "three ingots"
=> Correcting spelling error in quest #53 "Hammer time v2"

scripts/ZZ-Client-Only.zs
othewise free coin molds in a crating table
=> Fix vals for zzCoin mold so it works

config/AppliedEnergistics2/AppliedEnergistics2.cfg, scripts/AE2.zs
As suggested of
https://github.com/GTNewHorizons/NewHorizons/issues/1653
Tested and working
=> Removal of grindstone NEI Recipes

scripts/Railcraft.zs
Apologies for being unclear earlier, but this is what I was trying to, but failed adequately explain when i said make the two recipes roughly equal since they are both largely cosmetic blocks in [https://github.com/GTNewHorizons/NewHorizons/issues/1700](url)
Feel free to disregard if you so desire.
=> Equalize infernal brick and sandy brick recipes

scripts/Gregtech.zs
Found it odd that there were no recipes to turn Rye or Oats into Flour in either the Macerator or with a Mortar and Pestle.  So I fixed that.
Thanks in advance.
=> Turn Rye and Oats into Flour

config/betterquesting/DefaultQuests.json
Changed the description to flow better.
=> Fixed Auto Mining Quest Description

.github/issue_template.md
Adds lines for extra spacing and separation of parts of an issue.
=> Make issue template slightly more readable

scripts/Railcraft.zs
https://i.imgur.com/wA4178Q.png
https://i.imgur.com/5g6IssD.png
https://i.imgur.com/FZSD10m.png
=> Remove eio alloy from adv coke oven(raicraft)

scripts/Emt.zs
fully fixed all invalid damage values on ic2 charged items
=> EMTools minetweaker script fix

config/betterquesting/DefaultQuests.json
=> New Quests

config/betterquesting/DefaultQuests.json
=> Fix from Warlord Wossman for #2730

scripts/CoreMod.zs
script fix for
https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/71fb5360666fab181662faf67d93f222c609e539
=> Moved Alloy Smelter Recipes to the coremod

config/GregTech/WorldGeneration.cfg
+added custom veins as named veins
=> shruken filesize

scripts/Forestry-Frames.zs
Fixed a couple of errors and added the max values if one was set. (Bee Frame Tool Tips)
=> Some fixes and additions.

scripts/Emt.zs
recipes for: https://github.com/GTNewHorizons/Electro-Magic-Tools/pull/7
=> +added Recipes for the Large Essentia Generator and support Blocks.

config/gendustry/overrides/recipes.cfg
vanilla porkchop, beef, chicken, fish
=> add 4 item to protein

scripts/CoreMod.zs
Fix Crafting Recipe for NeutronReflectorParts
https://github.com/GTNewHorizons/NewHorizons/issues/3601
https://github.com/GTNewHorizons/NewHorizons/issues/3547
=> Fix Neutron Reflector Parts

scripts/Extra-Utilities.zs
Because don't use the ore dictionary,can't make Bedrock drum etc..
=> Fix can't craft item what using Bedrockium plate

scripts/Gregtech.zs
Added recipes for minced meat in a mortar. #4039
=> added mortar recipes for cooked/uncooked minced meat - issue 4039

config/ThaumicHorizons.cfg
tested on zeta w/o complications so far
=> enabled pocket plane

scripts/Emt.zs
+now accept any damage value
Signed-off-by: bartimaeusnek <33183715+bartimaeusnek@users.noreply.github.com>
=> fixed damage problems with EMT Recipes

.github/issue_template.md
Sorry...it was driving me crazy. I fixed it. Simple commit.
=> Fixed Spelling in Issue Template

scripts/Extra-Cells.zs
+ added ductape fix for computronics recipes
=> ME upgrade old broken recipes removed

config/forestry/backpacks.cfg
=> Add space rocks to diggers backpack

scripts/Galacticraft.zs
+added cheese ore recipe from cheese curds for no-rocket-run
=> added a script recipe

scripts/Chisel.zs, scripts/Tinkers-Construct.zs
TinkersConstruct Chiselling sometimes hang-up client in infinite loop.
This patch offloads TinkersConstruct decoration blocks chiselling to Chisel2 mod.
=> feat(tconstruct): move chiselling decorations to chisel2 mod

config/HoloInventory.cfg
Just to prevent this from happening lol:
https://i.imgur.com/RDLEmyh.png
=> HoloInventory: Added Nuclear Info Panel & Advance Panel to Blacklist

config/StorageDrawers.cfg
Adapt to new custom version of StorageDrawers
=> update(config): storagedrawers

.gitignore, config/enderzoo/EnderZoo.cfg, config/enderzoo/SpawnConfig_Core.xml
https://github.com/GTNewHorizons/NewHorizons/issues/5485
=> Update Enderzoo Dire Wolf config per #5485

.gitignore
=> apple core .gitignore update

scripts/Chisel.zs
Address issue [Mushroom Block With Chisel Support #5701](https://github.com/GTNewHorizons/NewHorizons/issues/5701)
=> feat(chisel): mushroom blocks variations

config/InGameInfoXML.cfg
https://github.com/GTNewHorizons/InGame-Info-XML/commit/df3ab2680e35fd6254c6c31b579c5d8ba4182e92
=> scale value to INT

scripts/Thaumic-Exploration-01.zs
nerf for the everburn urn that was discused 
#5739
=> nerf-everfull-urn

scripts/Biome-o-Plenty.zs, scripts/Extra-Bees.zs, scripts/Forbidden-Magic.zs, scripts/Gregtech.zs, scripts/Natura.zs
- Add missing Gregtech Extractor recipes for Dyes
- Change dyes recipes to output Gregtech Dyes rather than per-mod dyes
- Add Shapeless Workbench dyeOre to corresponding Gregtech Dye conversion recipes
=> Improve and harmonize dyes recipes

scripts/Thaumic-Energistics.zs
Now it selects wands only by correct nbt tag
=> Fixed Arcane Assembler recipe

config/InGameInfo.xml
Adds display of temperature in °C and °K:
=> improve(temperature): add celcius and kelvin

resources/galaxyspace/lang/en_US.lang
From: 
tile.Crystall.name=Unknow Crystal 
item.BarnardaCStrawberry.name=Unknow Fruits
to: 
tile.Crystall.name=Unknow**n** Crystal
item.BarnardaCStrawberry.name=Unknow**n** Fruits
=> Fix misspelled crystal

resources/galaxyspace/lang/en_US.lang
=> Legaris Fixes

config/GregTech/GregTech.cfg, scripts/Iron-Tanks.zs
added new underground fluids and values
first suggestions please discuss and suggest new values
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5974
=> added new underground fluids and values

config/AWWayofTime.cfg
Added a bunch of quests, added text to some to make them make more sense or reveal additional functionality (fluid interface for example).
Most of the quest rewards are boring (and could use spicing up), but make sure to check 2528 (I'll Send Wireless Signals Where I Want, Thank You) and 2543 (Wireless 3.0) to see if you agree with the rewards. Keep in mind you need to be UV+ to make infinity (I'm pretty sure?).
I'll make some quests to explain how to actually use AE2 later on, like #4519 says, but I want to finish this part first.
=> Applied Energistics 2 Quest Additions/Modifications

scripts/IC2.zs
Fixed a bug with the bucket dup
=> Fixed a bug with the bucket dup

scripts/ThaumicTinkerer-01.zs
=> Fix Fume Dissipator recipe

scripts/AE2.zs
Shaped recipe from AE
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/16
=> Add recipe from AE

scripts/Avaritia.zs, scripts/CoreMod.zs
See #5732. Should be easier to make before the DCT now, also more magical-ish too.
=> Skullfire sword

scripts/Forbidden-Magic-01-Wands.zs, scripts/Galacticraft.zs
feat(Galacticraft)new oxygen tanks
add 2 new Tiers of oxygen tanks
=> Galacticraft additional oxy tank

scripts/Avaritia.zs
#6072 Add wildcards to quantum and gravi stuff. LIA set to 0, it works regardless of whether you charge it anyway, but * doesn't work
=> Inf Armor Fix

scripts/Harvestcraft.zs
Issue #6499 
Added recipe to allow cooking rabbit in a furnace.
=> Added recipe for cooking rabbit. Issue #6499.

scripts/Harvestcraft.zs
Fix issue where gooseberry and yogurt made pineapple yogurt. Issue #6320
=> Fix issue 6320, no recipe for gooseberry yogurt.

config/forestry/backpacks.cfg
Tested and working. Sorry forgot screenshot on this one. #5865
=> Fix issue 5865. All meats into Hunter's Pack.

.github/workflows/stale.yml
=> Fix typo in stale bot

scripts/IC2.zs
=> minig pipe - conversely

config/chisel.cfg
Only merge if GTNewHorizons/Chisel#5 is already merged! Otherwise you can chisel instead of using the PLE, which the other PR prevents in code
=> Allows arcane stone chiseling again

.gitignore, config/InGameInfo.xml, resources/bibliocraft/lang/en_US.lang, resources/extrautils/lang/en_US.lang, resources/gravisuit/lang/en_US.lang, resources/miscutils/lang/en_US.lang, resources/opencomputers/lang/en_US.lang, resources/sleepingbag/lang/en_US.lang, resources/tectech/lang/en_US.lang, resources/thaumcraft/lang/en_US.lang, resources/thaumicbases/lang/en_US.lang, scripts/ZZ-Client-Only.zs
See GTNewHorizons/GT-New-Horizons-Modpack#4928
The deleted .lang files will be integrated in their respective mods.
=> Some localizations

scripts/IC2.zs
=> Preserve NBT tags when repairing rubber boots

config/GTNewHorizons/CustomToolTips.xml
=> Dollytooltip

config/chisel.cfg, scripts/Chisel.zs
See https://github.com/GTNewHorizons/Chisel/pull/6
It's very durable because it uses dense bedrockium and vanadiumsteel. It also takes HV, and 20 minutes. It's craftable at HV.
=> Added config and recipe for new chisel

scripts/IC2.zs
Follow up of 01fffb4 and #6860
=> Preserve NBT tags when repairing hazmat suit

scripts/Tinkers-Construct.zs
Added in Core mod with my other pull request
connected to: #4602
=> Remove Ardite compression recipe

scripts/Gregtech.zs, scripts/IC2.zs
GTNewHorizons/GT5-Unofficial#346
=>  Remove scripts mentioned in GTNewHorizons/GT5-Unofficial#346 

scripts/Tinkers-Construct.zs
https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/136
=> Remove added to NH Core mod metal block recipes

config/RTG/rtg.cfg
=> Flipped setting for RTG Strongholds

config/RTG/rtg.cfg
Patch issue: RTG Config files & Strongholds #6986
=> patch(config): patch RTG config for issue #6986

config/GTNewHorizons/CustomDrops.xml
add loot to Fire and Slime Beetel
add loot to Kobolt and Druide
add loot to Redcap and RedcapSapper
add loot to swarming Spider
add venison to Deers and raw rabbit to rabbit
add turkey to the BoP Rosester
=> Tf animal drops

scripts/IC2.zs
=> Fix bucket dupe in hazmat repair

scripts/GT++.zs
change the steam Boiler recipes and Chassis
add new Boiler Quests to Mv and Hv Tab
=> change(GT++)Boiler recipes

scripts/Draconic-Evolution.zs, scripts/Steves-Carts.zs, scripts/Translocators.zs
recipes are now in the core mod
=> remove(Steves Carts, Translocator, DE)implossion compressor recipe

scripts/Forestry.zs
=> #7088 swapped frames with bee houses. Also removed duplicate entries, and did some formatting

config/Betterloadingscreen/tips/en_US.txt
This file actually doesn't regenerate as long as the old one stays in config. Might as well update this one. Ran this file through Grammarly too, in order to reduce grammar and spelling errors
=> Actually updating the tips file

scripts/Thaumic-Horizons.zs
**Old Recipes:**
Transduction Amplifier
Planar Conduit
**New Recipes:**
Transduction Amplifier
Planar Conduit
=> Changed Recipe for Planar Conduit and Transduction Amplifier

scripts/Thaumic-Horizons.zs
This typo makes it unreasearchable.
=> Fix typo in Planar Theory research item

config/ModMixinsPlugin.cfg
change pollution values
chnge Firebox from 40 to 20 
change coke ovens from 20 to 10
=> new values dicussed with KJ yesterday.

scripts/Thaumcraft-03-Alchemy.zs
Recipe for https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/3141
=> amber dust -> gem recipe

scripts/Automagy.zs, scripts/Draconic-Evolution.zs, scripts/Extra-Utilities.zs, scripts/GT++.zs, scripts/Genetics.zs, scripts/Harvestcraft.zs, scripts/Malis-Doors.zs, scripts/Minecraft.zs, scripts/Natura.zs, scripts/Railcraft.zs, scripts/Thaumcraft-04-Artifice.zs, scripts/Tinkers-Construct.zs, scripts/Witchery.zs
See the linked issues for details
~~#697 should be #6971~~. I've given up on the golden head for now, since I can't get it to ignore NBT data on input.
=> Recipe script change

scripts/Biome-o-Plenty.zs, scripts/Forestry.zs, scripts/Minecraft.zs, scripts/Tainted-Magic-1.zs, scripts/Thaumcraft-03-Alchemy.zs, scripts/Thaumcraft-05-Golemancy.zs, scripts/Thaumic-Bases-01-Main.zs, scripts/Thaumic-Machina.zs, scripts/ThaumicTinkerer-01.zs
For #5028 I removed both the troublesome research and the one past it. Both are useless. If you've researched it already, you'll need to use a command to remove the research I guess? Unless someone has a suggestion?
=> A few more recipe script changes

scripts/Gregtech.zs
=> delete extruder shape boat

scripts/Logistics-Pipes.zs
For use together with
[logisticspipes-0.9.4.4.GTNH.jar.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5793168/logisticspipes-0.9.4.4.GTNH.jar.zip) (remove the .zip before use).
This is pull is for testing and feedback.
=> Logistics Pipes Script for Testing on Zeta

scripts/Thaumic-Bases-01-Main.zs
=> Fix overchanter recipe

scripts/Thaumic-Bases-01-Main.zs
See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/7726#issuecomment-809752412
=> Fix some more

scripts/GT++.zs
Reverts GTNewHorizons/GT-New-Horizons-Modpack#7802
=> Revert "Remove PSS controller recipe"

scripts/AE2.zs
=> Fixing the AE 2 new assembler recipes

scripts/Harvestcraft.zs
See #7120, #7166.
Also resorted it better into groups.
Also removed pointless script recipes, as they worked without them the same way.
=> Harvestcraft recipe fixes

scripts/Railcraft.zs
See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7921
=> Fix wood platform and add recipe for nether cobblestone

scripts/CoreMod.zs
=> adjust voltage for engraved energy chip

scripts/BiblioCraft.zs
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8003
=> Add cleaning recipe for clipboard

scripts/Computronics.zs
=> added Magical Memory (Creative) recipe

scripts/AE2.zs
see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7933
=> [DRAFT] add recipe for ore dictionary filter card

scripts/Witchery.zs
=> Change recipe to use tanned leather

scripts/Emt.zs, scripts/ThaumicTinkerer-01.zs
Infusion recipe does not have Oredict enabled, so I'm specifying a specific item
=> Fix ReinforedGlass Plate

scripts/Extra-Utilities.zs
see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8198
=> Remove double recipe for ender marker

config/EnhancedLootBags/LootBags.xml
Not tested. Based on #7815 report.
=> Change Charged Thaumium Caps to functional ones.

config/GTNewHorizons/dreamcraft.cfg
Add config for the new options defined in:
* https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/196
=> Add Deep Dark void miner config options

config/GTNewHorizons/dreamcraft.cfg
Sorry, I ended up changing these a little in https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/196
=> Update Deep Dark void miner config comments

scripts/Gregtech.zs
Until we have a proper settlement over how these two sets of API should coexists, this will have to make do
=> Add a recipe for StructureLib blueprint

config/GTNewHorizons/HazardousItems.xml
Changed inFire to gregtech:hot to support new gloves from GTNHCoreMod.
Shouldn't be pulled before accepting https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/200
=> Changed the damage source of hot items

config/GregTech/GregTech.cfg
=> Fix Wrong Hydrofluoric Acid on Makemake

resources/minecraft/lang/en_US.lang
First time editing quests. I hope I have done everything right.
=> Remove no longer valid warning about broken oredict

resources/minecraft/lang/en_US.lang
Sorry, didn't know that this file also needed to be updated, and missed it in:
* https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/8512
=> Remove bolt upgrade warning text, part 2

README.md
Too many people in discord have tried to build the pack by downloading individual mods from the Modlist, this should help.
=> Add install/download links

scripts/Draconic-Evolution.zs
See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8564, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8566.
Might make it too easy to auto-kill the wither, opinions wanted.
=> Change chest and grinder recipes

scripts/Draconic-Evolution.zs
See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8154
=> Change PG recipe

scripts/Gregtech.zs
change Electri Tools to LV Tab (recipe change)
add Block Mold to molds molds molds quest
=> add new EBF Cobalt Quest

config/Betterloadingscreen/tips/en_US.txt
=> ✧･ﾟ: *✧･ﾟ♡*(ᵘʷᵘ)*♡･ﾟ✧*:･ﾟ✧

.github/workflows/stale.yml
Fix two stale bot conflicting with each other like shown in #8207.
=> Fix FixedInDev stale bot

scripts/Gregtech.zs
* https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/218
* https://github.com/GTNewHorizons/GT5-Unofficial/pull/716
=> remove gt recipes because they commented out in gt code

.github/ISSUE_TEMPLATE/000-report-crash.yml, .github/ISSUE_TEMPLATE/001-report-bug.yml
Helps to prevent confusions like in #8832
=> Clarify what does Multiplay LAN means

scripts/Logistics-Pipes.zs
As I have recently restarted, I think it'd be a good chance to rebalance LP recipes, since people are always saying stuff are too expensive.
=> LP recipe fixes and rebalances

config/JABBA.cfg
Fixes #8838 and depends on https://github.com/GTNewHorizons/Jabba/pull/11
=> Add nukes to blacklist

config/AdvancedSolarPanel_MTRecipes.cfg
This recipe fully bypasses any need for using the "plat" line of platline far earlier than would be appropriate.
(You're welcome, Colen)
=> Nerf MT Platinum recipe

config/Galacticraft/core.conf
Fixes #8835 by exposing the config option (default false)
=> Add HUD option to config, default as it is now

config/GTplusplus/GTplusplus.cfg, config/GregTech/GregTech.cfg
Added pollution config changes. Shouldn't be merged until https://github.com/GTNewHorizons/GTplusplus/pull/54 is merged
=> Pollution config

config/Betterloadingscreen/betterloadingscreen.cfg
(cherry picked from commit 4c7f1c62ac9911a9be9d69afc6162506379a97c6)
=> adjust tip position up a bit

README.md
=> Lvminer quest update

config/railcraft/blocks.cfg
in preparation for removing all recipes to speed up lead-time
=> disable rock crusher

scripts/Railcraft.zs
Now that the rock crusher recipes are gone, no need to remove in zs
=> crusher no crushing

config/berriespp.cfg
=> fish default preservation

config/GregTech/GregTech.cfg
https://github.com/GTNewHorizons/GT5-Unofficial/pull/798#event-5754657292 - no longer need these config options
=> remove TE config options

server.properties
Add modpack name and bump version in default server MOTD
=> Tweak server MOTD

scripts/Minecraft.zs, scripts/Railcraft.zs
* https://github.com/GTNewHorizons/Railcraft/pull/14
* https://github.com/GTNewHorizons/GT5-Unofficial/pull/834
* https://github.com/GTNewHorizons/bartworks/pull/77
=> Rc blastfurnace recipe remove

scripts/Harvestcraft.zs
=> Make Pam's foods shapeless

config/betterbuilderswands.cfg
No more exploit like this. Verified to work on my server.
=> Fix rubber tree rubber dupe

scripts/Iron-Chests-Minecarts.zs, scripts/Iron-Chests.zs
depends on https://github.com/GTNewHorizons/IronChestMinecarts/pull/3
=> remove removal

config/GregTech/GregTech.cfg
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9371
=> elevator rotating

config/OpenComputers.cfg
It does not affect server performance, and fluid hatches may be huge
(fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7919)
=> Increase transposer fluid transfer rate

scripts/Thaumic-Exploration-01.zs
https://github.com/GTNewHorizons/Thaumic_Exploration/pull/9 recipe should be reverted as it is fixed.
=> soul brazier unnerf

config/RandomThings.cfg, config/hodgepodge.cfg
Remove the crafting requirement for the extra cells oredict bus as it is bad and also no longer has a recipe
Also reformat two config files so comments fit on one screen
=> remove bus from quest

scripts/CoreMod.zs
* https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/267
=> remove recipe they now in code

config/GTNewHorizons/CustomFuels.xml
=> Add reminder that (for now) CDB can be used for T-2 rocket fuel

config/INpureProjects/custom_nei_filters/Tcon.js
NOTE: Requires https://github.com/GTNewHorizons/INpureCore/releases/tag/1.1.0-GTNH
=> Add TCon nbt culling

config/GTNewHorizons/CustomToolTips.xml
Same branch as earlier merged commit, only 1 file really changed.
=> Removed obsolete sleeping bag sleep height warning in quest book as well

config/Betterloadingscreen/tips/en_US.txt
=> Fix LewisSaber typo

config/Betterloadingscreen/tips/en_US.txt
=> New tip for loading menu

config/CodeChickenCore.cfg
Follows from https://github.com/GTNewHorizons/CodeChickenCore/pull/7 setting the default to `false`
=> update memory checker config

config/OpenComputers.cfg
@Florexiz did you forget to make a pr ?
=> Florexiz patch 1

scripts/Extra-Utilities.zs, scripts/GT++.zs
move Sunnarium to EV where it was before
=> Sunnarium duct tape

config/GTNewHorizons/CustomToolTips.xml
=> Cubic zirconia tooltip

scripts/Adv-Solar-Panel.zs, scripts/Gregtech.zs, scripts/IC2.zs
* https://github.com/GTNewHorizons/GT5-Unofficial/pull/956
* https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/291
* balance recipes a bit more to reduce recursive crafting a bit. tier up the circuits
* rebalance heat vents
* remove hand crafted Nukes
* remove MT Core
* change RE LV Battery recipe
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9791
=> Ic2 balance change

config/EnhancedLootBags/LootBags.xml
Add UV lootbag loot beyond a single diamond
=> Add UV lootbag loot

scripts/CoreMod.zs, scripts/Minecraft.zs
remove old Piston recipes
This helper items not longer needed
* https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/299
=> Piston assembler recipes

config/GalaxySpace/core.conf
Fixes #9850 and adds power factors for new space stations.
(I simulated these changes using the Java class below)
Previous values (1h):
```
Simulating with 10000 modules, a=1.0E-4, b=1.075 for 3600 seconds (10000 iterations)
Average remaining modules after 3600 seconds: 6176 / 10000 (61.76%)
```
Suggested change by @Phineasor (1h):
```
Simulating with 10000 modules, a=2.9E-8, b=1.075 for 3600 seconds (10000 iterations)
Average remaining modules after 3600 seconds: 10000 / 10000 (100.0%)
```
Changes made in this PR (1h, 24h)
```
Simulating with 10000 modules, a=5.0E-5, b=1.001 for 3600 seconds (10000 iterations)
Average remaining modules after 3600 seconds: 9979 / 10000 (99.79%)
```
```
Simulating with 10000 modules, a=5.0E-5, b=1.001 for 86400 seconds (10000 iterations)
Average remaining …
```
=> Dyson Swarm Balancing

config/forestry/backpacks.cfg
Added AE2's Skystone and Sky Stone Block to the Digger's Backpack :)
=> Skystone Update

scripts/Galacticraft.zs, scripts/IC2.zs
add fluid solidifer recipe for rubber boots
=> change arc lamp use Planet Glowstone instead of batteries

.gitignore, resources/compactkineticgenerators/lang/ru_RU.lang
Original commits: https://github.com/GTNewHorizons/CompactKineticGenerators/commit/2ba38dfb83cfd0221460403020ed41b017fd3ea9, https://github.com/GTNewHorizons/CompactKineticGenerators/commit/4d17deba87e39c749815fb5e1e06a4a668336d31
This allows us to use an unmodified version of Compact Kinetic Generators.
=> Add Russian translation for Compact Kinetic Generators

config/betterquesting.cfg
=> Disable view mode by default

scripts/Genetics.zs
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10127
=> Remove small dusts

config/betterbuilderswands.cfg
Partially address https://github.com/GTNewHorizons/Dupes-Exploits-GTNH/issues/49
=> Fix exploit with Primal Shroom

config/InGameInfo.xml
- Add missing closing bracket
- Make all lower-case words upper-case (all words are upper case now)
See: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/10293#issuecomment-1121344023
=> Fix oversights of #10293

.github/scripts/questbook-i18n.py, .github/workflows/questbook-i18n.yml
Automatic merge pr can also be added if required
=> Add Quest Book I18N workflow

scripts/Better-Questing.zs
- context: https://github.com/GTNewHorizons/BetterQuesting/pull/66
=> Add a recipe for `BetterQuesting: Object Observation Station`

config/ExtraUtilities.cfg, scripts/Extra-Utilities.zs
=> Reenable angel wings

config/TinkersConstruct.cfg
@glowredman why you dont make a pr ?
=> Blacklist IC² Personal Safe

scripts/Blood-Magic.zs
Alternative to the binding ritual for Bound Diamonds.
=> Add alternate Bound Diamond recipe

scripts/Extra-Utilities.zs
=> Use config 9 for making XU compressed blocks

scripts/AE2.zs
=> Change Cable Anchor to use bolts

scripts/Emt.zs
Script change for https://github.com/GTNewHorizons/Electro-Magic-Tools/pull/36
=> Update solar goggle research page

scripts/Gendustry.zs, scripts/Gregtech.zs
For https://github.com/GTNewHorizons/GT5-Unofficial/pull/1107
=> Move and change recipe for Industrial Apiary to gregtech version.

scripts/SGCraft.zs
=> Daily stargate nerf

scripts/Draconic-Evolution.zs
For https://github.com/GTNewHorizons/Electro-Magic-Tools/pull/17
=> Disable recipes that are now crafted in Draconic Evolution Fusion Crafter

scripts/Gregtech.zs
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10754
=> Use Silicon Solar Grade for Solar Panels

scripts/Natura.zs
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10737
=> Remove original recipe for Flint and Blaze

scripts/Thaumic-Bases-01-Main.zs
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10284
=> Add compressor recipe and remove original for Quicksilver Block

README.md
- Quick readme adjustment
- Endgame goals
=> Endgame goals rework

config/GregTech/GregTech.cfg
See https://github.com/GTNewHorizons/bartworks/pull/104
=> Update Ross128b Lava field config to match default

scripts/Chisel.zs
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10940
=> Fix basalt group conflict error

.github/workflows/stale.yml
It's never going to happen anyway... it's a graveyard polluting the active issues
=> Stop exempting Icebox

config/NEIAddons.cfg, config/beebetteratbees.cfg
Alternative to closed PR:https://github.com/GTNewHorizons/ForestryMC/pull/26
=> Allowed secret mutations to be shown in NEI

config/EnhancedLootBags/LootBags.xml
Swap IApiary in loot bag, old for new
=> Swap IApiary in loot bag, old for new

scripts/Galacticraft.zs
This reverts commit 3ff0d0be51de672de0419aa410e1d37ff5340546.
As per https://github.com/GTNewHorizons/Galacticraft/pull/53
=> Revert "Modify Fluid Manipulator (#10995)"

config/GTNewHorizons/CustomToolTips.xml
=> Fix railcraft tank tooltip

config/ae2fc.cfg
For proper working of moved recipes to coremod
=> Added AE2FC Config

config/kubatech/MobOverrides.cfg, config/kubatech/kubatech.cfg
https://github.com/GTNewHorizons/KubaTech/pull/8
=> Add overrides to Mob Handler

config/BloodMagic/meteors/CallistoMeteor.json
I made a whoopies a long while ago
=> Fixed platinum being listed twice

config/BloodMagic/meteors/LegacyMarsMeteor.json
=> Another duplicate ore fix

config/OpenComputers.cfg
=> Change default bufferChanges value

config/NEI/handlerordering.csv
- Push XU microblock to the end
- Require https://github.com/GTNewHorizons/NotEnoughItems/pull/290 to work
- Push questbook to later
=> Change handler order

config/forestry/backpacks.cfg
- Add GC/GS blocks to Digger
- Once added by https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/5260 but reverted by https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/commit/ff779af59268658ed8bdcc40d732f478d814d8ed
- Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5249
- Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10904
- Add vanilla and harvestcraft fishes to Hunter
- Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9565
- Add mob heads to Hunter
=> Backpack config update

scripts/CoreMod.zs
Since it seems to crash with values above 32
#11290
=> Reduce instability for deep dark

config/defaultserverlist.json
=> Zvezdolet Team - New Servers added

scripts/Logistics-Pipes.zs
turns out I committed an older version
=> Fix typo in LP recipe

config/Betterloadingscreen/tips/en_US.txt
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11656
=> Fix Water Garden tips

scripts/Logistics-Pipes.zs
mostly bugfixes. will push more changes as I progress
=> more lp changes

README.md
here is what it would look like:
=> added discord invite to the readme

scripts/Ender-IO.zs
(yes i hate scripts and will move this to code as soon as possible)
=> Oredict capacitors quick and dirty

config/InGameInfo.xml
=> use localtemperature

config/GregTech/GregTech.cfg
add ev and iv Gas Turbine in cfg
* https://github.com/GTNewHorizons/GT5-Unofficial/pull/1511
=> update Gregtech cfg

.github/scripts/questbook-i18n.py
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/actions/runs/3622552645/jobs/6107400903
=> Change en_US.lang path in QB script

scripts/Minecraft.zs
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11300
=> Fix Stained Clay using Clay instead of Hardened Clay

scripts/runic-tablet.zs
fix-> on UM servers Runed Tablet not spawn
=> craft Runed Tablet

scripts/Galacticraft.zs
Made it a gt large steel cell instead of the annoying empty canister
=> changed recipe following colen request

config/hodgepodge.cfg
All values are default values except `fixHudLightingGlitch` and `fixComponentsPoppingOff` due to them now being fixed by https://github.com/GTNewHorizons/MrTJPCore/pull/2 (***ONLY MERGE THIS ONCE THAT PR IS MERGED!***)
=> Update Hodgepodge config

config/EnhancedLootBags/LootBags.xml
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12285
=> Update deprecated gendustry IApiary upgrades

config/endercore/endercore.cfg
no more `Too expensive!`
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12326
=> unlock the level limitation when using an anvil

README.md
3000+ quests, Botania addition, and over 8 years now (Dec 2014)
=> Small updates to readme

scripts/Adv-Solar-Panel.zs, scripts/Gregtech.zs
Changes nano circuits to any UIV circuit
=> Change nano circuits to any UIV

config/gendustry/overrides/tuning.cfg
Fixes the Infcat blacklist.
currently it is not actually blacklisted.
=> Fix Infcat blacklist

scripts/Galacticraft.zs
=> Terraformer fix (EC2 cleanup)

.github/ISSUE_TEMPLATE/000-report-crash.yml, .github/ISSUE_TEMPLATE/001-report-bug.yml
=> add Java version to issue forms

scripts/Steves-Factory-Manager.zs
to merge with https://github.com/GTNewHorizons/Steve-s-Factory-Manager/pull/12
=> move certain recipe removals to the mod itself - Steve factory manager

scripts/SGCraft.zs
=> Update Stargate Recipes

config/GalaxySpace/core.conf
Restored old values except for dyson
=> Fix GS config

config/EnhancedLootBags/LootBags.xml
This fixes tooltip on loogbag NEI (https://github.com/GTNewHorizons/EnhancedLootBags/pull/8)
=> Give charged Draconic Bow from lootbag

scripts/Blood-Magic-Thaumcraft.zs
Title. This change wasn't very well-thought-out, but if the general concept of making these cheaper is fine and the change itself is not, I can put some more thought into it.
=> Make ritual stones slightly less CBT to make en masse

config/betterquesting/Readme.md
It is now also pinned in the quest-dev channel
=> Overhauled the BQ readme

scripts/Ender-IO.zs
recipes now in code 
* https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/542
=> remove Ender io recipes

config/Betterloadingscreen/tips/en_US.txt
Two silly tips and a proper one
=> 2+1 new tips

.github/scripts/questbook-i18n.py, .github/workflows/questbook-i18n.yml
The `en_US.lang` generated through this script is slightly different from the one generated using commands in the game (in the order of quests). Please refer to the actual generated file 
- generated file: [en_US.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11132492/en_US.txt)
- ref: GTNewHorizons/BetterQuesting/pull/89
=> Update questbook i18n workflow for new format

.github/workflows/stale.yml
c.f. https://github.com/actions/stale#close-issue-reason, https://github.blog/changelog/2022-05-19-the-new-github-issues-may-19th-update/
=> Close stale issues as `not_planned`

config/EnhancedLootBags/LootBags.xml
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13154
=> Fix Grandmaster unique lootbag

config/betterquesting/DefaultQuests/Quests/AppliedEnergisti-AAAAAAAAAAAAAAAAAAAAIw==/Tier1EssentiaStorage-AAAAAAAAAAAAAAAAAAAJwA==.json
Update and rename Tier1FluidStorag-AAAAAAAAAAAAAAAAAAAJwA==.json to Tier1EssentiaStorage-AAAAAAAAAAAAAAAAAAAJwA==.json
#13180
=> Fix Tier 1 Fluid Storage Quest Typo

config/GregTech/WorldGeneration.cfg
Make this config readable by
- fixing the indentation and
- Removing all properties with default value (was mostly like this before)
=> Fix indentation in GT WorldGeneration.cfg

config/betterquesting/Readme.md
=> Small update to questdev guide

config/betterquesting/Readme.md
Also add a warning about advanced values.
An error in editing advanced values can lead to a crash.
=> BQ Readme: add how to order quests

config/betterquesting/DefaultQuests/Quests/Tier05Steam-AAAAAAAAAAAAAAAAAAAAAg==/HowCanICarryAllT-AAAAAAAAAAAAAAAAAAACLg==.json
* Add a note on how to rename a backpack by using Shift+RMB.
* Decolor and reword the parts about their max number and autocollect.
=> Quest: HowCanICarryAll: add Shift+RMB and reformat

config/OpenComputers.cfg
https://github.com/GTNewHorizons/OpenComputers/pull/98
=> Change MFU range config value 6->16

config/GregTech/WorldGeneration.cfg
Based on this spreadsheet:
[GTNewHorizons.ods](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11470535/GTNewHorizons.ods)
=> Finish T9 Oregen

config/holoinventory.cfg
https://discord.com/channels/181078474394566657/522098956491030558/1107633085308211261
=> Blacklist conduit from HoloInventory

config/GregTech/GregTech.cfg
added support for botania glass in clean room. No more than 50% in structure.
configure in the code - https://github.com/GTNewHorizons/GT5-Unofficial/pull/1993
=> cleanroom -> botania glass

config/GregTech/GregTech.cfg
pretty self-explanatory:
goes together with code change here: https://github.com/GTNewHorizons/GT5-Unofficial/pull/2039
=> Remove hourglass from cleanroom

config/injectedDependencies.json
=> Fix missing thaumcraft aspects on various items

config/TooMuchLoot/loot/dungeonChest.xml
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13623
=> Change probability for copper in config/TooMuchLoot/loot/dungeonChest.xml to 90 from 9

config/gendustry/overrides/tuning.cfg
=> Add Kevlar bee to mutator blacklist

config/betterquesting/DefaultQuests/Quests/Tier4EV-AAAAAAAAAAAAAAAAAAAABg==/FiberReinforcedE-AAAAAAAAAAAAAAAAAAAGjA==.json
=> Update FiberReinforcedepoxid sheet quest

config/betterquesting/DefaultQuests/Quests/Tier5IV-AAAAAAAAAAAAAAAAAAAABw==/FinallyActualHaf-AAAAAAAAAAAAAAAAAAAL7A==.json, config/betterquesting/DefaultQuests/Quests/Tier5IV-AAAAAAAAAAAAAAAAAAAABw==/FinallySamarium-AAAAAAAAAAAAAAAAAAAMEA==.json, config/betterquesting/DefaultQuests/Quests/Tier5IV-AAAAAAAAAAAAAAAAAAAABw==/YouCantBeCerious-AAAAAAAAAAAAAAAAAAAMBw==.json, config/betterquesting/DefaultQuests/Quests/Tier5IV-AAAAAAAAAAAAAAAAAAAABw==/ZirconiumIngots-AAAAAAAAAAAAAAAAAAAL6g==.json
Changed a few of the Monazite quest descriptions to showcase some uses for the materials.
=> Monazite quest description changes

config/betterquesting/Readme.md
explains how to add links in the QB and what format to use.
=> Quest Guide - how to add links

config/GalacticraftAmunRa.cfg
The other changes are just changed defaults, Forge updates the comments to reflect that. Important are lines 49 and 52.
Follow-up of https://github.com/GTNewHorizons/amunra/pull/22.
=> Change Mothership engine fuel/coolant

config/Betterloadingscreen/betterloadingscreen.cfg
Enabling the Better Loading Screen play sound option per issue #13705
=> Update betterloadingscreen.cfg to enable modpack loaded sound

config/TooMuchLoot/loot/villageBlacksmith.xml
we have a quest for them, so they shouldnt be borderline impossible to obtain. (see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13742 for a data point)
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13742 and https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13575
=> flippers loot weight buff

config/GTNewHorizons/CustomToolTips.xml
Add Tooltip for Donation Coin
need 
* https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/657
=> Donation Coin Tooltip

config/betterquesting/DefaultQuests/Quests/MultiblockGoals-AAAAAAAAAAAAAAAAAAAADA==/AnUnexpectedBonu-AAAAAAAAAAAAAAAAAAAAUg==.json
Rather then say they're entirely useless.
=> Hint at getting industrial diamonds from blocks of charcoal

config/betterquesting/DefaultQuests/Quests/Tier5IV-AAAAAAAAAAAAAAAAAAAABw==/VenusTrip-AAAAAAAAAAAAAAAAAAAGtQ==.json
Added a warning to the Venus trip quest and prompted the player to check space race chapter.
=> Added warning to Venus trip

.gitignore, config/neiintegration.cfg
Another way to do what [this](https://github.com/GTNewHorizons/NEI-Integration/pull/7) was supposed to do, as per request from @glowredman.
=> Add NEI-Integration config

config/betterquesting/DefaultQuests/Quests/Tier1LV-AAAAAAAAAAAAAAAAAAAAAw==/HowtoGetSodiuman-AAAAAAAAAAAAAAAAAAACbg==.json
resolves https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14025
=> adjust how to get lithium quest

config/betterquesting/DefaultQuests/Quests/AppliedEnergisti-AAAAAAAAAAAAAAAAAAAAIw==/AESpatialStorage-AAAAAAAAAAAAAAAAAAAJyQ==.json
=> fix typo in ae2 spacial processor quest

config/betterquesting/DefaultQuests/Quests/AdeptThaumaturgy-AAAAAAAAAAAAAAAAAAAAFw==/WhoNeedsFriends-AAAAAAAAAAAAAAAAAAAI3A==.json
I think that should be an Ordo here.
=> Fix duplicated items in quest rewards

config/GalacticraftAmunRa.cfg
Follow up to https://github.com/GTNewHorizons/amunra/pull/27
Value was discussed here: https://discord.com/channels/181078474394566657/939305179524792340/1136735266166542508
=> Set Mothership Mass Override to 1500kg

config/betterquesting/DefaultQuests/Quests/MultiblockGoals-AAAAAAAAAAAAAAAAAAAADA==/TimetoDrillforOi-AAAAAAAAAAAAAAAAAAAC_Q==.json
=> Skip oil baron quest as a reward for completing Time to drill for oil quest

config/betterquesting/DefaultQuests/Quests/GT-AAAAAAAAAAAAAAAAAAAAEQ==/HulkSmash-AAAAAAAAAAAAAAAAAAAFjQ==.json, config/betterquesting/DefaultQuests/Quests/Tier3HV-AAAAAAAAAAAAAAAAAAAABQ==/Rutile-AAAAAAAAAAAAAAAAAAAD9A==.json
- removed mention of maceration stack output bonus. looking through git history apparently alk 'temporarily' removed that 4 years ago. By now its all cleaned up without a trace in the code left.
- fixed rutile amount in quest to fit the actual recipe.
=> 2 small quest fixes

config/betterquesting/DefaultQuests/Quests/SpaceRace-AAAAAAAAAAAAAAAAAAAAIg==/SaltWaterandChlo-AAAAAAAAAAAAAAAAAAAGzw==.json
=> Change centrifuge to electrolyze in salt water on mars quest

config/EnhancedLootBags/LootBags.xml
=> crop harvester spawns to often

config/betterquesting/DefaultQuests/Quests/MultipleQuestLine/DoubletheFun-AAAAAAAAAAAAAAAAAAAHaw==.json
=> Double the fun quest change

server.properties
you cant keep forgetting :grief:
=> change motd version

config/betterquesting/DefaultQuests/Quests/MultipleQuestLine/NanoForgeTier2-AAAAAAAAAAAAAAAAAAAM0A==.json
=> :nerd: spelling mistake

config/GTNewHorizons/CustomFuels.xml
Make the pine cones from BiomesOPlenty burnable
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14599
=> pine cones as fuel

config/hodgepodge.cfg
update hodgepodge cfg
set cells container in GTNH to true
=> Update defaults for hodgepodge.cfg

config/betterquesting/DefaultQuests/Quests/EndgameGoals-AAAAAAAAAAAAAAAAAAAAHQ==/AwakenedCore-AAAAAAAAAAAAAAAAAAAB0w==.json, config/betterquesting/DefaultQuests/Quests/EndgameGoals-AAAAAAAAAAAAAAAAAAAAHQ==/ChaoticCore-AAAAAAAAAAAAAAAAAAAB0Q==.json, config/betterquesting/DefaultQuests/Quests/Tier9UHV-AAAAAAAAAAAAAAAAAAAALg==/DraconicCore-AAAAAAAAAAAAAAAAAAAB0A==.json, config/betterquesting/DefaultQuests/Quests/Tier9UHV-AAAAAAAAAAAAAAAAAAAALg==/WyvernCore-AAAAAAAAAAAAAAAAAAABzg==.json
=> Fix quests after DEFC movement

config/InGameInfo.xml
was showing 0 as white and 60 as yellow
=> Change default IGI xml to check for greater than and equal fps

config/bartworks.cfg
Updates config to match https://github.com/GTNewHorizons/bartworks/pull/371
=> remove unused config lines

config/Betterloadingscreen/tips/en_US.txt
Also correct Journeymap, remove Natura clouds, normalize wiki address, and add f9 hint
=> update hints to remove illegal voltage tier

config/betterquesting/DefaultQuests/Quests/Tier2MV-AAAAAAAAAAAAAAAAAAAABA==/SuperTankI-AAAAAAAAAAAAAAAAAAADsA==.json
Updates quest text to reflect changes in https://github.com/GTNewHorizons/GT5-Unofficial/pull/2392#event-11156843888
=> Update quest to give a hint that quantum tanks will be better

config/betterquesting/DefaultQuests/Quests/AppliedEnergisti-AAAAAAAAAAAAAAAAAAAAIw==/1024kEssentiaCom--IWmYEgKSGi0M7rtP59zaw==.json, config/betterquesting/DefaultQuests/Quests/AppliedEnergisti-AAAAAAAAAAAAAAAAAAAAIw==/1024kEssentiaSto-tUJaqz9uSwajByFi4gNHzQ==.json, config/betterquesting/DefaultQuests/Quests/AppliedEnergisti-AAAAAAAAAAAAAAAAAAAAIw==/16384kEssentiaCo-JejpWZ7ATZq-0uomP4c7UA==.json, config/betterquesting/DefaultQuests/Quests/AppliedEnergisti-AAAAAAAAAAAAAAAAAAAAIw==/16384kEssentiaSt-iwN50p7pSyyCHDkM-O-D7w==.json, config/betterquesting/DefaultQuests/Quests/AppliedEnergisti-AAAAAAAAAAAAAAAAAAAAIw==/256kEssentiaComp-Wh0yn2MOQhS-X_8NiPiZJw==.json, config/betterquesting/DefaultQuests/Quests/AppliedEnergisti-AAAAAAAAAAAAAAAAAAAAIw==/256kEssentiaStor-s2TL3i06Tb2WvPvdt1utyg==.json, config/betterquesting/DefaultQuests/Quests/AppliedEnergisti-AAAAAAAAAAAAAAAAAAAAIw==/4096kEssentiaCom-QHyLarPvSnCb30EbaBQdaw==.json, config/betterquesting/DefaultQuests/Quests/AppliedEnergisti-AAAAAAAAAAAAAAAAAAAAIw==/4096kEssentiaSto-G5g_5_24RS6sqhmjFEbf8A==.json, config/betterquesting/DefaultQuests/Quests/AppliedEnergisti-AAAAAAAAAAAAAAAAAAAAIw==/64kComponent-AAAAAAAAAAAAAAAAAAAE6A==.json, config/betterquesting/DefaultQuests/Quests/AppliedEnergisti-AAAAAAAAAAAAAAAAAAAAIw==/AndAnotherDigita-O0tN--UDTlCbt5ufLodVqA==.json, config/betterquesting/DefaultQuests/Quests/AppliedEnergisti-AAAAAAAAAAAAAAAAAAAAIw==/EssentiaQuantumS-y9mYyyz4Qg6iGOYILdKA1A==.json, config/betterquesting/DefaultQuests/Quests/AppliedEnergisti-AAAAAAAAAAAAAAAAAAAAIw==/NeedMoreInformat-5ObFHI5BQ5Oxv0yca7morA==.json, config/betterquesting/DefaultQuests/Quests/AppliedEnergisti-AAAAAAAAAAAAAAAAAAAAIw==/ToolsoftheTrade-AAAAAAAAAAAAAAAAAAAJ6Q==.json
and new network tool
add legend mention before into new quest.
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/432#issuecomment-1828373980
=> Add new essentia cell component and cells

config/betterquesting/DefaultQuests/Quests/AppliedEnergisti-AAAAAAAAAAAAAAAAAAAAIw==/ThaumometricEsse-muXTNgpiRE6RZI_x7GW62w==.json
=> change quest's desc

config/txloader/load/witchery/lang/en_US.lang
Partial fix for https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14161
=> add some witchery names

config/betterquesting/DefaultQuests/Quests/MultipleQuestLine/MakingaRapier-AAAAAAAAAAAAAAAAAAALUQ==.json
One possible fix for issue #15322.
=> Remove references to the Lich fight from the Making a Rapier quest

config/defaultserverlist.json, servers.json
Due to violations of Minecraft TOS
closes #14927
=> Removal of Craftersland

config/Betterloadingscreen/tips/en_US.txt
Pointless pedantry ftw.
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15395
=> Fix parentheses

config/AWWayofTime.cfg
fixes https://github.com/GTNewHorizons/Dupes-Exploits-GTNH/issues/126
=> disable ritual rhythm of the beating anvil

README.md
Needed for some open source licenses
=> Yourkit Endorsement

config/Betterloadingscreen/tips/en_US.txt
https://discord.com/channels/181078474394566657/181078474394566657/1212541341708587008
Context
=> Add new tip

config/GTNewHorizons/CustomToolTips.xml
* https://github.com/GTNewHorizons/ironchest/pull/16/
=> add Dark Steel chest info

config/CustomMainMenu/mainmenu.json, config/CustomMainMenu/mainmenu_auto.json, config/CustomMainMenu/mainmenu_large.json, config/CustomMainMenu/mainmenu_normal.json, config/CustomMainMenu/mainmenu_small.json, config/txloader/load/custommainmenu/lang/en_US.lang
https://github.com/GTNewHorizons/GTNH-Translations/issues/8
=> Allow translating main menu

config/betterquesting/DefaultQuests/Quests/MultiblockGoals-AAAAAAAAAAAAAAAAAAAADA==/NeutronSensor-AAAAAAAAAAAAAAAAAAALeQ==.json
Updates the Neutron Sensor quest according to the UI change in https://github.com/GTNewHorizons/GoodGenerator/pull/242.
=> Neutron Sensor quest fix

config/GTNewHorizons/CustomToolTips.xml
Still waiting on a Thaumic Boots Patch for 1 pair of boots.
And fixing this to actually work, Wildcard tooltips don't work here. - Fixed
#15904
=> Added recharge tooltips with tiers

config/BloodMagic/meteors/YourResourcesHandItOver.json
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15925.
Discussed balancing concerns with @ScriptedPiky , @Steelux8 , and others in #meta-dev, people feel positive about this.
=> Change duplicate Europium ore to Neutronium.

.github/scripts/questbook-i18n.py, config/txloader/load/betterquesting/lang/template.lang
Update quest i18n script to handle new quest line format from:
*   https://github.com/GTNewHorizons/BetterQuesting/pull/133
This PR should not be merged until after that PR is merged.
The `template.lang` got shuffled around quite a bit because I changed the sort order in the linked PR, but it should hopefully be easier to keep the sort order consistent in the future, as now it's just string ordering based on encoded UUID. I checked that the line counts are the same before and after this PR, as a sanity check.
---
Note to self: also need to update ordering of contents in the various other `.lang` files under `txloader/`
=> Update quest i18n script

config/forestry/backpacks.cfg
depends on https://github.com/GTNewHorizons/ForestryMC/pull/71
=> Add coins to the backpack

config/betterquesting/DefaultQuests/Quests/NoQuestLine/TriggerEpoxidSki-AAAAAAAAAAAAAAAAAAAL2w==.json, config/betterquesting/DefaultQuests/Quests/NoQuestLine/TriggerPBISkip-AAAAAAAAAAAAAAAAAAALVw==.json, config/betterquesting/DefaultQuests/Quests/NoQuestLine/TriggerPTFESkip-AAAAAAAAAAAAAAAAAAAL2Q==.json, config/betterquesting/DefaultQuests/Quests/NoQuestLine/TriggerPlatlineI-AAAAAAAAAAAAAAAAAAALWw==.json, config/betterquesting/DefaultQuests/Quests/NoQuestLine/TriggerPlatlineO-AAAAAAAAAAAAAAAAAAALXA==.json, config/betterquesting/DefaultQuests/Quests/NoQuestLine/TriggerPlatlineP-AAAAAAAAAAAAAAAAAAALVg==.json, config/betterquesting/DefaultQuests/Quests/NoQuestLine/TriggerPlatlineP-AAAAAAAAAAAAAAAAAAALWA==.json, config/betterquesting/DefaultQuests/Quests/NoQuestLine/TriggerPlatlineR-AAAAAAAAAAAAAAAAAAALWQ==.json, config/betterquesting/DefaultQuests/Quests/NoQuestLine/TriggerPlatlineR-AAAAAAAAAAAAAAAAAAALWg==.json, config/betterquesting/DefaultQuests/Quests/NoQuestLine/TriggerPolystyre-AAAAAAAAAAAAAAAAAAAL2g==.json, config/betterquesting/DefaultQuests/Quests/NoQuestLine/TriggerSiliconeR-AAAAAAAAAAAAAAAAAAAL2A==.json, config/betterquesting/DefaultQuests/Quests/NoQuestLine/TriggerStyreneBu-cQkx83QYT4m3mwovgZIKvA==.json
Updated a bunch of trigger quests to make sure they trigger the entire chemical line that they come from. Rather then just the end of the line.
=> Trigger quests edits

config/betterquesting/Readme.md
Requested by @chochem. The readme now explains how to use the formatting tags and how they set colors on their own.
=> Update BetterQuesting Readme with New Formatting Tag Information

config/EnhancedLootBags/LootBags.xml
=> exchange Ingot crates with ingots

config/betterquesting/Readme.md
Adds troubleshooting section to the quest making guide with first entry plus two minor changes.
=> Small update to quest making guide

config/forestry/backpacks.cfg
=> Add missed Raw Nether Quartz ore

config/betterquesting/DefaultQuests/Quests/Tier05Steam-AAAAAAAAAAAAAAAAAAAAAg==/RepairingYourHaz-AAAAAAAAAAAAAAAAAAAHYA==.json
Fixes a typo in the quest for the hazmat suit.
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16658#issuecomment-2211812731
=> Fixes a typo in the Hazmat Suit Quest

config/betterquesting/DefaultQuests/Quests/Tier0StoneAge-AAAAAAAAAAAAAAAAAAAAAQ==/RedstoneEarlyGam-AAAAAAAAAAAAAAAAAAACFw==.json
Updates the instructions on how to process redstone ore since you will no longer place it in-world as you dont get the block anymore but instead raw ore
=> Update the redstone processing quest

config/betterquesting/DefaultQuests/Quests/Tier0StoneAge-AAAAAAAAAAAAAAAAAAAAAQ==/RedstoneEarlyGam-AAAAAAAAAAAAAAAAAAACFw==.json
See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/16716#issuecomment-2219264545
=> Add Info on taking the hammer with you directly

config/betterquesting/DefaultQuests/Quests/GT-AAAAAAAAAAAAAAAAAAAAEQ==/MABS-AAAAAAAAAAAAAAAAAAAM1Q==.json
Followup to https://github.com/GTNewHorizons/GT5-Unofficial/pull/2673 (and thus requires that PR)
=> MABS bonuses quest adjustment

config/betterquesting/DefaultQuests/Quests/EndgameGoals-AAAAAAAAAAAAAAAAAAAAHQ==/AnEyeattheEndofT-kazCPEWoSmiZhR4bkHlEBQ==.json
- Added a small summary of the multiblock
- Added 1 of each casing to the retrieval task
=> Added more info to EoH quest

config/GregTech/WorldGeneration.cfg
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16746
See also:
- https://github.com/GTNewHorizons/GTNEIOrePlugin/pull/40
- https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/894
=> Remove Space from "Mehen Belt"

config/betterquesting/DefaultQuests/Quests/Tier10UEV-D_aFb1hFQH2PDkN0_KvAEQ==/WellThisLooksShi-AAAAAAAAAAAAAAAAAAAKHA==.json
fixed outdated eternal singularity quest
=> Quest update

config/betterquesting/DefaultQuests/Quests/GT-AAAAAAAAAAAAAAAAAAAAEQ==/Tier2Transformin-AAAAAAAAAAAAAAAAAAAM2g==.json, config/betterquesting/DefaultQuests/Quests/GT-AAAAAAAAAAAAAAAAAAAAEQ==/Tier3Focusing-AAAAAAAAAAAAAAAAAAAM2w==.json, config/betterquesting/DefaultQuests/Quests/GT-AAAAAAAAAAAAAAAAAAAAEQ==/Tier4Transformin-AAAAAAAAAAAAAAAAAAAM3A==.json
Fixed these in the main quest a while ago, but forgot to edit the upgraded casing quests in GT++
=> QFT casing amount

config/betterquesting/DefaultQuests/Quests/AppliedEnergisti-AAAAAAAAAAAAAAAAAAAAIw==/KeepingYourNetwo-AAAAAAAAAAAAAAAAAAAFCw==.json, config/betterquesting/DefaultQuests/Quests/Tier3HV-AAAAAAAAAAAAAAAAAAAABQ==/LVMicroprocessor-AAAAAAAAAAAAAAAAAAAE0w==.json
Fixes
- AE2 energy cell having wrong amount in quest description (#16816)
- typo in microprocessor quest (https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16658#issuecomment-2243604001)
=> More random quest changes

config/betterquesting/DefaultQuests/Quests/Tier5IV-AAAAAAAAAAAAAAAAAAAABw==/Repreciwhat-AAAAAAAAAAAAAAAAAAAJBg==.json
This PR just fixes a small typo in the "Repreci... what?" quest in the IV questline
=> Fix typo in "Repreci... what?" quest

config/betterquesting/DefaultQuests/QuestLines/Tier10UEV-D_aFb1hFQH2PDkN0_KvAEQ==/QuestLine.json
For us that play with visibility off.
=> Hide UEV Questline until it is unlocked

config/GregTech/GregTech.cfg
to be merged with https://github.com/GTNewHorizons/GT5-Unofficial/pull/2741
=> Change bounds of natural gas

.gitignore, config/NEI/collapsibleitems.cfg
To be merged after https://github.com/GTNewHorizons/NotEnoughItems/pull/506 is merged
=> Add pack specific collapsibleitems.cfg for NEI

config/gendustry/overrides/tuning.cfg
This is in reference to this PR https://github.com/GTNewHorizons/GT5-Unofficial/pull/2818
=> Added the europium bee and americium bee to the mutatron blacklist

config/NEI/collapsibleitems.cfg
+ All Tinkers Tools what was shown after https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/16907
=> CollapsibleItems: More Groups

config/ThaumcraftMobAspects/BiomesOPlenty.cfg, config/ThaumcraftMobAspects/SpecialMobs.cfg, config/ThaumcraftMobAspects/enderzoo.cfg, config/ThaumcraftMobAspects/witchery.cfg
This PR includes the following updates:
- Reworked and completed the aspects for mobs from SpecialMobs.
- Added aspects for the Witchery Hellhound.
- Added aspects for mobs from BiomesOPlenty.
- Added aspects for mobs from Ender Zoo.
Related PR for the mod generating these configs: https://github.com/GTNewHorizons/ThaumcraftMobAspects/pull/3
=> Added TC Aspects for more mobs

.gitignore, config/NEI/collapsibleitems.cfg, config/NEI/hiddenitems.cfg
related PR: https://github.com/GTNewHorizons/NotEnoughItems/pull/519
=> NEI: Add hiddenitems.cfg

config/betterquesting/DefaultQuests/Quests/GettingAround-bAal8kZ3R8eRTwaHgbYkKA==/Betterbootswitha-AAAAAAAAAAAAAAAAAAAI1A==.json, config/betterquesting/DefaultQuests/Quests/GettingAround-bAal8kZ3R8eRTwaHgbYkKA==/Walkalloveryou-AAAAAAAAAAAAAAAAAAAI1Q==.json, config/betterquesting/DefaultQuests/Quests/GettingAround-bAal8kZ3R8eRTwaHgbYkKA==/Walkingacrossthe-AAAAAAAAAAAAAAAAAAAI1g==.json
Up until now most info was only shared in #Upcoming Features which led so some confusion for some players. This quest now explains the added features and how to config them.
Also some wording and capitalization for the other thaumic boots quests.
=> Add info for config of Thaum Boots

config/betterquesting/DefaultQuests/Quests/NoQuestLine/TriggerNetherSki-qFco17HGS0SxmpVn-uWJZQ==.json
=> small fix for new skip

config/GregTech/MachineStats.cfg
=> Fix the Magic E Absorber Exploding

config/betterquesting/DefaultQuests/Quests/EndgameGoals-AAAAAAAAAAAAAAAAAAAAHQ==/StargateCommand-AAAAAAAAAAAAAAAAAAAKJQ==.json, config/betterquesting/DefaultQuests/Quests/EndgameGoals-AAAAAAAAAAAAAAAAAAAAHQ==/WhatHow-AAAAAAAAAAAAAAAAAAAKJg==.json, config/betterquesting/DefaultQuests/Quests/Tier10UEV-D_aFb1hFQH2PDkN0_KvAEQ==/DreamsofRainbowS-H3Tvy4ZKSyiQGT16Og90bA==.json, config/betterquesting/DefaultQuests/Quests/Tier12UMV-l37V2WvbSHGZQ5oMgAfBuw==/StarsSoManyStars-QO1gudFvTtKgWe9942dW3Q==.json, config/betterquesting/DefaultQuests/Quests/Tier9UHV-AAAAAAAAAAAAAAAAAAAALg==/ABlasttothePast-_vOu6ZYdRiOqLN_5-uBU_A==.json
Modpack PR for https://github.com/GTNewHorizons/GT5-Unofficial/pull/3105
=> 2.7 Stargate

config/GregTech/Client.cfg, config/GregTech/GregTech.cfg, config/GregTech/MachineStats.cfg, config/GregTech/Other.cfg, config/GregTech/OverpoweredStuff.cfg, config/GregTech/WorldGeneration.cfg
to match https://github.com/GTNewHorizons/GT5-Unofficial/pull/3152
=> update GT configs

config/ggfab.cfg
to merge once https://github.com/GTNewHorizons/GT5-Unofficial/pull/3231 is merged
=> update ggfab config

config/betterquesting/DefaultQuests/Quests/SpaceRace-AAAAAAAAAAAAAAAAAAAAIg==/Grapple-AAAAAAAAAAAAAAAAAAAFwA==.json
=> fix grapple quest

config/betterquesting/DefaultQuests/Quests/Tier05Steam-AAAAAAAAAAAAAAAAAAAAAg==/ToolForge-AAAAAAAAAAAAAAAAAAAC5Q==.json
It appears i forgot to change it to AND from OR when doing https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/17153 
This PR fixes that
=> Change tinker quest to AND

config/betterquesting/DefaultQuests/Quests/Tier5IV-AAAAAAAAAAAAAAAAAAAABw==/ASmallRewardTheI-n22vWzZHSu6Gn63EBV1FUw==.json
Just a small quest in the IV section to breadcrumb players into my stupid spray can.
=> Adds infinite spray can quest

config/TooMuchLoot/loot/pyramidJungleDispenser.xml, config/TooMuchLoot/loot/strongholdCorridor.xml
fixes https://discord.com/channels/181078474394566657/181078474394566657/1288632869903663106
=> remove gt arrows from lootpools

config/GregTech/MachineStats.cfg
was broken accidentally in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/17129
fixes https://discord.com/channels/181078474394566657/522098956491030558/1296539553263255603
=> fix uua speed bonus

config/coretweaks.cfg
Add the config default of coretweaks.cfg and disable the crash_handler since we already have better crashes
=> Add coretweaks.cfg

config/betterquesting/DefaultQuests/Quests/Tier05Steam-AAAAAAAAAAAAAAAAAAAAAg==/Theonebooktorule-XuZpnhWZRou46kensglZ6g==.json
was a nice idea with that reward but that very much does not work as ids arent fixed between different saves.
Fixes: 
and yes it could actually generate random powerful usable items if you were lucky XD
=> Fix akashic tome quest

config/forestry/backpacks.cfg
=> Add raw ore nether star

config/betterquesting/DefaultQuests/QuestLines/SFMandComputers-AAAAAAAAAAAAAAAAAAAAHw==/AllYourCardAreBe-AAAAAAAAAAAAAAAAAAAG1Q==.json, config/betterquesting/DefaultQuests/QuestLines/SFMandComputers-AAAAAAAAAAAAAAAAAAAAHw==/BIOS-AAAAAAAAAAAAAAAAAAAG3g==.json, config/betterquesting/DefaultQuests/Quests/SFMandComputers-AAAAAAAAAAAAAAAAAAAAHw==/Itseverytimethes-5mcwk7dYSBydA9KRHbW59A==.json, config/opencomputers/gtnh.recipes
2nd attempt for the broken OC Transistor Achievement.
Related current recipe PR: https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/1049
Old/Original PRs: https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/1028 and https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/17604
=> Oc transistor achievement fix2

config/betterquesting/DefaultQuests/Quests/Tier7ZPM-AAAAAAAAAAAAAAAAAAAAHg==/RecycleTrinium-AAAAAAAAAAAAAAAAAAALgg==.json
Small quest text fix because that recipe hasn't existed for ~20 months
=> Remove mention of Trinium Sulphate electrolysis

config/NEI/collapsibleitems.cfg
=> NEI: group Superdance Plate

config/GregTech/Pollution.cfg
should fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17989
=> fix pollution config

config/GTNewHorizons/CustomToolTips.xml
=> Graviton shard lore+production method tooltip

config/forestry/backpacks.cfg
Add the differents forms of Roasted Iron to the miners backpack config
Fix GTNewHorizons/GT-New-Horizons-Modpack#17301
=> Add Roasted Iron to Miner backpack

config/gtnhintergalactic.cfg
https://github.com/GTNewHorizons/GTNH-Intergalactic/pull/83
=> Add default gtnh intergalactic config

config/GTNewHorizons/CustomToolTips.xml
it's not ideal, but at least it works for base configurations.
Requires https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/1093
=> tooltips for preconfigured storage buses

config/InGameInfoXML/InGameInfo.xml
=> Round Fahrenheit biome temperature in IGI

config/TravellersGear.cfg
Felt it needed a speedup after working on https://github.com/GTNewHorizons/TravellersGearNeo/pull/3
=> Increase Traveller's Gear ability switching radial menu speed

config/betterquesting/DefaultQuests/Quests/BeeBreeding-AAAAAAAAAAAAAAAAAAAAEw==/Arsenic-AAAAAAAAAAAAAAAAAAAIzg==.json, config/betterquesting/DefaultQuests/Quests/BeeBreeding-AAAAAAAAAAAAAAAAAAAAEw==/EnderShard-AAAAAAAAAAAAAAAAAAAM4Q==.json, config/betterquesting/DefaultQuests/Quests/BeeBreeding-AAAAAAAAAAAAAAAAAAAAEw==/Ethereal-AAAAAAAAAAAAAAAAAAAIqw==.json, config/betterquesting/DefaultQuests/Quests/BeeBreeding-AAAAAAAAAAAAAAAAAAAAEw==/Fluix-AAAAAAAAAAAAAAAAAAAIjg==.json, config/betterquesting/DefaultQuests/Quests/BeeBreeding-AAAAAAAAAAAAAAAAAAAAEw==/Ghastly-AAAAAAAAAAAAAAAAAAAI4w==.json, config/betterquesting/DefaultQuests/Quests/BeeBreeding-AAAAAAAAAAAAAAAAAAAAEw==/Iron-AAAAAAAAAAAAAAAAAAAIkQ==.json, config/betterquesting/DefaultQuests/Quests/BeeBreeding-AAAAAAAAAAAAAAAAAAAAEw==/Nethershard-AAAAAAAAAAAAAAAAAAAM4g==.json, config/betterquesting/DefaultQuests/Quests/BeeBreeding-AAAAAAAAAAAAAAAAAAAAEw==/Peat-AAAAAAAAAAAAAAAAAAAIeQ==.json, config/betterquesting/DefaultQuests/Quests/BeeBreeding-AAAAAAAAAAAAAAAAAAAAEw==/Phantasmal-AAAAAAAAAAAAAAAAAAAIjA==.json, config/betterquesting/DefaultQuests/Quests/BeeBreeding-AAAAAAAAAAAAAAAAAAAAEw==/SalisMundus-AAAAAAAAAAAAAAAAAAAIwg==.json, config/betterquesting/DefaultQuests/Quests/BeeBreeding-AAAAAAAAAAAAAAAAAAAAEw==/ThaumicShards-AAAAAAAAAAAAAAAAAAAIwQ==.json, config/betterquesting/DefaultQuests/Quests/BeeBreeding-AAAAAAAAAAAAAAAAAAAAEw==/VibrantAlloy-AAAAAAAAAAAAAAAAAAAIig==.json, config/betterquesting/DefaultQuests/Quests/Tier2MV-AAAAAAAAAAAAAAAAAAAABA==/AceticAcid-AAAAAAAAAAAAAAAAAAADVA==.json, config/betterquesting/DefaultQuests/Quests/Tier2MV-AAAAAAAAAAAAAAAAAAAABA==/Ethenone-AAAAAAAAAAAAAAAAAAADUg==.json, config/betterquesting/DefaultQuests/Quests/Tier3HV-AAAAAAAAAAAAAAAAAAAABQ==/Polytetrafluoroe-AAAAAAAAAAAAAAAAAAAHFg==.json
just a small round:
- add advice for perfect ratio PTFE recipe, fixes https://discord.com/channels/181078474394566657/949447391587733504/1313188719146041375
- improve ethenone quests from https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17882
- fix various bee rewards (add new ones, downtiers, uptiers), fixes https://discord.com/channels/181078474394566657/949447391587733504/1311722768425025596
=> Quest Fixes - 2 December

config/NEI/hiddenitems.cfg
| before | after |
|-|-|
| ![image](https://github.com/user-attachments/assets/23d8c3cc-e3c5-4ddf-b24c-a3b726321339) | ![image](https://github.com/user-attachments/assets/97455f2b-287a-4877-9036-d95dfd4027ba) |
The recipes still work
=> Hide Genetics Serum

config/TooMuchLoot/loot/strongholdCrossing.xml
gt crates are gone. I replaced them by some ingots but I don't think it really matters.
fixes https://discord.com/channels/181078474394566657/522098956491030558/1314659522278719538
=> remove crates from strongholds

config/defaultserverlist.json, servers.json
Selling kits and everyone on the server get the benefit are not against Eula so far ik.
=> add MY FTB server back to list

config/betterquesting/DefaultQuests/Quests/AndSoItBegins-AAAAAAAAAAAAAAAAAAAAAA==/MoreUsefulIC2Cro-AAAAAAAAAAAAAAAAAAAGRw==.json, config/betterquesting/DefaultQuests/Quests/AndSoItBegins-AAAAAAAAAAAAAAAAAAAAAA==/Tools-AAAAAAAAAAAAAAAAAAAABQ==.json, config/betterquesting/DefaultQuests/Quests/MultipleQuestLine/SharpnessOver5-AAAAAAAAAAAAAAAAAAAACw==.json
Should be okay, but I seldom make quest changes :P
=> Remove tools quest update

config/etfuturum/blocksitems.cfg, config/etfuturum/entities.cfg, config/etfuturum/experiments.cfg, config/etfuturum/functions.cfg, config/etfuturum/mixins.cfg, config/etfuturum/tweaks.cfg, config/etfuturum/world.cfg
update to EFR 2.6.2 with a bit more work on some settings.
Including disabled PlayersSleepingPecentageGamerule as that is planned for SU, disabled composter as we have forestry for a more advanced approach (though we might be able to change the functionality to something different that suits us?), disable basalt as we already have that, disable netherite until there is a plan of what to do with it, disable bamboo gen as we already a better variant of that.
=> EFR update

config/GalaxySpace/core.conf, config/gtnhintergalactic.cfg
Part of https://github.com/GTNewHorizons/GTNH-Intergalactic/pull/89
=> Migrate dyson configs from galaxyspace to intergalactic

config/defaultserverlist.json, servers.json
https://cdn.discordapp.com/attachments/1016330270619734077/1321484846492811264/Screenshot_4928.png?ex=676d682b&is=676c16ab&hm=11cac3bbab47c031829b15ff567cae902fa673ebf008318bf0d06f9430947d2e&
=> Add Apoc back

README.md
Add APOC to server list on readme.md
=> Add AGN to Readme

config/defaultserverlist.json, servers.json
=>  Add "EpochCraft GTNH [EU]": "alpha.epochcraft.space",

.github/ISSUE_TEMPLATE/000-report-crash.yml, .github/ISSUE_TEMPLATE/001-report-bug.yml, .github/ISSUE_TEMPLATE/002-suggest-a-change.yml, .github/ISSUE_TEMPLATE/003-request-new-feature.yml, .github/ISSUE_TEMPLATE/004-suggest-a-new-mod.yml, .github/ISSUE_TEMPLATE/999-create-reminder.yml
Remove discord discriminators as they do no longer exist
=> Remove discord discriminator from templates

config/betterquesting/DefaultQuests/Quests/Tier0StoneAge-AAAAAAAAAAAAAAAAAAAAAQ==/GettingCharcoal-AAAAAAAAAAAAAAAAAAAAGA==.json
Not needed since https://github.com/GTNewHorizons/Railcraft/pull/65
=> Remove warning about fixed WAILA bug

config/ExtraBees.cfg, config/ExtraTrees.cfg
Part of https://github.com/GTNewHorizons/Binnie/pull/53
Old configs were not on this repo so nothing to remove
=> Add new configs for Binnie

config/etfuturum/functions.cfg
two more small efr config changes. In particular fixes https://discord.com/channels/181078474394566657/522098956491030558/1325114555889876992
=> two more small EFR config changes

config/GTNewHorizons/CustomToolTips.xml
config repo part of https://github.com/GTNewHorizons/GT5-Unofficial/pull/3785
=> remove no longer required extra tooltips

config/forestry/backpacks.cfg
=> Add roasted nickel to forestry backpack

config/betterquesting/DefaultQuests/Quests/HowtoGeneratePow-AAAAAAAAAAAAAAAAAAAACQ==/PoweroftheSun1x1-AAAAAAAAAAAAAAAAAAAD7A==.json, config/betterquesting/DefaultQuests/Quests/HowtoGeneratePow-AAAAAAAAAAAAAAAAAAAACQ==/PoweroftheSun1x1-AAAAAAAAAAAAAAAAAAAD7w==.json, config/betterquesting/DefaultQuests/Quests/HowtoGeneratePow-AAAAAAAAAAAAAAAAAAAACQ==/PoweroftheSun1x1-AAAAAAAAAAAAAAAAAAADqQ==.json, config/betterquesting/DefaultQuests/Quests/HowtoGeneratePow-AAAAAAAAAAAAAAAAAAAACQ==/PoweroftheSun1x1-AAAAAAAAAAAAAAAAAAAGtw==.json, config/betterquesting/DefaultQuests/Quests/HowtoGeneratePow-AAAAAAAAAAAAAAAAAAAACQ==/PoweroftheSun1x1-AAAAAAAAAAAAAAAAAAAGuQ==.json, config/betterquesting/DefaultQuests/Quests/HowtoGeneratePow-AAAAAAAAAAAAAAAAAAAACQ==/PoweroftheSun1x1-AAAAAAAAAAAAAAAAAAAK1w==.json, config/betterquesting/DefaultQuests/Quests/HowtoGeneratePow-AAAAAAAAAAAAAAAAAAAACQ==/PoweroftheSun1x1-AAAAAAAAAAAAAAAAAAAK2g==.json, config/betterquesting/DefaultQuests/Quests/MultipleQuestLine/UVSolar-AAAAAAAAAAAAAAAAAAAKGw==.json
Requires https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/1161
=> Update quests to use gt solars

config/gtnhintergalactic.cfg
Related to https://github.com/GTNewHorizons/GTNH-Intergalactic/pull/106
=> Set DS Power Factor for Personal Space Dimensions

config/betterquesting/DefaultQuests/Quests/KillAlltheThings-AAAAAAAAAAAAAAAAAAAAJQ==/TimetoKillSquirr-AAAAAAAAAAAAAAAAAAALFg==.json
=> Fix squirrel killing quest

config/tcneiadditions.cfg
Add the config of TC NEI Additions to the repo, as it was missing.
I changed the second entry to partially resolve https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18946
=> add TC NEI Additions config

config/betterquesting/DefaultQuests/Quests/MultipleQuestLine/SteelChest-V4jinTYRSueIrEqn90dRzQ==.json
Fixed a small typo, changed the word "hass" to "has"
=> Fixed small typo in SteelChest-V4jinTYRSueIrEqn90dRzQ==

config/betterquesting/DefaultQuests/Quests/Tier12UMV-l37V2WvbSHGZQ5oMgAfBuw==/SavingonSpaceTim-hWXZi-whQfmgWO0EII7g2g==.json
Removed last line from the quest as it's wrong. Also, the controller tooltip already explains how it speeds up the recipes.
=> UMV CoAL quest correction

config/AppliedEnergistics2/AppliedEnergistics2.cfg
=> Update AppliedEnergistics2.cfg - fix typo

config/betterquesting/DefaultQuests/Quests/FishingFarmingCo-AAAAAAAAAAAAAAAAAAAACg==/WaxOnWaxOff-AAAAAAAAAAAAAAAAAAAJZQ==.json
(cherry picked from commit 15f6967ca3408db32c2594709f6d0231ee40d7e8)
=> you cant scan it at this time

config/enderio/SAGMillRecipes_User.xml
Part of https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/1206
=> Change Obsidian SAG Milling recipe from 4->2 Dust

config/GregTech/Pollution.cfg
Related to https://github.com/GTNewHorizons/GT5-Unofficial/pull/4092
=> Update large boiler pollution values

config/betterquesting/DefaultQuests/Quests/Tier9UHV-AAAAAAAAAAAAAAAAAAAALg==/BioCircuit2Biolo-AAAAAAAAAAAAAAAAAAAKZw==.json
=> Fixed typo in Biocircuit2Biolo

config/etfuturum/world.cfg
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/19454
=> Amethyst only spawn in OW

config/txloader/forceload/____gtnhoverridenames/lang/en_US.lang
Related PRs:
- https://github.com/GTNewHorizons/Railcraft/pull/77
- https://github.com/GTNewHorizons/ThaumicBases/pull/49
- https://github.com/GTNewHorizons/WitchingGadgets/pull/71
- https://github.com/GTNewHorizons/Tainted-Magic/pull/32
=> Change 'Void metal' -> 'Void Metal'

config/enderio/SAGMillRecipes_User.xml
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/19464
=> Fix SAG Mill for Blaze Rods giving IC2 sulfur

config/betterquesting/DefaultQuests/Quests/Tier05Steam-AAAAAAAAAAAAAAAAAAAAAg==/THENETHER-AAAAAAAAAAAAAAAAAAAB3w==.json
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18678#issue-2773080777
=> Make obsidian optional for nether quest

config/betterquesting/DefaultQuests/Quests/GettingAround-bAal8kZ3R8eRTwaHgbYkKA==/Betterbootswitha-AAAAAAAAAAAAAAAAAAAI1A==.json, config/betterquesting/DefaultQuests/Quests/GettingAround-bAal8kZ3R8eRTwaHgbYkKA==/Walkalloveryou-AAAAAAAAAAAAAAAAAAAI1Q==.json, config/betterquesting/DefaultQuests/Quests/GettingAround-bAal8kZ3R8eRTwaHgbYkKA==/Walkingacrossthe-AAAAAAAAAAAAAAAAAAAI1g==.json
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18912#issue-2819248610
=> Voidwalker quest compat

config/AWWayofTime.cfg
Use new config from https://github.com/GTNewHorizons/BloodMagic/pull/80
=> Disable flask repair

config/Betterloadingscreen/tips/en_US.txt
=> add new loadingscreen tip

config/bettercrashes.cfg
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/19904
=> Update link to crashes on tracker

config/betterquesting/DefaultQuests/Quests/BeeBreeding-AAAAAAAAAAAAAAAAAAAAEw==/Oil-AAAAAAAAAAAAAAAAAAAIdw==.json
Changed the Oil Princess Quest to update description to the correct bee referenced in the description.
Closes: #19865
Before & After Photos
=> Oil Bee QB Changes

config/IC2NuclearControl.cfg
guess capes are removed some code update before
=> add new Alarm to nc config

config/betterquesting/DefaultQuests/Quests/Tier3HV-AAAAAAAAAAAAAAAAAAAABQ==/Chloroform-AAAAAAAAAAAAAAAAAAAHFQ==.json
The quest description kinda makes it seem like you need a lot of chlorine, which you don't since you can recycle the HCl byproduct and recover all of it.
relates to #17882
=> Update Chloroform quest description

config/betterquesting/DefaultQuests/Quests/MultipleQuestLine/MallardRustSmell-AAAAAAAAAAAAAAAAAAAFiA==.json
The ABS can now take multiple energy hatches. Part of [Improve Upgradability of Alloy Blast Smelter #19791](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/19791).
=> Update ABS Quest

config/betterquesting/DefaultQuests/Quests/Tier5IV-AAAAAAAAAAAAAAAAAAAABw==/Universalpickaxe-VoQ7oLYhTjuomLCz_ddOhA==.json
Changed Vajra to new GT Version, added additional information about how to switch modes, and how to swap old Vajra to new Vajra.
New Quest Page:
=> Updated Vajra Quest to new Non-ARR Vajra

config/txloader/load/galacticraftcore/sounds.json, config/txloader/load/minecraft/sounds.json
This PR adds the new soundtracks by Sol IX. 
Flora is added to the tracks which can play in the overworld, and Absolute Zero and Nebula Lullaby will be in the rotation with the galacticraft space music. I have weighted them 3, which makes them a bit more likely to be chosen by the game than the vanilla tracks.
=> Add new music tracks by Sol IX

config/NEI/client.cfg
Been the default for 3 years now
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/commit/517eecc03046c9e56e9af9b293dacc0cf518a1ac
=> Disable NEI Cheat Mode by default

config/SpiceOfLife.cfg
Previous version ran into an issue with specifically 1 hunger foods not losing value until you had 9 of them
=> Adjust Spice Of Life Formula

config/backhand.cfg
Torch tweaks require https://github.com/GTNewHorizons/Backhand/pull/100
=> add default backhand config

config/betterquesting/DefaultQuests/Quests/MultiblockGoals-AAAAAAAAAAAAAAAAAAAADA==/PlayingWiththeBi-AAAAAAAAAAAAAAAAAAAJXQ==.json
I can't test it right now, but this should remove the task for the chem plant manual
=> Remove chem plant manual

config/betterquesting/DefaultQuests/Quests/Tier5IV-AAAAAAAAAAAAAAAAAAAABw==/PotassiumNitrate-AAAAAAAAAAAAAAAAAAAGpw==.json
- Quest was autocompleting due to faulty logic, I removed optional task in order to make it work again.
This will fix and close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/19713.
=> Fixes Potassium Nitrate Quest

config/betterquesting/DefaultQuests/Quests/MultiblockGoals-AAAAAAAAAAAAAAAAAAAADA==/HotHotHot-AAAAAAAAAAAAAAAAAAAIFQ==.json
the item doesn't give a potion effect anymore
=> remove note about potion particle effect for pizza glove quest

config/betterquesting/DefaultQuests/Quests/BuildingBetterBa-AAAAAAAAAAAAAAAAAAAADQ==/CopperShulkerBox-dbax1OsmRpWMg6Pt4tE_ig==.json, config/betterquesting/DefaultQuests/Quests/BuildingBetterBa-AAAAAAAAAAAAAAAAAAAADQ==/GoldShulkerBox-YFUK2QflT1G3_WC8XBp2Wg==.json, config/betterquesting/DefaultQuests/Quests/BuildingBetterBa-AAAAAAAAAAAAAAAAAAAADQ==/IronShulkerBox-StA9TvxxSi2n2c7wQdCAFA==.json, config/betterquesting/DefaultQuests/Quests/BuildingBetterBa-AAAAAAAAAAAAAAAAAAAADQ==/SilverShulkerBox-nc1Pqje3RIe_Yp6WoPOFzg==.json, config/betterquesting/DefaultQuests/Quests/CoinsCoinsCoins-AAAAAAAAAAAAAAAAAAAAEA==/Shulker-C8FHZDizTnax3tt7HvnkBw==.json, config/betterquesting/DefaultQuests/Quests/MultipleQuestLine/APortableBarrel-EDtFbLVvQX2Y5mQp84W9bw==.json
- Fixes pre-requisite for shulker spawn egg quest to be the same as shulker box quest, rather than the impossibility it was before
- Nerfed the rewards of the low tier shulker quests, they were a little much.
=> Shulker Quest Fixes

servers.json
=> Add Nimera GTNH Server EU

servers.json
=> Add Pumpkin Keep GTNH Server

config/EnhancedLootBags/LootBags.xml, config/txloader/load/dreamcraft/lang/en_US.lang
- Exactly as title states, I assume they were going for Daemon, which is an "ancient" way of writing demon, which goes with the witchery theme. "Deamon" is a made up word and means absolutely nothing.
I would also be willing to just change it to Demon, but I thought I would keep the flavor in there.
=> Changes "Deamon" to "Daemon"

config/etfuturum/tweaks.cfg
No end cities so they spawn like enderman in the end, just not as common.
=> Enable shulker spawning in end

config/NEI/collapsibleitems.cfg
issue: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/20604
=> Add Collapsibleitems group for transformers

config/betterquesting/DefaultQuests/Quests/BuildingBetterBa-AAAAAAAAAAAAAAAAAAAADQ==/ConcreteandGTSto-AAAAAAAAAAAAAAAAAAAHmA==.json
followup for https://github.com/GTNewHorizons/GT5-Unofficial/pull/4910
=> Reword concrete quest to indicate that Chisel and GT variants provide the same boost

config/betterquesting/DefaultQuests/Quests/HowtoGeneratePow-AAAAAAAAAAAAAAAAAAAACQ==/PoweroftheSunatL-AAAAAAAAAAAAAAAAAAADqA==.json
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/21415
dont know if even more was changed about solars but this fixes LV at least.
=> fix lv solar quest prereqs

config/betterquesting/DefaultQuests/Quests/FlowerPower-AAAAAAAAAAAAAAAAAAAAIA==/Asgardandelion-M7CE2a0uSOSZZsyNloB0zg==.json, config/betterquesting/DefaultQuests/Quests/FlowerPower-AAAAAAAAAAAAAAAAAAAAIA==/CreativeManaTabl-ykz6BsyOTl2m_xfS28ofXA==.json, config/betterquesting/DefaultQuests/Quests/FlowerPower-AAAAAAAAAAAAAAAAAAAAIA==/Loonium-r3fKz87vRk23Tv2TRGarvg==.json
botania distinguishes many items by NBT, so don't ignore NBT.
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/21468
=> fix 3 botania quests

config/TooMuchLoot/loot/strongholdCorridor.xml
those two items dont exist or don't exist anymore. Fixes https://discord.com/channels/181078474394566657/522098956491030558/1421198908503097484
=> clean up broken stronghold chest loot

config/betterquesting/DefaultQuests/Quests/Tier0StoneAge-AAAAAAAAAAAAAAAAAAAAAQ==/DontBurnYourFing-AAAAAAAAAAAAAAAAAAAAKQ==.json
Depends on https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/1386
=> Update glove quest to reflect new bauble slots

config/enderio/OreDictionaryPreferences_User.xml, config/enderio/SAGMillRecipes_User.xml
I skipped "Aluminum Brass Dust", since it appears the input is unobtainable.
=> Create GregTech dusts in SAG Mill.

config/betterquesting/DefaultQuests/Quests/StoringandTransf-AAAAAAAAAAAAAAAAAAAAIQ==/PowerGoggles-GvlZG9IESmW2qsEMw-hkIw==.json
=> Add mention of the powergoggles command

config/vendingmachine/tradeDatabase.json
Steps:
1. Publish VM 0.4.0 to maven repo https://nexus.gtnewhorizons.com/#browse/browse:releases:com%2Fcubefury%2Fvendingmachine%2FVendingMachine
2. Add VM to GT5U modlist https://github.com/GTNewHorizons/GT5-Unofficial/pull/5009
3. Update BetterQuesting with VM integration https://github.com/GTNewHorizons/BetterQuesting/pull/176
4. **Add Default Trade list to config in main modpack repo (This PR)**
5. Update Coremod with recipes https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/1398
=> Add vending machine trades
